### ISSUE TITLE
Add support for Node.js v22 Current

### ISSUE THREAD

**Issue by cclauss** [actions/setup-node#1016]
**Description:**
Please add support for `Node.js v22 Current`... https://github.com/nodejs/node/releases

**Justification:**
Add testing on the latest version of Node.js.

**Are you willing to submit a PR?**
No.

**Comment by cclauss** [comment]
Seems like Mac and Ubuntu work out-of-the-box but Windows has issues:
* nodejs/node#52682

**Comment by HarithaVattikuti** [comment]
Hello @cclauss 
Thank you for creating this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by cclauss** [comment]
https://github.com/npm/cli/releases/tag/v10.7.0 seems to fix things!
```yaml
      # Temporary workaround for Node.js v22 on Windows
      - if: matrix.node-version == '22' && runner.os == 'Windows'
        shell: bash  # Not pwsh!!!
        run: |
          npm --version  # 10.5.1
          npm install -g npm  # >= https://github.com/npm/cli/releases/tag/v10.7.0
          npm --version  # 10.7.0
```
