### ISSUE TITLE
Attempting to download... Not found in manifest. Falling back to download directly from Node

### ISSUE THREAD

**Issue by jcrgaprende** [actions/setup-node#1017]
**Description:**
When you want to download the version of Node, it fails when trying to do so, there are no more logs for the error

<img width="838" alt="image" src="https://github.com/actions/setup-node/assets/114514822/8987a033-57cb-4e2a-b595-3e4dc539eb0e">

**Action version:**
V4

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

Node v14

**Comment by sujanbasnet** [comment]
I got the same error when defining a specific node version to use with `node-version`. But it was able to download the same version when I used `node-version-file`.

|node-version| node-version-file|
|-|-|
|<img width="1034" alt="image" src="https://github.com/actions/setup-node/assets/25930345/9834234a-4a36-4a69-9ae7-eaaec1d914a4">|<img width="1039" alt="image" src="https://github.com/actions/setup-node/assets/25930345/f7f269f5-a000-40ab-8629-4225a106095f">|

**Comment by jcrgaprende** [comment]
@sujanbasnet i test it, and tell you if works for me. thanks

**Comment by yairlopez-aprende** [comment]
Hi @sujanbasnet, thanks for the help!

How are you using the action exactly (it isn't visible in your screenshot)? 
Are you using both `node-version: '14.21.3'` and `node-version-file:  '14.21.3'` for example or just `node-version-file:  '14.21.3'`?

Thanks!

**Comment by bilalbokharee** [comment]
Hi. I also have a similar error. This is my job:

```
build_macos_x64:
    name: macOS (x86_64)
    env:
      npm_config_arch: x64
    runs-on: macos-latest
    steps:
      
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
      
      - name: Setup NodeJS 
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/fermium' #Resolves to v14.21.3
```
Here is the screenshot of failing step:

![image](https://github.com/actions/setup-node/assets/24479334/01a526dc-15fc-45ee-9f94-95b1f5c8adbb)

Notice that `npm_config_arch` has a value set to `x64` and it fails saying 

"Error: Unable to find Node version 'v14.21.3' for platform darwin and architecture **arm64**."

**Comment by yairlopez-aprende** [comment]
Exactly @bilalbokharee , I've noticed the same thing, and the Github repo where it pulls the package from does not have node v14.21.3 for arm64:
https://github.com/actions/node-versions/releases?expanded=true&page=7&q=14.17.3

It looks like we'll either have to download/install the package from the node.js website or upgrade to a newer verion of node.

<img width="1059" alt="image" src="https://github.com/actions/setup-node/assets/109602146/15119b0c-bd93-4578-b127-04f652474f26">

**Comment by bilalbokharee** [comment]
Yeah I agree but the point is that I am not asking it to download for arm64. I want to download for x64, and this was working up until yesterday. Now it is automatically assuming the request is for arm64.

**Comment by yairlopez-aprende** [comment]
Yeah, that's because macos-latest is now macos-14 which uses arm64 architecture, if you use macos-12 it should work fine.

This is exactly my issue, but I need macos-latest(14) to use Xcode 15.

Downgrading to macos-12, which was macos-latest until this week should solve your issue.

**Comment by yairlopez-aprende** [comment]
I have found a simpler solution that seems to work ( haven't actually built my App yet), at least I am able to install Node.js v14 on macos-14.

Since the arm64 package isn't available I went ahead and set `architecture: 'x64'`, it looks like it will work :)

  build:
    runs-on: macos-14
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '14.17.3'
          architecture: 'x64'
          
        
<img width="1031" alt="image" src="https://github.com/actions/setup-node/assets/109602146/7a2df796-786b-4ef4-b09b-8d04ac410af4">

**Comment by HarithaVattikuti** [comment]
Hello @jcrgaprende 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by sujanbasnet** [comment]
> Hi @sujanbasnet, thanks for the help!
> 
> How are you using the action exactly (it isn't visible in your screenshot)? Are you using both `node-version: '14.21.3'` and `node-version-file: '14.21.3'` for example or just `node-version-file: '14.21.3'`?
> 
> Thanks!

I replaced `node-version` with `node-version-file` and provided the `package.json`.

```yml
- uses: actions/setup-node@v4
  with:
    # node-version: "18.8.2"
    node-version-file: "clients/web/storefront/package.json"
```

**Comment by priya-kinthali** [comment]
Hello there 👋,
Thank you for providing the details. We appreciate your patience and cooperation. 
To utilize the x64 architecture on `macos-latest`, please adjust your workflow configuration as follows:

 ```yml
- uses: actions/setup-node@v4
   with:
      node-version: "14.17.3"
      architecture: 'x64' 
```
Please note if you're aiming to use an arm64 package, an upgrade is necessary. This is due to the lack of support for arm64 packages for Node 14 on the official Node.js website. 
Feel free to try this solution and let us know if any issues arise.
