### ISSUE TITLE
supporting installing node into an alpine based container

### ISSUE THREAD

**Issue by fagai** [actions/setup-node#109]
I use alpine linux for my container.

```
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:7.3-fpm-alpine

    steps:
    - uses: actions/checkout@v1

    - name: use Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install
      run: npm install
```

actions/setup-node succeeds, but npm install fails.

```
Run npm install
  npm install
  shell: sh -e {0}
env: can't execute 'node': No such file or directory
##[error]Process completed with exit code 127.
```

Is there a way to work with alpine linux?

**Comment by Swiftwork** [comment]
Hi @fagai,

As you you might have noticed alpine is a very bare-bones container and is often used for hosting small containers. php:7.3-fpm.alpine does indeed not contain nodejs as seen in this [Dockerfile](https://github.com/docker-library/php/blob/master/7.3/alpine3.11/fpm/Dockerfile). So you will have to find another image that suits your needs or create your own like this [Dockerfile](https://github.com/shopsys/project-base/blob/master/docker/php-fpm/Dockerfile) and push it to [Docker Hub](https://hub.docker.com/) or any other repository you might have access to.

**Comment by fagai** [comment]
@Swiftwork 
Isn't this an action to include node.js?

**Comment by Swiftwork** [comment]
You are right @fagai, I'm not sure what I was thinking 😅

**Comment by bryanmacfarlane** [comment]
Node doesn't have a dist yet for alpine where you can pull JIT
https://nodejs.org/dist/index.json

But they do publish alpine containers with node
https://hub.docker.com/_/node 

Can you elaborate on your scenario a bit?  Are you trying to test your lib on alpine with node?  Are you trying to test a node app meant to distribute with node?

**Comment by fagai** [comment]
@bryanmacfarlane 
I wanted to build assets with a personal alpine linux image.
However, I now use the standard ubuntu-latest.

**Comment by bryanmacfarlane** [comment]
Have you considered something like this instead?

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'node:12.16.1-alpine3.9'

    steps:
    - uses: actions/checkout@v1
    - name: npm install
       run: npm install
```

Note that you end up with node 12 in an alpine container and the toolset is sealed (good practice in containers).

If you need to customize the container then you can docker build from that image.
