### ISSUE TITLE
Unable to publish to Github unless I append username to front

### ISSUE THREAD

**Issue by Aetherinox** [actions/setup-node#1108]
**Description:**
Workflow scope not being detected / defaults to npm when attempting to upload to both npmjs.com and Github.

**Action version:**
v4

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
- node: v20.15.0
- npm: 10.7.0

**Repro steps:**  
- Set up a worker for pushing to both Github and npmjs (see below)

**Expected behavior:**
Worker should publish to both npmjs and github with the same workflow.

**Actual behavior:**
Created a single github workflow, it publishes to Github and npmjs

```yml
        - name: "⚙️ Setup Node"
          id: task_gpr_node_setup
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            registry-url: https://npm.pkg.github.com/
            scope: '@aetherinox'
```

In the example above, I've provided the `scope`, as well as the Github npm repo. However, when actually running the workflow, I get:
```
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-07-11T08_50_52_693Z-debug-0.log
```

What I've noticed is that I can get Github to successfully publish my package, but I must modify my package name itself. If I change the package name to:
```
"name": "@aetherinox/node-toasted",
```

It works fine, however, if I use
```
"name": "node-toasted",
```

I get the error listed above. And after searching this git repo issue section; I've noticed quite a few are getting it, but no definitive solution. I've ensured my tokens are right, and they are. As soon as I switch the package name to include @username, then it publishes fine.

Obviously this could be a solution, but I'd prefer my packages don't start with my username on npmjs, otherwise it makes searching more complicated.

I was assuming `scope` is what would allow for a package name, without the need for the username at the beginning.

Here is one of the failed runs:
- https://github.com/Aetherinox/node-toasted/actions/runs/9888400127/job/27312234841

And here is the successful run:
- https://github.com/Aetherinox/node-toasted/actions/runs/9888304349/job/27311913154

For now I've removed the npmjs publish code until I can figure out how to publish to github without the name being appended to the front.

Here is the workflow file:
- https://github.com/Aetherinox/node-toasted/blob/main/.github/workflows/npm-publish.yml

A little messy with now until I get this figured out.

I did however, review the logs from the workflow, and saw this, which doesn't make sense. If it's seeing that scope, why the package name change:
```
Run actions/setup-node@v4
  with:
    node-version: 20.x
    registry-url: https://npm.pkg.github.com/
    scope: aetherinox
    always-auth: false
    check-latest: false
    token: ***
```

Also tried both scopes:
```yml
  scope: @aetherinox

  scope: aetherinox
```

And I tried printing `/home/runner/work/_temp/.npmrc`:

```
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
@aetherinox:registry=https://npm.pkg.github.com/
always-auth=false
```

Been reading around, and someone posted using
```
npm init -y --scope 'scope name'
```

during the build process, however, it seems to cut off part of the name

`name: 'node-toasted'` becomes `name: '@aetherinox/toasted'`

**Comment by Aetherinox** [comment]
An update, hopefully you may have alternative ideas.

I assumed by using `setup-node` action with the `scope` parameter, it would take care of Github's requirement to specify a scope, so that the name could be without.

Then I attempted `npm init --scope`, and it was removing `node` from the front of the package name. Apparently that's something the developers of npm have put in place. It doesn't remove other random words, but if you put `node` in the package name, it strips the word all together.

So that leaves the options to simply re-name the package, or before running `npm publish`, doing a find and replace in the `package.json` file for the original package name, and changing it to start with a scope.

```yml
  - name: Find and Replace
    uses: jacobtomlinson/gha-find-replace@v3
    with:
      find: '"name": "node-toasted"'
      replace: '"name": "@aetherinox/node-toasted"'
      include: "package.json"
      regex: true
```

Then the package publishes successfully.
