### ISSUE TITLE
Issue with Saving Yarn Cache on Self-Hosted Runner

### ISSUE THREAD

**Issue by marouanechoukri31** [actions/setup-node#1113]
**Description:**
A problem occurred while saving the yarn cache using a self-hosted runner. The process works correctly on the hosted runner.

**Error :**

`
Failed to save: Unable to reserve cache with key node-cache-macOS-yarn-33259bc05a9ff84ddf70121c6ada6b7886b9a8e9721b785469c879d852cc411e, another job may be creating this cache. More details: Cache already exists.
`

**Code :** 

```

- name: Use Node.js
  uses: actions/setup-node@v4
  with:
     node-version: '20.15.1'
     cache: 'yarn'

```

**Action version:**
Version 4

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

Node version : 20.15.1
Yarn version : 1.22.22
