### ISSUE TITLE
lts/* isn't installing the latest LTS

### ISSUE THREAD

**Issue by nex3** [actions/setup-node#1153]
**Description:**

The current Node LTS at time of writing is v22.11.0. If I run `nvm install lts/*` locally, that's what gets installed. However, when I select `lts/*` for GitHub actions, I am getting v20.18.0 instead.

You can see this in [this CI run](https://github.com/sass/embedded-host-node/actions/runs/11583275447/job/32248116750), which I've screenshotted for posterity:

![image](https://github.com/user-attachments/assets/733b28db-3d8f-4984-89ac-4914510f68f0)

This is [the corresponding action configuration](https://github.com/sass/embedded-host-node/blob/768c1f61af6a245cfce7c9aca921384d452f70ca/.github/workflows/ci.yml#L50-L53):

```yaml
  tests:
    name: 'Tests | Node ${{ matrix.node-version }} | ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        node-version: ['lts/*', 'lts/-1', 'lts/-2']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
```

**Action version:**

`v4`, which is currently 39370e3970a6d050c480ffad4ff0ed4d3fdee5af

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

See above screenshot.

**Repro steps:**  

See links above.

**Expected behavior:**

This should install the latest Node.js LTS and the same version as `nvm install lts/*`, v22.11.0.

**Actual behavior:**

This is installing v20.18.0.
