### ISSUE TITLE
Yarn installs failing in GitHub Actions after updating to Node 23.0.0

### ISSUE THREAD

**Issue by danascheider** [actions/setup-node#1157]
**Description:**
I have a React app that uses GitHub Actions for CI. After upgrading its Node version to 23.0.0, the dependency installation step fails saying "The remote archive doesn't match the expected checksum." I am not able to replicate these errors in my local environment.

This is set up in my `.github/workflows/ci.yml` file as follows:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: "23.0.0"
    - name: "install Node Modules"
      run: yarn
```

As soon as I changed `node-version: "22.11.0"` to `node-version: "23.0.0"`, the builds started failing.

**Action version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node: 23.0.0
npm: 10.9.0
yarn: 3.6.4

**Repro steps:**  
This is an example of one of the [failing builds](https://github.com/danascheider/skyrim_inventory_management_frontend/actions/runs/11694749998/job/32568968480?pr=693). I made two PRs that failed. The commonalities are that Node is updated to 23.0.0 in the `package.json`, `.tool-versions`, and `ci.yml` files.

**Expected behavior:**
I expected my build to continue running, and passing, like it was until I updated Node.

**Actual behavior:**
`yarn install` fails, indicating that "The remote archive does not match the expected checksum"

**Comment by mahabaleshwars** [comment]
Hello @danascheider,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by priyagupta108** [comment]
Hi @danascheider 👋,
It appears there's an issue on Node's side with version 23.0.0. For more details, see nodejs/node#55414
To resolve this, use the latest version of Node 23, which is 23.2.0. Alternatively, you can specify:
```yaml
uses: actions/setup-node@v4
with:
  node-version: '23'
```
This configuration ensures that the action will automatically download the latest available release for Node.js version 23.
