### ISSUE TITLE
error 'manifest.filter is not a funcion' when using node-version with "lts/*"

### ISSUE THREAD

**Issue by giulianisanches** [actions/setup-node#1162]
**Description:**
I'm trying to install the latest LTS version using the syntax `"lts/*"` and getting the error `manifest.filter is not a function`. Using a different syntax, like `22.x` works.

```yaml
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
```

**Action version:**
actions/setup-node@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
Default ones installed with ubuntu 20.04

**Repro steps:**  
I just have an action like below, and it fails when I push to the `wip` branch:

```yaml
name: Build

on:
  push:
    branches:
      - wip

jobs:
  build:
    environment: shared
    runs-on: [self-hosted]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
```

**Expected behavior:**
I expect it to install the latest LTS version

**Actual behavior:**
build fails with the message `manifest.filter is not a function`
