### ISSUE TITLE
provide cache datails as outputs

### ISSUE THREAD

**Issue by sherif-amk** [actions/setup-node#1181]
`actions/setup-node` should output cache details such as:
- path
- key
- hits: boolean
- size
- last_updated

```
   steps:
       - name: install NodeJs
        id: node
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - name: use pnpm cache //<-- may be in another job
        uses: actions/cache
        with:
          path: ${{ step.node.outputs.path }}
          kay: ${{ step.node.outputs.kay }}
```
