### ISSUE TITLE
E401: Invalid authentication token when using Azure Artifacts registry

### ISSUE THREAD

**Issue by Wouter8** [actions/setup-node#119]
Trying to setup a workflow for my Angular project. I have 1 private package which is hosted at Azure.

I created a PAT with read/write access in Azure and added it to the repository secrets. This is being used by another GitHub action, which requires a private NuGet package, and is working fine.

My current workflow looks like this (removing the .npmrc manually just to be sure it's completely from the action):
```
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workingDirectory: ./wv8-finance-front-end

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.0
      with:
        registry-url: 'https://pkgs.dev.azure.com/woutervanacht/_packaging/Wv8-NuGet-Feed/npm/registry/'
        always-auth: 'true'
    # Remove custom npmrc
    - run: rm .npmrc
      working-directory: ${{env.workingDirectory}}
    # Skip post-install scripts here, as a malicious
    # script could steal NODE_AUTH_TOKEN.
    - run: npm install --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT }} 
      working-directory: ${{env.workingDirectory}}
    # `npm rebuild` will run all those post-install scripts for us.
    - run: npm rebuild && npm run prepare --if-present
      working-directory: ${{env.workingDirectory}}
    # build angular production configuration
    - run: npm run ng build --prod
      working-directory: ${{env.workingDirectory}}
```

The log (from `npm install` step):
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nan@2.14.0 (node_modules/@angular/compiler-cli/node_modules/nan):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unable to authenticate, your authentication token seems to be invalid.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: parse5@5.1.0 (node_modules/@angular/cdk/node_modules/parse5):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Unable to authenticate, your authentication token seems to be invalid.

npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login
```
