### ISSUE TITLE
Environment details is empty and node is not found

### ISSUE THREAD

**Issue by ValentinVignal** [actions/setup-node#1210]
**Description:**

It seems like node is not installed after using the action. Unfortunately, I cannot provide a reproductible example or a link as my company's repository is private.

After running 

```yaml
- uses: actions/checkout@v4
- uses: actions/setup-node@v4
```

when I try to use `node`, I get the error `node: command not found`.

Also, the logs about environment details seem empty:

```
Environment details
  node: 
  npm: 
  yarn:
```

I might be missing something or it might be because of my company's repos rules/set up.

What could it be ?

**Action version:**
`v4`

**Platform:**
I'm not sure as I don't have access to the details of the image but I think it would be Ubuntu
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**

The logs seems empty (look at Environment details)

```
Run actions/setup-node@v4
  with:
    always-auth: false
    check-latest: false
    token: ***
  env:
    PATH: ***
Run '/home/runner/k8s/index.js'
  shell: /home/runner/externals/node {0}
Environment details
  node: 
  npm: 
  yarn:
```

I get the error 

``node: command not found``

**Comment by mahabaleshwars** [comment]
Hi @ValentinVignal,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by gowridurgad** [comment]
Hi @ValentinVignal, We were unable to reproduce the issue on the provided workflow. The environment fields are populated correctly. Please see the screenshot below for reference.
Here are some troubleshooting steps you can follow:
1. **Verify Node.js Version:** Ensure that the node-version parameter is specified correctly in the workflow file.
```
- uses: actions/setup-node@v4
  with:
      node-version: '21' 
```
2. **Check PATH Configuration:** Ensure the PATH environment variable includes the path to the node binary. Add a step to print the PATH variable:

`- run: echo $PATH`

If the issue persists and you are unable to provide a reproducible link, please share your workflow file with the relevant configuration for further assistance.

Additionally, could you please confirm whether you are using a GitHub-hosted or self-hosted runner? If you are using a GitHub-hosted runner, even if you do not pass the node version, you will get the default values.

<img width="1551" alt="Image" src="https://github.com/user-attachments/assets/c7be0eca-571a-47f7-a3e0-b8338ee3e67d" />

**Comment by gowridurgad** [comment]
Hi @ValentinVignal, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by ValentinVignal** [comment]
@gowridurgad sorry for the late reply. Unfortunately, I don't have access to the image created by my company. I can only read it.

We can close this issue as I cannot have more information.

Thank you again for the help

**Comment by BeyondEvil** [comment]
I got this error on our self-hosted runners.

If I use:

```yaml
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
```

I get the issue.

If I instead to:

```yaml
      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
```

I don't. 🤷
