### ISSUE TITLE
Security: `lts/*` installs old LTS versions up to 9 days after release

### ISSUE THREAD

**Issue by karlhorky** [actions/setup-node#1236]
**Description:**

Using the `lts/*` alias with `actions/setup-node` installed Node.js v22.13.0 as of 25 Jan 2025, an old version. [Node.js v22.13.1](https://nodejs.org/en/blog/release/v22.13.1) has been out since 21 Jan 2025.

⚠️ Security: Node.js v22.13.1 contains [security updates](https://nodejs.org/en/blog/vulnerability/january-2025-security-releases) and as such, this can be considered a security problem

```yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          check-latest: true
```

Workflow logs:

```
Run actions/setup-node@v4
  with:
    node-version: lts/*
    always-auth: false
    check-latest: false
    token: ***
  ...
Attempt to resolve LTS alias from manifest...
Found in cache @ /opt/hostedtoolcache/node/22.13.0/x64
Environment details
  node: v22.13.0
  npm: 10.9.2
  yarn: 1.22.22
```

Longer update delays of over 5 days can be seen in actions/setup-node#940 

**Action version:**

actions/setup-node@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node.js lts/*

```
  node: v22.13.0
  npm: 10.9.2
  yarn: 1.22.22
```

**Repro steps:**  

Use the configuration above and observe the output above

**Expected behavior:**

Node.js latest LTS (20.11.0) is installed

**Actual behavior:**

Node.js older LTS (20.10.0) is installed

**History:**

Originally reported in https://github.com/actions/setup-node/issues/940, but closed without resolution, with @aparnajyothi-y saying that it should be handled on the runner side:

> @aparnajyothi-y in [comment 2247503445](https://github.com/actions/setup-node/issues/940#issuecomment-2247503445): cache eviction should not be handled on the runner side

In speaking with the runner images team, @hemanthmanga mentioned it should not be handled on the runner side:

> @hemanthmanga in [comment 2263151956](https://github.com/actions/runner-images/issues/10311#issuecomment-2263151956): As the runner images team, we believe cache eviction should be handled through tasks, not the runner itself

**Comment by karlhorky** [comment]
Ok great, so the problem is the slow hosted tool cache updates / image update schedule from `actions/runner-images`.

I see that:

1. The issue was transferred to `actions/runner-images`
2. Then @erik-bershel transferred it back here to `actions/setup-node`

I'm unsure why 2 happened, or what the reasons / justification behind it was.

But if `actions/runner-images` and `actions/setup-node` cannot agree on the responsibility of fixing the issue, maybe revisiting a rework of the current system is good.

I reworded the suggestion:

What about getting rid of the manifest + PR merging + hosted tool cache updates system (which sometimes fails even with `check-latest`, as I have observed), and instead downloading the version based on other existing tools like nvm?

**Comment by karlhorky** [comment]
> most likely up to six days, but there are exceptions, like now with macOS, where the image has not been updated for a month or so

Hm, that is very surprising default behavior for `actions/setup-node` with any aliases.

Users do not like surprising caching behavior. See as a reference the community feedback to the "cached by default" strategy for Next.js in the last years, which Next.js eventually rolled back.

> This option is [documented on the main page of the tool](https://github.com/actions/setup-node) and the choice is up to the user. The default behaviour is intended to reduce execution time, which is currently a higher priority for the community than the relevance of the package version.
> 
> ```
> Note: Like the other values, * will get the latest [locally-cached Node.js version](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#nodejs), or the latest version from [actions/node-versions](https://github.com/actions/node-versions/blob/main/versions-manifest.json), depending on the [check-latest](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version) input.
> ```

This documentation doesn't imply that the default caching behavior can lead to up to 1 month of delay.

When hearing "latest locally-cached Node.js version" from software from a company with a good reputation like GitHub, I would not imagine that it's significantly out of date, as is the case in the scenarios that we've explored. (and 1 month is of course even more so)

So I would suggest one of two things:

1. If users use aliases or ranges, disable the cache with `check-latest: true` (unless this is also still broken, which I have experienced a few times too)
2. If the default behavior won't change, change the documentation to show that usage of aliases is dangerous with the default `actions/setup-node` and can lead to undetermined delays of up to 1 month or longer

**Comment by karlhorky** [comment]
## Workaround: switch to `nvm`

Full replacement for broken `actions/setup-node` version resolution, with `nvm`:

```yaml
# Use nvm because actions/setup-node does not install latest versions
# https://github.com/actions/setup-node/issues/940
- name: Install latest LTS with nvm
  run: |
    nvm install 'lts/*'
    echo "$(dirname $(nvm which node))" >> $GITHUB_PATH
  shell: bash -l {0}
```

If you also need pnpm caching (replacement for the `cache` setting of `actions/setup-node`), config for `actions/cache`:

```yaml
- name: Get pnpm store directory
  shell: bash
  run: |
    echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
- uses: actions/cache@v4
  name: Setup pnpm cache
  with:
    path: ${{ env.STORE_PATH }}
    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    restore-keys: |
      ${{ runner.os }}-pnpm-store-
```

Also posted on `github-tricks`: https://github.com/karlhorky/github-tricks/blob/main/readme.md#github-actions-correct-broken-actionssetup-node-version-resolution
