### ISSUE TITLE
eslint output indentation breaks problem matcher (Nx monorepo support)

### ISSUE THREAD

**Issue by fregante** [actions/setup-node#1244]
**Description:**

Annotations don't appear when eslint is indented. This happens when using tools like https://nx.dev that orchestrate and group script/tasks in large repos.

It seems that Jest's matcher is not affected

**Action version:**

v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
```json
  "engines": {
    "node": "22.14.0",
    "npm": "10.9.2"
  },
```

**Repro steps:**  

Output this code to console on CI

Problem matched:

```
/home/runner/work/repo/file.ts
    55:5  warning  Unexpected 'todo' comment: 'TODO: Add test for this eventuality:...'     no-warning-comments
```

Problem not matched:

```
  /home/runner/work/repo/file.ts
    14:1  error  'webext-messenger' should be listed in the project's dependencies. Run 'npm i -S webext-messenger' to add it  import/no-extraneous-dependencies
```

**Comment by mahabaleshwars** [comment]
Hi @fregante,
Thank you for creating this issue. We will investigate it and provide feedback as soon as we have some updates.

**Comment by priya-kinthali** [comment]
Hello @fregante👋,
Thank you for reporting this issue and for submitting the related pull request! To help us investigate and understand the problem better, could you please provide a minimal repository that demonstrates the issue? 
Your cooperation is greatly appreciated!

**Comment by fregante** [comment]
Please use the example strings provided in my opening post. Setting up the entire repo just to produce the same output is a bit much. 

The exact repro is:

``` yaml
- uses: actions/setup-node@v4
- run: 
    echo "  /home/runner/work/repo/file.ts"
    echo "    14:1  error  'webext-messenger' should be listed in the project's dependencies. Run 'npm i -S webext-messenger' to add it  import/no-extraneous-dependencies"
```
