### ISSUE TITLE
Support `devEngines` field in `package.json`

### ISSUE THREAD

**Issue by zanminkian** [actions/setup-node#1255]
**Description:**
`devEngines` field is now supported by npm and corepack.

If user set `node-version-file: package.json` in yaml, `setup-node` action should consult both `engines` and `devEngines` fields, while currently only `engines` works.

**Justification:**
In monorepo, the root package.json usually have no `engines` field. Moreover, the `engines`  is for users who install the npm package, while the `devEngines` field is for who developers who develop the npm package. Obviously, `devEngines` is more suitable for `setup-node`.

**Are you willing to submit a PR?**
Yes

**Comment by suyashgaonkar** [comment]
Hi @zanminkian , Thank you for creating this feature request. We will investigate it and provide feedback as soon as we have some updates.

**Comment by mklueh** [comment]
And if anyone is working on this, maybe you could also consider factoring in the volta node field?

<img width="151" alt="Image" src="https://github.com/user-attachments/assets/8c1252f1-6767-4086-9eda-814c65fea818" />

Then you could run `volta pin node@23.11.0` which would fetch and install node, set the node version in package.json `volta.node` and that's all you have to do

**Comment by susnux** [comment]
@mklueh but the volta field is already supported? https://github.com/actions/setup-node/pull/921

**Comment by zanminkian** [comment]
@mklueh volta is not the standard, but `devEngines` is the standard which is supported by npm, pnpm, corepack ...
BTW I don't consider `volta` until it stablely supports pnpm.

**Comment by zanminkian** [comment]
Here is a workaround to support devEngines:
```yaml
      - uses: actions/checkout@v4
      # TODO: Remove this step when https://github.com/actions/setup-node/pull/1283 is merged
      - name: Get Node.js version
        id: get-node-version
        run: |
          node_version=$(jq -r '.devEngines.runtime.version // empty' package.json)
          if [ -z "$node_version" ]; then
            echo "Error: No Node.js version specified in devEngines.runtime.version"
            exit 1
          fi
          echo "node-version=$node_version" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get-node-version.outputs.node-version }}
```
