### ISSUE TITLE
Basic example fails 

### ISSUE THREAD

**Issue by purefan** [actions/setup-node#126]
Hello,

Taking the first example ("Basic") from the Usage section in the Readme.md file fails:
```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
  with:
    node-version: '10.x'
- run: npm install
- run: npm test
```

I am running this locally with `act` but I discarded it being a problem in act by running the yarn step instead of setup-node and it worked. 

The actual output is this:

> [CI/unit-test] Extracting content from '/tmp/act064769060' to '/actions/'
> [CI/unit-test] Exec command '[node /actions/actions-setup-node@v1/dist/index.js]'
> [CI/unit-test]   💬  ::debug::isExplicit: 
> [CI/unit-test]   💬  ::debug::explicit? false
> [CI/unit-test]   💬  ::debug::evaluating 0 versions
> [CI/unit-test]   💬  ::debug::match not found
> [CI/unit-test]   💬  ::debug::evaluating 381 versions
> [CI/unit-test]   💬  ::debug::matched: v12.16.1
> [CI/unit-test]   💬  ::debug::isExplicit: 12.16.1
> [CI/unit-test]   💬  ::debug::explicit? true
> [CI/unit-test]   💬  ::debug::checking cache: /opt/hostedtoolcache/node/12.16.1/x64
> [CI/unit-test]   💬  ::debug::not found
> [CI/unit-test]   ❗  ::error::Expected RUNNER_TEMP to be defined
> [CI/unit-test]   ❌  Failure - actions/setup-node@v1
> DEBU[0010] exit with `FAILURE`: 1                       
> DEBU[0010] exit with `FAILURE`: 1                       
> DEBU[0010] exit with `FAILURE`: 1                       
> Error: exit with `FAILURE`: 1

[This line](https://github.com/actions/setup-node/blob/83c9f7a7df54d6b57455f7c57ac414f2ae5fb8de/src/installer.ts#L195) of code seems relevant

My jobs section looks like this:
```
jobs:
  unittest:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm test
```
