### ISSUE TITLE
Unable to publish to the GitHub Registry

### ISSUE THREAD

**Issue by JamesIves** [actions/setup-node#130]
I've been following this document (and the README): https://github.community/t5/GitHub-Actions/bd-p/actions, specifically the part about cross publishing between npmjs and the GitHub registry, but I can't seem to get it to work. This is my workflow: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/.github/workflows/publish.yml

The problem I'm having is that every time I publish it says I must authenticate, except it's providing a URL related to the npmjs registry: `401 Unauthorized - PUT https://registry.npmjs.org/github-pages-deploy-action - You must be logged in to publish packages.` 

This is the [full log](https://github.com/JamesIves/github-pages-deploy-action/runs/549023729?check_suite_focus=true). Am I missing something here or is this a bug?

**Comment by jasonkarns** [comment]
Same issue:

```
npm notice 
55
npm ERR! code E401
56
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/@nodenv%2fnodenv - You must be logged in to publish packages.
```

with following workflow :

```
npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
```

I think it's a bug (or their docs are wrong).

**Comment by JamesIves** [comment]
Interesting, npmjs seems to pass for me when specifying `registry-url: 'https://registry.npmjs.org'`, but only the GitHub registry seems to fail for me. I'm guessing that whatever mechanism that overrides the `.npmrc` file isn't behaving correctly in my case.

**Comment by JamesIves** [comment]
@jasonkarns Were you able to get this to work for yourself?

**Comment by jasonkarns** [comment]
@JamesIves I needed to explicitly state the `scope` and `registry-url` inputs to the action. Rather frustrating limitation at present, IMO. the scope is redundant information (it's in the package name), and the registry should either default to npm and/or respect the `publishConfig` setting in package.json. But at least it's working :/

**Comment by JamesIves** [comment]
Interesting, I can't seem to get it to work for the life of me. Tried in several repositories now, the publish the first `npmjs.org` publish works.

```yml
   # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'

    - name: Configure git
      run: |
        git config user.email "iam@jamesiv.es"
        git config user.name "James Ives"
    - run: npm install
    - run: npm run-script build
    - run: npm version patch -m "Release %s 📣"
    - run: git push
    - run: npm ci

    # Publish to npm
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'
        scope: '@JamesIves'

    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

However it still doesn't seem to be correctly overwriting the `.npmrc` file after the second call to `setup-node` as I get this error (the `PUT` request is still being made to npmjs.org instead of npm.pkg.github.com)

`401 Unauthorized - PUT https://registry.npmjs.org/github-pages-deploy-action - You must be logged in to publish packages.`

**Comment by petecorreia-appital** [comment]
I've got it working by setting `~/.npmrc` myself with the following:

```yaml
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
```

I also have `.npmrc` files in a few directories with the correct registries define, for example:
```
@example:registry=https://npm.pkg.github.com
```

**Comment by JamesIves** [comment]
> I also have .npmrc files in a few directories with the correct registries define, for example:

Can you provide more context to this? Do you have two `.npmrc` files somehow? I have `@JamesIves/package-name` defined as the name in my `package.json` file and I still can't get it to switch from npmjs to github packages:

```yml
name: publish-to-npm
on:
  release:
    types: [created]
  push: 
    branches:
      - publish-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev

    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}

    - run: ls -a

    - name: Configure git
      run: |
        git config user.email "email@gmail.com"
        git config user.name "James Ives"

    - run: npm install
    - run: npm run-script build
    - run: npm ci

    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
```

I've simplified my workflow so I'm skipping the npmjs step to ensure that nothing is conflicting but it still doesn't work. Running `ls -a` reveals the `.npmrc` file is correctly being created at the root.

**Comment by meister** [comment]
I also ran into similar issue. But after a bit of debugging, it looks like the `.npmrc` file for github registry adds `@scope`, which means if we try to publish a non-scoped package, the authentication fails. You can add
```
run: cat $NPM_CONFIG_USERCONFIG
```
to see if it’s the same for you.
Also by looking at the action code (https://github.com/actions/setup-node/blob/master/src/authutil.ts#L25) it looks like for Github registry, the scope is always added.

So not sure if it’s even possible to publish non-scoped packages in Github, if not, then it sort of conflicts with the NPM and can’t publish to both places with the same `package.json` file, unless a scope is added.

**Comment by JamesIves** [comment]
By scoping do you mean adding `@repoowner/repo-name` within the name field `package.json` or is there a specific scope field I'm not aware of?

**Comment by meister** [comment]
> By scoping do you mean adding `@repoowner/repo-name` within the name field `package.json` or is there a specific scope field I'm not aware of? 

Yes exactly. Just tried it and it started to work. You can then publish the same thing in NPM as well, as long as you add `npm publish —access public`. Otherwise scoped packages there are private by default.

**Comment by chriskacerguis** [comment]
So, I don't know if this applies to your situation or not, but I was having the exact same issue.  I came across this doc 

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#publishing-a-package-using-publishconfig-in-the-packagejson-file 

I added this to my repo and it worked.

```json
"publishConfig": { "registry": "https://npm.pkg.github.com/" },
```

Good luck

**Comment by meister** [comment]
Thanks @chriskacerguis for the info.

But as for me (and  it looks like it’s similar to @JamesIves ), I was trying to publish to both NPM and Github.. But I wonder if with the `publishConfig`, would I still be able to publish to NPM? Or can I then publish to Github without scope?

Either way I renamed my package in NPM with the scope, so that it matches Github, and it started to work.

**Comment by JamesIves** [comment]
I've added the scope to the package name, and it doesn't seem to run with me. For simplicity I even removed the npm publish part from the action file:

https://github.com/JamesIves/fetch-api-data-action/blob/publish-test/.github/workflows/publish.yml

https://github.com/JamesIves/fetch-api-data-action/runs/579411875?check_suite_focus=true

**Comment by edouardr** [comment]
So I was having the same issue. I managed to get my package publish by using below workflow:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@OWNER'
      - name: Authenticate with GitHub package registry
        run:
          echo "//npm.pkg.github.com:_authToken=${{ secrets.PAT }}" >
          ~/.npmrc
      - name: Build and Test
        shell: bash
        run: npm run setup
      - name: Publish
        shell: bash
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
```

What I did was to generate the .npmrc file manually at `~/` and inject a Private Access Token with sufficient permissions.

On top of that, I also used scoped package name in `package.json`.

```json
{
...
  "name": "@owner/package-name",
...
}
```

**Comment by redreceipt** [comment]
We're having the same problem. Locally, it publishes to the correct registry (GPR) but when using Github Actions, it tries to publish to NPM

<img width="747" alt="Screen Shot 2020-09-10 at 3 50 38 PM" src="https://user-images.githubusercontent.com/2659478/92794410-92f1c080-f37d-11ea-93e4-0bfbf4c1641d.png">

Here's our config https://github.com/ApollosProject/apollos-apps/blob/master/.github/workflows/publish.yml

**Comment by redreceipt** [comment]
I did two things. One of them fixed it, not sure which one it was and I'm not going to touch anything 😂 

1. Added `@scope` to the Action config

```yml
    - name: Use Node 10.19.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@apollosproject'
```

2. Added registry to my `lerna.json`. Didn't think it was necessary because I have them defined per package but I gues this action may need it here...

```json
{
  "packages": ["packages/*"],
  "version": "1.5.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": { "publish": { "registry": "https://npm.pkg.github.com" } }
}
```

**Comment by JamesIves** [comment]
I've managed to resolve this with my actions with the following workflow file:

https://github.com/JamesIves/github-pages-deploy-action/blob/dev/.github/workflows/publish.yml

I also added the scope to the package.json file here: https://github.com/JamesIves/github-pages-deploy-action/blob/dev/package.json#L2

**Comment by hpl002** [comment]
Amazing that this hasn't been patched yet. Very misleading that the published actions is broken(for this particular use case) by default.

Please see @JamesIves post for remedy
 - https://github.com/actions/setup-node/issues/130#issuecomment-691103257

**Comment by jojobyte** [comment]
My repo was having a similar issue to this one. Replacing the package name in package.json by adding the scope to it solved it for Github Package Registry.

```json5
// original
{
    "name": "traefikjam",
}

// fix for GPR publish
{
    "name": "@jojobyte/traefikjam",
}
```

My fix: https://github.com/jojobyte/traefikjam/blob/master/.github/workflows/node-build.yml#L40

```yaml
jobs:
  npm-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@scope'
      - run: npm ci
      - name: Publish to GitHub Package Registry
        run: |
          sed -i 's+"name": ".*+"name": "@${{ github.repository }}",+gI' ./package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This lets you publish to NPM with an unscoped package name and GPR with a scoped package name.

**Comment by nhhockeyplayer** [comment]
get off of node v16 and goto v18 for the latest npm
stay away from npmjs.org they are still collecting credit card hits and its not worth the $7 someone is still collecting charity and maybe its well needed but that entire footprint should be a lesson on how NOT to model an ecosystem

node v18... use the latest npm it will accept your scoped package name as appropriate
otherwise it will force you to NOT use the scoped package name which will fail your entire effort

prayers for microsoft to revamp all of this and stabilize this ecosystem for good

**Comment by dsame** [comment]
Hello @nhhockeyplayer 
Despite the node version the name of package must have a scope according to the [docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)

If the package name is not scoped one has to use the workaround like the [one](https://github.com/actions/setup-node/issues/130#issuecomment-1144579893) suggested by @jojobyte 

While we are improving the README, please use the snippet as a reference in order to upload the package to both repos

```
    steps:
...
      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.13.2'
          registry-url: 'https://registry.npmjs.org'

      - name: publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish

      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.13.2'
          scope: '@akv-demo'
          registry-url: 'https://npm.pkg.github.com'

      - name: publish to github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          npm publish 
```

and the package.json must have both scope name and repository url match the github repo:

```
{
  "name": "@akv-demo/pkg1",
  ...
  "repository": {
    "url": "https://github.com/akv-demo/setup-node-test",
    "type": "git"
  }
}

```

The corresponding build is here: https://github.com/akv-demo/setup-node-test/runs/7819174590?check_suite_focus=true

and as it was already noted one of the reason of  "401 Unauthorized - PUT https://registry.npmjs.org/github-pages-deploy-action - You must be logged in to publish packages" might be the package is not initially created with the public access.
