### ISSUE TITLE
Provide a output for the selected Node.js version

### ISSUE THREAD

**Issue by LinusU** [actions/setup-node#150]
It would be great if there could be an output that tells which exact version of Node.js was installed.

An example use case for this is cacheing `node_modules`, which is only valid for the same OS + Node.js version + package-lock combination:

```yml
name: Node CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v1
      with:
        node-version: 12.15.0

    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      if: steps.cache-node-modules.outputs.cache-hit != 'true'

    - name: Tets
      run: npm test
```

**Comment by kennethtran93** [comment]
There's a workaround for this in the meantime:

```yml
    - name: Get NodeJS Version
      id: nodeversion
      run: |
        echo "::set-output name=version::$(node --version)"
```

Then in the future steps you can call it ```${{ steps.nodeversion.outputs.version }}```

I only adapted this from another workflow which calls a different command, but this should work for what you are doing.  Just put this after `setup-node`

**Comment by bryanmacfarlane** [comment]
I don't think it even needs to be an output.  On the target side (which would read the output for this proposal) simply do a $(node --version) to compose the key.  Writing an output and executing a graph of jobs is fragile because reading the cache shouldn't be based on the previous jobs node version, it should be based on the node version in the job that's consuming the cached node-modules.

**Comment by rdmurphy** [comment]
Thanks for responding @bryanmacfarlane!

I've been happily using @kennethtran93's suggestion but I don't fully follow — I agree that's the ideal in situations when you're writing a shell script, but is it possible to do the call to `$(node --version)` inline like that within a YAML file using the expression syntax?

I'm using this to do the opposite of your example — based on the Node version (and the system + hashed `package-lock.json`) that was installed I tap into a potentially cached `node_modules`. The main difference is I am doing this with `@v2-beta` where I pass in just a simple `'12'`. I don't really care which `v12` I get but I do want to ensure the cache hit is based on the **exact** version of Node that was eventually installed.

(Not to suggest every `setup-*` library is obligated to repeat what the others do, but FWIW `setup-python` also accepts version ranges as input and [*does* do this](https://github.com/actions/setup-python/blob/master/action.yml#L14-L16) to share what exact version was installed.)

**Comment by panva** [comment]
I just stumbled upon this also needing this. Use case being recalling cached installed node_modules with the cache key containing the node version.

```
- name: Cache node_modules
  uses: actions/cache@v2
  id: node_modules
  with:
    path: node_modules
    key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package.json') }}-${{ steps.node.outputs.version }}
```

@bryanmacfarlane How would you suggest to change the key attribute to use `$(node -v)`?

**Comment by panva** [comment]
See #173

**Comment by panva** [comment]
So are we stuck having to have [this extra step](https://github.com/panva/jose/compare/v3.6.2...v3.7.0#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R117-R120) everywhere? Why is this present in setup-python but for setup-node it's lack of is as-designed?

🙏 #173

**Comment by simondotm** [comment]
I was looking here also to see if there was a succinct way to get the node version for convenience, but as a fall back, is there some reason why the `strategy.matrix` isnt a good enough fall back (rather than getting the node version some other scripty way)?

```
    strategy:
      matrix:
        node-version: [15.x]
    ...
    key: ${{ runner.os }}-node_modules-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
```
