### ISSUE TITLE
No token found and can't prompt for login when running with --non-interactive for gpr-publish

### ISSUE THREAD

**Issue by AjayPoshak** [actions/setup-node#156]
When I run yarn publish in github action for GPR, I get following error

```
yarn publish v1.22.4
warning package.json: No license field
warning package.json: No license field
[1/4] Bumping version...
info Current version: 2.0.0-beta.3
[2/4] Logging in...
error No token found and can't prompt for login when running with --non-interactive.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
##[error]Process completed with exit code 1.
```

Meanwhile it works fine for NPM publish flow.
My workflow configuration: https://github.com/AjayPoshak/instagram-story/blob/master/.github/workflows/npmpublish.yml

**Comment by baptisteArno** [comment]
Same error. Did you make it work @AjayPoshak?

**Comment by AjayPoshak** [comment]
@baptisteArno nope.

**Comment by manovotny** [comment]
I had the same issue and adding `always-auth` and `registry-url` worked for me, [as suggested in this other issue / comment](https://github.com/actions/setup-node/issues/81#issuecomment-623018474).

```yaml
- name: Set node version
  uses: actions/setup-node@v1
  with:
      always-auth: true
      node-version: 12.14.0
      registry-url: 'https://registry.npmjs.org'
```

**Comment by baptisteArno** [comment]
Still not working the same error...

Here is my complete workflow:

```yaml
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by fivethreeo** [comment]
v2 Sets NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc

**Comment by BryanCrotaz** [comment]
I'm seeing the same problem with `registry.npmjs.org`

**Comment by Untanky** [comment]
It seems the token is not set correctly.

Here is my config: 
 ```yaml
name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@Untanky'
        always-auth: true
    - run: npm install
    - run: echo $NODE_AUTH_TOKEN
    - run: echo $NODE_AUTH_TOKEN & npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

When trying to log the tokens (which is obviously not possible in plain text), I noticed that the token is not set correctly for the publish step:

Log from echo step:
```
Run echo $NODE_AUTH_TOKEN
  echo $NODE_AUTH_TOKEN
  shell: /bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
XXXXX-XXXXX-XXXXX-XXXXX
```

Log from publish stop:
```
Run echo $NODE_AUTH_TOKEN & npm publish
  echo $NODE_AUTH_TOKEN & npm publish
  shell: /bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***
***
```

As you can see, the token seems to not be set correctly. Can anyone else confirm this as well?
