### ISSUE TITLE
Reduce latency when new node versions are released

### ISSUE THREAD

**Issue by kenhuang** [actions/setup-node#160]
Hi there:

Thanks for this library. Just found that the ` node-version` option is not downloading the latest node release.

v10.21.0 release notes:
https://nodejs.org/en/blog/vulnerability/june-2020-security-releases/

Our setup:
```
- uses: actions/setup-node@v1
  with:
    node-version: 10.x
    registry-url: "https://registry.npmjs.org"
```

Logs:
```
Run actions/setup-node@v1
/usr/bin/docker exec  be3164773b20b9e565b79dfa087a0d06395e9681e0de57453920d34a25c07234 sh -c "cat /etc/*release | grep ^ID"
/__t/node/10.20.1/x64/bin/node --version
v10.20.1
/__t/node/10.20.1/x64/bin/npm --version
6.14.4
```

Update:
seems related to this change: https://github.com/actions/setup-node/pull/147

Regards
Ken
