### ISSUE TITLE
An action could not be found at the URI

### ISSUE THREAD

**Issue by moltar** [actions/setup-node#172]
```yml
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.18

```

Results in:

```
Download action repository 'actions/setup-node@v2'
##[error]An action could not be found at the URI 'https://api.github.com/repos/actions/setup-node/tarball/v2'
```
