### ISSUE TITLE
Can't fetch private dependency from github registry

### ISSUE THREAD

**Issue by alex-trofimov** [actions/setup-node#188]
Hi!
I have a dependency in my project that looks like this:
`"react-native-background-geolocation-android": "git+https://github.com/transistorsoft/react-native-background-geolocation-android.git#3.8.0",`

And this basic workflow:
```
name: Test

on:
  release:
    types:
      - created

jobs:
  release_codepush_update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        always-auth: true
        registry-url: https://npm.pkg.github.com
        scope: '@transistorsoft'

    - name: Install dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
```
Which throws this error on `npm install` step:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/transistorsoft/react-native-background-geolocation-android.git
npm ERR! 
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/transistorsoft/react-native-background-geolocation-android.git/' not found
npm ERR! 
npm ERR! exited with error code: 128
```

(My project isn't a part of the `transistorsoft` scope if that matters)

The access token is correct, I can fetch the dependency repo in the same workflow using `curl`.

Another part of the project's workflow is run on Appcenter and the same task of authentication is resolved by this bash script:
```
echo "always-auth=true
//npm.pkg.github.com/:_authToken=${GITHUB_ACCESS_TOKEN}" >> .npmrc
```
I tried replacing the content of .npmrc generated by this action with content generated by the said script but for some reason, I can't make it to work.

Any ideas what I'm doing wrong?
