### ISSUE TITLE
Unable to install private package from Github registry on Windows platform

### ISSUE THREAD

**Issue by Janealter** [actions/setup-node#193]
On Windows platfrom `yarn install` or `npm install` returns error `401 unauthorized` even though I have set the correct parameters:
```yaml
- name: Use Node.js 12.13.0
  uses: actions/setup-node@v1
  with:
    node-version: 12.13.0
    registry-url: https://npm.pkg.github.com
    scope: my_scope
- name: Install dependencies
  run: yarn install # or 'npm install', whatever
  env:
    NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
```

Early installations were successful. I can't determine the version of the package from which the installation broke down. On Linux platform installation works fine.

I found workaround for this issue:
```yaml
- name: Install dependencies
  run: yarn install
  env:
    # Specify custom .npmrc because actions/setup-node@v1 doesn't
    # correctly set registry-url and token at Windows platform
    NPM_CONFIG_USERCONFIG: .npmrc.ci
    NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
```
Custom .npmrc (`.npmrc.ci`) contains:
```
@my_scope:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
```

**Comment by Sh4bbY** [comment]
I had the same issue with ubuntu-latest, so I doubt this issue is related to Windows only.
The workaround form @Janealter worked for me. Thanks!

**Comment by xt0rted** [comment]
I get the same error on ubuntu. I'm not sure if it's the same issue but this is the config that ended up working for me on both ubuntu and windows:

```yaml
- name: Setup Node
  uses: actions/setup-node@v2.1.2
  with:
    node-version: ${{ env.NODE_VERSION }}
    registry-url: "https://npm.pkg.github.com"
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}

- name: Yarn install
  run: yarn install
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
```

**Comment by A-Tokyo** [comment]
The trick is adding the NODE_AUTH_TOKEN env variable to the yarn install step

```
- name: Yarn install
  run: yarn install
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
```
