### ISSUE TITLE
Jest is not using correct configured node version

### ISSUE THREAD

**Issue by Judahh** [actions/setup-node#204]
Test workflow is failing with Jest errors saying it's using v12.19.0, but I'm using v14
# Github CI run #
yarn run v1.22.10
$ jest -i -c integration.config.json --passWithNoTests  --ci --verbose --forceExit --detectOpenHandles
ts-jest[config] (WARN) There is a mismatch between your NodeJs version v12.19.0 and your TypeScript target es2020. This might lead to some unexpected errors when running tests with `ts-jest`. To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

# Workflow #
````
name: Test
on:
  pull_request:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Checkout
        uses: actions/checkout@main
      - name: Install
        uses: borales/actions-yarn@master
        with:
          cmd: install # will run `yarn install` command
      - name: Build
        uses: borales/actions-yarn@master
        with:
          cmd: build # will run `yarn build` command
      - name: Test
        uses: borales/actions-yarn@master
        with:
          cmd: test # will run `yarn test` command
      - name: Test Integration
        uses: borales/actions-yarn@master
        with:
          cmd: integration # will run `yarn integration` command
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRES_USER: "postgres"
          MONGO_HOST: mongo
          MONGO_PORT: ${{ job.services.mongo.ports[27017] }}
````
