### ISSUE TITLE
Support for LTS version

### ISSUE THREAD

**Issue by hckhanh** [actions/setup-node#208]
For now, I realized that the LTS version on https://nodejs.org/en/ is `14.15.0`
But I always receive the version v12.19.0 on every build. Even though I removed `node-version` param from `actions/setup-node` step:

```yml
jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          check-latest: true
```

So I think that it should have some kind of `lts` version to indicate which version is currently the LTS version.
