### ISSUE TITLE
/usr/bin/env: 'node': No such file or directory

### ISSUE THREAD

**Issue by jimrazmus** [actions/setup-node#224]
Using 'actions/setup-node@v1' in a workflow step makes node available in subsequent steps. Updating to 'actions/setup-node@v2.1.4' makes subsequent steps fail with "/usr/bin/env: 'node': No such file or directory"

**Comment by maxim-lobanov** [comment]
Could you please provide repro steps for this issue?

**Comment by jimrazmus** [comment]
This is the workflow in question:

```
name: Lint Terraform

on:
  push:

jobs:
  lint-terraform:
    runs-on: self-hosted
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
      - name: Lint Terraform
        run: terraform fmt -check -recursive -diff
```

Everything works with v1 of setup-node. Updating to v2.1.4 exhibits the error.
