### ISSUE TITLE
Error publishing to GHPR

### ISSUE THREAD

**Issue by jasonkarns** [actions/setup-node#234]
```yml
  github-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Almost verbatim from the readme for publishing to GHPR. Took out the node-version (which is documented as optional) because any is fine. Took out the npm install step because we have no deps, so there's nothing to install. Added --ignore-scripts to eliminate possibility of malicious scripts in prepack, etc.

Example failed run: https://github.com/bats-core/bats-core/runs/1846241181

Error message:

```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/bats - Not found
npm ERR! 404 
npm ERR! 404  'bats@1.3.0-alpha' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-06T20_19_12_105Z-debug.log
```
