### ISSUE TITLE
Ignore the gpr registry-url setting

### ISSUE THREAD

**Issue by keyiis** [actions/setup-node#236]
I want publish my package to gpr，but still publish to npmjs registry,below is my config
```
name: Node.js Package

on:
  release:
    types: [created]

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
error log
```
npm notice 
npm notice 📦  node-multi@0.1.9
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE        
npm notice 7.0kB  src/gulpfile.js
npm notice 0      index.js       
npm notice 919B   bin/ops.js     
npm notice 1.5kB  package.json   
npm notice 105B   README.md      
npm notice === Tarball Details === 
npm notice name:          node-multi                              
npm notice version:       0.1.9                                   
npm notice package size:  7.7 kB                                  
npm notice unpacked size: 20.9 kB                                 
npm notice shasum:        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
npm notice integrity:     sha512-eMKt/e8omh0lC[...]xxxxxxxxxxxxxx
npm notice total files:   6                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/node-multi - Not found
npm ERR! 404 
npm ERR! 404  'node-multi@0.1.9' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-19T01_30_47_698Z-debug.log
Error: Process completed with exit code 1.
```
