### ISSUE TITLE
npmjs:You cannot publish over the previously published versions

### ISSUE THREAD

**Issue by keyiis** [actions/setup-node#237]
I used github action publish to npmjs,package already published,but display error,It looks run 2 times
**npm-publish.yml**
```
name: Node.js Package

on:
  release:
    types: [created]

jobs:

  publish-npm:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

```
error log
![image](https://user-images.githubusercontent.com/7766085/108450309-f32b4d80-729f-11eb-85f8-b08b06edf199.png)

```
> npm publish

npm notice 
npm notice 📦  node-multi@0.2.0
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE        
npm notice 7.0kB  src/gulpfile.js
npm notice 0      index.js       
npm notice 919B   bin/ops.js     
npm notice 1.3kB  package.json   
npm notice 105B   README.md      
npm notice === Tarball Details === 
npm notice name:          node-multi                              
npm notice version:       0.2.0                                   
npm notice package size:  7.6 kB                                  
npm notice unpacked size: 20.7 kB                                 
npm notice shasum:        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
npm notice integrity:     sha512-XsZdw9VfQ0sAD[...]xxxxxxxxxx
npm notice total files:   6                                       
npm notice 
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/node-multi - You cannot publish over the previously published versions: 0.2.0.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-19T02_40_05_360Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-multi@0.2.0 publish: `npm publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-multi@0.2.0 publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-19T02_40_05_390Z-debug.log
Error: Process completed with exit code 1.
```
but already published to npm registry
![image](https://user-images.githubusercontent.com/7766085/108450408-2241bf00-72a0-11eb-9464-716497748162.png)

**Comment by bryanmacfarlane** [comment]
The setup-node step (this action where you're logging the issue) succeeded - see the summary.   The error looks correct and it's coming from the running the command line npm publish

```yaml
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
```

So this seems to be external to npm and how it works.

Hope that helps.  We can reactivate if you believe it's an issue with this actions and setuo-node step.
