### ISSUE TITLE
desired version is being ignored

### ISSUE THREAD

**Issue by zilahir** [actions/setup-node#240]
Hey,

I am tryiing to use a specific version of node, which is exactly what this package is used for. 

```
steps:
      - uses: actions/setup-node@v2
        with:
            node-version: '12.8.1'
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
```

but then, still getting the error: 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'teleprompter@2.1.0',
npm WARN EBADENGINE   required: { node: '>=12 < 15' },
npm WARN EBADENGINE   current: { node: 'v15.11.0', npm: '7.6.0' }
npm WARN EBADENGINE }
```

so it seems like, the desired version is getting ignored completely. is this a bug, or am i missing something?

[workflow](https://github.com/zilahir/teleprompter/blob/master/.github/workflows/.release.yml)
