### ISSUE TITLE
registry-url ignored completely

### ISSUE THREAD

**Issue by jektvik** [actions/setup-node#244]
Have a setup like this:

```
name: Node.js Package

on:
  push:
    branches:
    - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
And the docs (https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages) say that this should publish to the provided registry-url i.e. to github.
But instead the job tries pushing to npm and my log fails saying that:
```
Not Found - PUT https://registry.npmjs.org/my-package-name - Not found
```
It's my first shot at github actions so not sure if i'm missing something or whether the setup-node action is messed up and doesn't create the npmrc file properly ?

**Comment by joebowbeer** [comment]
Please provide package.json and .npmrc file if it exists.

In particular, what are the values of the following in package.json?
* name
* publishConfig
* repository

publishConfig will override.

**Comment by jektvik-si** [comment]
On that setup there was no entry for  wither
- publishConfig
- repository
in package.json

the name was unscoped so simply
name: "my-package-name"

**Comment by rafifos** [comment]
Providing additional context:

```
  Release:
    runs-on: ubuntu-latest
    needs: Tests
    if: | # Only runs if the current branch is `master`.
      contains('
        refs/heads/master
      ', github.ref)

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: ${{ secrets.NPM_REGISTRY }}

      - name: Install dependencies
        run: |
          yarn --pure-lockfile --non-interactive --no-progress

      - name: Restoring Next.js build cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: yarn build

      - name: Run semantic-release
        run: yarn semantic-release
```

`NPM_REGISTRY` contains both the registry url and npm token (like in `.npmrc`, i've ommited the token for obvious reasons)

`//registry.npmjs.org/:_authToken=${NPM_TOKEN}`

And finally, this is the `package.json`:

```
{
  "private": true,
  "name": "project name",
  "version": "1.0.0",
  "publishConfig": {
    "access": "restricted"
  },
  "scripts": {
    "semantic-release": "semantic-release"
  },
  "engines": {
    "node": ">=14"
  },
  "dependencies": {
    "private package only published on npm": "1.0.2"
  }
}
```
