### ISSUE TITLE
Docs on use of matrix.node_version don't match actual output

### ISSUE THREAD

**Issue by humphd** [actions/setup-node#245]
In the docs it recommends using the following format to display a node version in the `name`:

```
strategy:
    matrix:
      node: [ '12', '14' ]
    name: Node ${{ matrix.node }} sample
```

or 

```
  strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 10
          - 12
          - 14
        architecture:
          - x64
        # an extra windows-x86 run:
        include:
          - os: windows-2016
            node_version: 12
            architecture: x86
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
```

When I do this with v2.1.5, my names don't include node version info:

![Screen Shot 2021-03-20 at 11 45 32 AM](https://user-images.githubusercontent.com/427398/111875765-d43cdb80-8971-11eb-9848-a91a8eecaa3a.png)

Possible I'm doing it wrong, but following the README doesn't seem to do what it claims.
