### ISSUE TITLE
.npmrc is not created

### ISSUE THREAD

**Issue by adamhenson** [actions/setup-node#249]
# Expected

When `registry-url` input is set with `env.NODE_AUTH_TOKEN` an .npmrc file should be created in project root.

# Actual

When `registry-url` input is set with `env.NODE_AUTH_TOKEN` an .npmrc file is not created.

# Reproduction

*.github/workflows/publish.yml*

```yaml
name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@foo-software'
      - name: Publish Packages
        run: |
          cat .npmrc
```

*package.json*

```yaml
{
  "name": "root",
  "private": true,
  "keywords": [
    ...
  ],
  "scripts": {
    ...
  },
  "husky": {
    ...
  },
  "lint-staged": {
    ...
  },
  "devDependencies": {
    ...
  }
}
```

Note: My project is a Lerna based monorepo, so the above package.json has minimal fields. Perhaps, this functionality requires certain fields / values, but I'm not sure why and what those fields would be.

GitHub Action output and linked [here](https://github.com/foo-software/foo-react-charts/runs/2242526422?check_suite_focus=true).

<img width="501" alt="Screen Shot 2021-03-31 at 11 03 29 PM" src="https://user-images.githubusercontent.com/747743/113237758-6fd52280-9275-11eb-8566-bfcc33dfd4a9.png">

**Comment by adamhenson** [comment]
For anyone who's come across this, my workaround is below, but it feels like a hack since this functionality supposedly exists in `actions/setup-node`.

```diff
      - name: Publish Packages
        run: |
+         echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          cat .npmrc

**Comment by adifelice-godaddy** [comment]
I'm not sure `.npmrc` is created on repo dir, why don't you check the variable `NPM_CONFIG_USERCONFIG`:
```diff
      - name: Publish Packages
        run: |
-         cat .npmrc
+         cat $NPM_CONFIG_USERCONFIG
```

**Comment by adamhenson** [comment]
Thanks @adifelice-godaddy - interesting. Why would it create it anywhere but the repo directory... would you know? The output strangely the below:

```
/home/runner/work/_temp/.npmrc
```

Do you have a recommendation of how to make this be added to the root directory? If it's more than setting an environment variable, then I'll probably just keep [my hack](https://github.com/actions/setup-node/issues/249#issuecomment-811608662). As in, I don't want to write a line that runs a `mv` command, because that would be more effort and add more mystery to the code (anyone reading would wonder why I have this `mv` command. My hack would be more explicit).

**Comment by adamhenson** [comment]
I tried this:

```
mv $NPM_CONFIG_USERCONFIG ${{ github.GITHUB_WORKSPACE }}/.npmrc
```

But, there's a file permission error which makes sense, but beyond my understanding.

```
Run mv $NPM_CONFIG_USERCONFIG /.npmrc
mv: cannot move '/home/runner/work/_temp/.npmrc' to '/.npmrc': Permission denied
Error: Process completed with exit code 1.
```

**Comment by cdrini** [comment]
Out of curiosity, why do you need the .npmrc file in the repo? I was having an issue with the auth token not working (resulting in 404 errors, of all things!), and went down the path of trying to modify the npmrc, but it turned out that the npm token I'd generated was no longer valid, because they add 2FA or something, and I had to generate a new token for "Automation" :/ Once I updated the token everything worked without manual npmrc mods.

**Comment by kenniaa** [comment]
> Out of curiosity, why do you need the .npmrc file in the repo?

Sometimes you want to include an `.npmrc` in a docker container as part of the build step.

**Comment by adamhenson** [comment]
In a GitHub Action I am publishing to NPM from CI. This ticket isn't about answering why I'm doing a thing. This ticket was opened because a documented feature of  `action/node_setup` is not working as expected.

**Comment by adifelice-godaddy** [comment]
> Sometimes you want to include an .npmrc in a docker container as part of the build step.
`action/node_setup` allows you to do that, but setup is done globally in container environment. In most cases it will work as expected. It would be helpful to have more details why it's needed locally in repo's directory. Thanks.

**Comment by adamhenson** [comment]
Please stop adding comments that are not helpful in resolving this issue. For now I'm just using [my workaround](https://github.com/actions/setup-node/issues/249#issuecomment-811608662). I'm thinking about closing this since it hasn't gotten attention from actual contributors. I'm simply reporting a feature of this project that is broken.

My use case isn't very relevant, but since people have been inquiring and for context: it is simple and standard - I have a repo that includes the code for packages to be published to NPM. I'm using `actions/setup_node` to setup the Node.js environment which includes NPM and authorizing NPM.

The README for this project states that it can be used for [`configuring authentication for GPR or npm`](https://github.com/actions/setup-node#setup-node).

In the [usage](https://github.com/actions/setup-node#usage) section of the README it provides an example that you might use to setup and environment to publish packages for NPM. See `Publish to npmjs and GPR with npm` example.

This is the example from the README.

```
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '10.x'
    registry-url: <registry url>
- run: yarn install
- run: yarn publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
- uses: actions/setup-node@v2
  with:
    registry-url: 'https://npm.pkg.github.com'
- run: yarn publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And this setup isn't actually working.
