### ISSUE TITLE
Feature Request: Ability to customize heap memory available to node

### ISSUE THREAD

**Issue by probablyup** [actions/setup-node#251]
I'm not sure what the default heap allocation is, but for some larger projects using webpack etc it's insufficient and the heap allocation needs to be increased via something like this:

```bash
export NODE_OPTIONS=--max_old_space_size=4096
```

It would be great if this could be done in the node setup action via some clean API :)

**Comment by maxim-lobanov** [comment]
Hello @probablyup , I am not sure that we should build-in this functionality to setup-node action. It can be achieved easily with the following  code snippet as an example:
```yml
steps:
- uses: actions/setup-node@v2.1.5
  with:
    node-version: 14.x
- run: npm install
- run: npm run start
  env:
    NODE_OPTIONS: --max_old_space_size=4096
```
Or you can even specify env variable on job level if it should be applied to all steps. See [documentation](https://docs.github.com/en/actions/reference/environment-variables) for more details
