### ISSUE TITLE
Support for npm audit?

### ISSUE THREAD

**Issue by cujarrett** [actions/setup-node#259]
## What

I don't seem to have success with `npm audit`, is that in scope for this project?

Thanks!

**Comment by iamjoeker** [comment]
Working great for me. Here is the job config I use for running yarn audit. 

```yaml
  audit_node_deps:
    name: Audit Node Deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Audit Deps
        run: yarn audit
```
