### ISSUE TITLE
14.x and 14 both points to 14.16.1

### ISSUE THREAD

**Issue by chenrui333** [actions/setup-node#264]
👋   I am trying to use latest node 14.17.0, but I realize with 

```
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
```

I am using `14.16.1` unless I specify exactly `node-version: "14.17.0"`.

Thanks!

**Comment by maxim-lobanov** [comment]
Could you please try
```yml
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    check-latest: true
```

See readme for more details
