### ISSUE TITLE
Private registry support does not work with npm version 7

### ISSUE THREAD

**Issue by Avaq** [actions/setup-node#265]
I'm running into the issue described here: https://github.com/npm/cli/issues/2508. This issue was closed by mistake (https://github.com/npm/cli/issues/2508#issuecomment-839671711), but it seems to be implied that it won't be fixed, and that something needs to change on `setup-node`'s end to get things working again.

From my basic understanding, it's related to the way that setup-node configures the multiple registries:

https://github.com/actions/setup-node/blob/5c355be17065acf11598c7a9bb47112fbcf2bbdc/src/authutil.ts#L47-L55

#### To Reproduce

1. Make sure your `package-lock.json` contains a private package that can only be accessed with your `NPM_TOKEN`. It's important to have a **`package-lock.json`** file as well as your regular `package.json`, because the issue only occurs when there is also a package lock, as hinted at by this comment: https://github.com/npm/cli/issues/2508#issuecomment-839843235
2. Use a workflow like:
    ```yaml
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x' # Node version is important; It ensures that npm v7 is installed
        registry-url: 'https://registry.npmjs.org'
    - run: npm install --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    ```
