### ISSUE TITLE
How to get a node image with full internationalization support? (--with-intl=full-icu)

### ISSUE THREAD

**Issue by latobibor** [actions/setup-node#267]
In our codebase there is some Date internationalization code. We use `Date.toLocaleString` method. The test written for this use case broke because of `toLocaleString` fell back to US localization instead of the provided one (it is working properly locally and in production). 

I think the issue is that the `node.js` provided by this action is not the **default** one but one with less or no `Intl` support:
https://nodejs.org/api/intl.html

Is there a parameter I can pass to obtain the **default** `node.js` image?

Relevant part of our `.github` file:
```yaml
  test-source:
    name: Test Source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
```

Thanks in advance!
