### ISSUE TITLE
Unable to publish Github package

### ISSUE THREAD

**Issue by Zenoo** [actions/setup-node#269]
I am trying to setup a workflow that publishes a Github package, but I can't seem to make it work.  

Here is a simplified workflow I created to try it: 

https://github.com/Zenoo/slick-loader/blob/master/.github/workflows/npm-publish.yml
```yml
name: Node.js Package

on:
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

But the process always fails:

```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/slick-loader - Not found
npm ERR! 404 
npm ERR! 404  'slick-loader@1.1.35' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-16T08_47_48_768Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by anantoghosh** [comment]
Publishing to github requires some configurations:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#publishing-a-package-using-a-local-npmrc-file

1. Your package name should have the scope with your github username `@<username>/<packagename>`.
2. Change the `publish` command for github to ` npm publish --@<username>:registry=https://npm.pkg.github.com/`.
3. If you are releasing to npm registry too, change that `npm publish` to `npm publish --access public`.

All this confusion arises from the expectation that the node publish workflow will just work right out of the box 😕 .

**Comment by Zenoo** [comment]
@anantoghosh What can I do if my package doesn't have the scope with my username?  
The package has already been published on NPM for a long time, I can't just rename it.  
Same for your second and third point: My package name doesn't contain a scope ^^'

**Comment by anantoghosh** [comment]
Even though there are some comments saying that this should be possible https://github.com/actions/setup-node/issues/73#issuecomment-642457192 https://github.com/actions/setup-node/issues/243#issuecomment-802086947, all possible combinations of configurations I tried did not solve the issue.

As a hack I though I could rename the package name to add the scope in the gpr action but then I start getting this problem https://github.com/actions/setup-node/issues/215, using npm config (because I was installing a global package for editing the json and needed to set npm prefix) causes the `/` after scope to get encoded into `%2f` which I was unable to fix with multiple different configurations.
I searched briefly through github to find packages other packages which tried this and all but two failed in publishing to gpr.
https://github.com/bats-core/bats-core/blob/eac1e9d047b2b8137d85307fc94439c90bdc25ae/.github/workflows/release.yml#L51
They are using `npm init --scope username` to rename the package and this works for me too, gpr publish works, but using npm init in my project adds dependencies into the package.json file which I don't need so this was a no go too.

https://github.com/hujiulong/vue-3d-model/blob/master/scripts/gpr-setup.js
They are using a node script to rename, this is what I went with too (modified for type: "module"):
```js
// gpr-hack.js
import { writeFileSync, readFileSync } from "fs";

const file = readFileSync("./package.json", {
  encoding: "utf-8",
});

const json = JSON.parse(file);

json.name = "@name/pkgname";

writeFileSync("./package.json", JSON.stringify(json, undefined, 2));

```
Final solution looks like this:
```yaml
publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@name"
      - run: node gpr-hack.js
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

It took me quite some time to get this to work mainly due to https://github.com/actions/setup-node/issues/215, this may also cause trouble if `npm config` were to be used eg: for installing global packages.

note: `yarn` may behave differently

**Comment by Zenoo** [comment]
Hmm, I tried your method on this repo:
[HemantNegi/jquery.sumoselect](https://github.com/HemantNegi/jquery.sumoselect)

But it's sending me 403 errors:
https://github.com/HemantNegi/jquery.sumoselect/runs/2924759196?check_suite_focus=true#step:3:10
```
👩‍🏭 Creating new GitHub release for tag v3.3.14...
⚠️ GitHub release failed with status: 403, retrying...
```

**Comment by Zenoo** [comment]
I tried your solution but I'm getting the same kind of error in the run:
https://github.com/HemantNegi/jquery.sumoselect/runs/2925738111#step:12:58

```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@HemantNegi%2fjquery.sumoselect - Not found
npm ERR! 404 
npm ERR! 404  '@HemantNegi/jquery.sumoselect@3.3.20' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-27T15_20_08_621Z-debug.log
Error: Process completed with exit code 1.
```

Here is the workflow:
https://github.com/HemantNegi/jquery.sumoselect/blob/master/.github/workflows/github-release-publish.yml
```yml
name: GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            See [CHANGELOG.md](./CHANGELOG.md) for changes.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@HemantNegi"
      - run: node gpr-hack.js
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

And here's the GPR hack:  
https://github.com/HemantNegi/jquery.sumoselect/blob/master/gpr-hack.js
```js
const fs = require('fs');
const path = require('path');
const pkg = require('./package.json');

pkg.name = '@HemantNegi/jquery.sumoselect';

// Update package.json with the udpated name
fs.writeFileSync(
  path.join(__dirname, './package.json'),
  JSON.stringify(pkg, null, 2),
);
```
