### ISSUE TITLE
Node 8 installs different versions depending on system

### ISSUE THREAD

**Issue by sergiohgz** [actions/setup-node#27]
When setting up Node with the next strategy matrix and action from `v1` or `master`:

```yaml
strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

# ...

    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        version: ${{ matrix.node_version }}
```

With Node 10 and 12, it works like a charm, installing `10.16.2` and `12.8.0` respectively, using `10` or `'10.x'` and `12` or `'12.x'`, but with Node 8 using `8` or `8.x` it will not install the latest version in Windows. I made a table with the versions installed depending on the base system and the value in the `node_version` array specified:

| System specified | Node specified | Node installed |
| ---------------- | -------------- | -------------- |
| ubuntu-latest    | 8              | 8.16.0         |
| macOS-latest     | 8              | 8.16.0         |
| windows-latest   | 8              | **8.10.0**       |
| ubuntu-latest    | 8.x            | 8.16.0         |
| macOS-latest     | 8.x            | 8.16.0         |
| windows-latest   | 8.x            | **8.10.0**     |
| ubuntu-latest    | 8.16           | 8.16.0         |
| macOS-latest     | 8.16           | 8.16.0         |
| windows-latest   | 8.16           | 8.16.0         |

Windows is installing `8.10` when Ubuntu and MacOS install `8.16`. If we force `8.16` it will install it, but this is not scaling.
