### ISSUE TITLE
Support cache dependencies for cases where package lock files are located in subfolders

### ISSUE THREAD

**Issue by bbugh** [actions/setup-node#275]
Hi! 👋

We have a mixed-language monorepo with nothing in the base folder except some CI info. We need to be able to specify `working-directory` input like other scripts in order to use this fantastic action to build our node subfolders.

Something like:

```yaml
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    working-directory: some-client
```

Thanks!

**Comment by maxim-lobanov** [comment]
Hello @bbugh , I don't think that you need `working-directory` input in setup-node task. This task just installs specified Node.js version and do nothing with working directory.

If your `package.json` / project are located in the separate folder, I think you need to specify `working-directory` for next steps:
```yml
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    
- name: Install dependencies and build project
  working-directory: some-client
  run: |
    npm install
    npm run build
    npm run test
```
