### ISSUE TITLE
Accept a working-directory as an input argument

### ISSUE THREAD

**Issue by Nefcanto** [actions/setup-node#282]
I'm trying to setup node for my GitHub Action. But I'm not working in the default directory.

I clone a repo in `dir_one/rep_one` and then clone another repo in `dir_two/rep_two` and copy a couple of files from the first repo to the second repo.

Then I want to setup Node and `npm install` on the second repo. 

`working-directory` doesn't work with `uses` and I also tried to `- run: cd dir_two/repo_two`, but again build fails because it's running in its folder.

I receive this error:

> Error: Dependencies lock file is not found in /home/runner/work/Site/Site. Supported file patterns: package-lock.json,yarn.lock

Please create an input argument to accept path where node should search for `package.json` file.

**Comment by karlosos** [comment]
I have a similar problem. My monorepo has the following structure:

```
my-repo/
├─ frontend/
│  ├─ package.json
│  ├─ package-lock.json
│  ├─ src
├─ backend/
```

Is there a possibility of using `actions/setup-node@v2` inside `./frontend` directory?

I've tried following workflow:

```
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
```

With similar error:

> Error: Dependencies lock file is not found in /home/runner/work/django_chatroom/django_chatroom. Supported file patterns: package-lock.json,yarn.lock

![image](https://user-images.githubusercontent.com/3882385/124731395-788f6180-df12-11eb-9458-76442b7a560b.png)
