### ISSUE TITLE
Support for npm-shrinkwrap.json

### ISSUE THREAD

**Issue by edukisto** [actions/setup-node#302]
Is it possible to use not only `package-lock.json` or `yarn.lock` but also `npm-shrinkwrap.json` when caching package dependencies?

**Comment by AlenaSviridenko** [comment]
Hi @edukisto, we have an [ADR to support monorepos and projects with complex structure](https://github.com/actions/setup-node/pull/299/) that will also make it possible to specify path to `npm-shrinkwrap.json` so it can be used as a dependencies source. 
It will be implemented in the upcoming couple of months.

**Comment by edukisto** [comment]
That’s great! We are looking forward to it! Thank you, @AlenaSviridenko!

**Comment by dmitry-shibanov** [comment]
Hello @edukisto. The [pull request](https://github.com/actions/setup-node/pull/305) with adding support for monorepos and projects with complex structure was merged. You can specify npm-shrinkwrap.json with this code snippet.
```
- uses: actions/setup-node@v2
  with:
    node-version: '14'
    cache: 'npm'
    cache-dependency-path: npm-shrinkwrap.json
```

For now I'm closing the issue. If you have any concerns feel free to ping me in the thread.
