### ISSUE TITLE
Support `cache-hit` state

### ISSUE THREAD

**Issue by pacexy** [actions/setup-node#316]
I wrote a workflow like follow, but I found nothing happened. Is that wrong or just unsupported?

```yml
- uses: actions/setup-node@v2
  id: cache
  with:
    node-version: '14'
    cache: yarn
- run: yarn install --frozen-lockfile
  if: steps.cache.outputs.cache-hit != 'true'
```
