### ISSUE TITLE
Support .nvmrc

### ISSUE THREAD

**Issue by dougmoscrop** [actions/setup-node#32]
It would be nice if `setup-node` understood an .nvmrc file (even if it does not use nvm under the hood, the idea is the `node-version` is just the contents of the file).

If GitHub Actions as a whole could read the contents of a file as part of an expression, I could do something like

```yml
uses: setup-node@v1
with:
  node-version: {{ contents(.nvmrc) }}
```

But I don't know where to log that type of feature request!

Perhaps '.nvmrc' could be used as a special placeholder, so that:

```yml
uses: setup-node@v1
with:
  node-version: '.nvmrc'
```

Instructs this action to read the contents and treat the contents as the desired version?

**Comment by damccorm** [comment]
> If GitHub Actions as a whole could read the contents of a file as part of an expression

I think its probably unlikely we're going to expand our expression parsing to that degree - in general computation isn't supposed to happen there and we want to discourage moving in that direction, and keep that more towards just reading existing variables. Note that you could do something like the following here:

```
run: nvmrc=$(cat .nvmrc)

uses: setup-node@v1
with:
  node-version: $nvmrc
```

> Perhaps '.nvmrc' could be used as a special placeholder

I'm interested in this option. We're looking at doing something similar in setup-dotnet: https://github.com/actions/setup-dotnet/pull/15. I see a couple options here:

1) If there's a `.nvmrc` at the root of the repo (or the current working directory) and no `node-version` specified, automatically use the version in the `.nvmrc` file. Maybe have a variable that allows you to turn this on or off.
2) Allow `node-version` to be a path to a `.nvmrc` file.
3)  Don't allow this option.

@chrispat, any thoughts on this one? I think maybe we should establish a pattern here and with setup-dotnet for similar requests (I'm sure node and dotnet aren't the only tools with config files that can specify versions).

**Comment by dougmoscrop** [comment]
Thanks for the top about just using an output, that makes sense and is good enough for me, though the simpler developer experience would be nice;  maybe it's just worth a `setup-npm` action?

**Comment by travi** [comment]
> I see a couple options here:
>
> 1. If there's a .nvmrc at the root of the repo (or the current working directory) and no node-version specified, automatically use the version in the .nvmrc file. Maybe have a variable that allows you to turn this on or off.
> 1. Allow node-version to be a path to a .nvmrc file.
> 1. Don't allow this option.

if it's helpful in making the decision, travis-ci has the behavior of 1. and is very often sufficient for my projects. it also has the benefit of removing the need to keep the versions in sync for what is intended for use with local development and the version intended for CI since there is a single source of truth rather than distributing across multiple files.

**Comment by peaceiris** [comment]
The following also works well.

```yaml
    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
```

- [Set an output parameter: set-output | Development tools for GitHub Actions - GitHub Help](https://help.github.com/en/articles/development-tools-for-github-actions#set-an-output-parameter-set-output)
- [My workflow test.yml | peaceiris/actions-hugo](https://github.com/peaceiris/actions-hugo/blob/master/.github/workflows/test.yml)

**Comment by chingc** [comment]
Has there been any progress towards natively supporting .nvmrc instead of having to use `set-output`?

**Comment by thejoebourneidentity** [comment]
We got the following issue in the virtual environments repo: https://github.com/actions/virtual-environments/issues/4

What's the latest on the plans to support .nvmrc? Is it on the roadmap?

**Comment by chrispat** [comment]
I think the action could be updated to support .nvmrc as the default if no version is specified in the `node-version` parameter.  At the moment we do not have anyone we an assign to do that work in the action but it does feel like something we could code review as a community contribution.

**Comment by thejoebourneidentity** [comment]
I chatted with @bryanmacfarlane about this. I think for now we're going to close this issue, and instead move forward with the recommendation to just add nvm to the image as is requested in the virtual environments repo. https://github.com/actions/virtual-environments/issues/4

**Comment by sarink** [comment]
`cat`ing an nvmrc file and using that version should be pretty simple, right?

If you're not already using nvm under the hood to find which node version to install... Why add another dependency to the mix?

**Comment by bryanmacfarlane** [comment]
Yeah, pretty straight forward and we haven't closed so we'll get to it at some point.  Note that in your example above you should add `shell: bash` to your first run step if you want to ensure it works on windows as well

**Comment by schoenwaldnils** [comment]
Wait, this is not supported yet? Well, good to know now 🤷🏻‍♂️
I really hope this will be getting implemented soon.

**Comment by peaceiris** [comment]
[Update/Add nvm · Issue #4 · actions/virtual-environments](https://github.com/actions/virtual-environments/issues/4#event-3259097679) was closed and `nvm` will be available on Actions runners 🚀

**Comment by chingc** [comment]
> [Update/Add nvm · Issue #4 · actions/virtual-environments](https://github.com/actions/virtual-environments/issues/4#event-3259097679) was closed and `nvm` will be available on Actions runners 🚀

I'm so happy about this.

**Comment by vvo** [comment]
Awesome! How can we know once it's deployed and we can remove custom actions we had to support nvm? Thanks 🙏

**Comment by thejoebourneidentity** [comment]
Sorry for the late reply here, you can always follow along over at https://github.com/actions/virtual-environments

For instance, nvm was added some time back to the Ubuntu images :)
https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

I think we can close this issue @bryanmacfarlane

**Comment by chrispat** [comment]
I don't think having NVM on the images is the same thing given NVM does not support Windows.  I think the best option would be to have this actions support the .nvmrc.  If someone would like to raise a PR for it we could likely accept it.

**Comment by sangeeth96** [comment]
@chrispat can I pick this up? Would love to know if you have any thoughts in mind or guidance w.r.t to this.

**Comment by chrispat** [comment]
@sangeeth96 feel free to open a PR.  My general expectation would be that if `node-version` is not supplied the action would look for a .nvmrc in the root of the workspace and attempt to use the value from that.

**Comment by airtonix** [comment]
> I don't think having NVM on the images is the same thing given NVM does not support Windows. I think the best option would be to have this actions support the .nvmrc. If someone would like to raise a PR for it we could likely accept it.

On windows you should be using nodist, which then makes this a non issue as nodist doesn't require all the messing about like nvm does.

**Comment by damianobarbati** [comment]
Guys sorry to ask, but... what is the current correct way to let setup-node use the .nvmrc specific node version? 😅
I got lost and I can't find it in the README

**Comment by dessant** [comment]
@damianobarbati, like this:

```yaml
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: 'false'
      - name: Get Node.js version
        id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
```

**Comment by damianobarbati** [comment]
@dessant thanks x1000!

It's so verbose though, is there any intention to make it slimmer with an option in setup-node action?

**Comment by chingc** [comment]
@damianobarbati If you're using GitHub runners, the Linux and macOS machines have had nvm installed by default for quite some time.  You can see a full list of supported software [here](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-software).  I've stopped using setup-node ever since.

**Comment by damianobarbati** [comment]
@chingc are you sure? I read the article and I'm using Ubuntu 20.04 in my actions, but 
```yml
      - name: check
        run: |
          nvm install < .nvmrc
``
results in command not found

**Comment by corpulentcoffee** [comment]
@damianobarbati [For reasons](https://github.com/actions/virtual-environments/issues/4#issuecomment-600025775), `nvm` only works under a login shell (e.g. `shell: bash --login {0}`)... so something like

```yaml
- name: npm test
  shell: bash --login {0}
  run: nvm install && npm ci && npm test
```

... might be what you want. If your `run` script is complex or multiple lines, you might want to pass `bash` other flags for safety too (e.g. `-e`, `-o pipefail`, `-O inherit_errexit`), or move it out to an external script.

Unlike `actions/setup-node`, nvm's changes are only active for the duration of the `run` script, so successive `run`s that need the same Node environment would want to start with `nvm use`.

**Comment by privatenumber** [comment]
Noticed errors weren't being caught when using `shell: bash -l {0}`

To make sure the GitHub Action fails correctly, make sure to use the [`-e` flag](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#:~:text=exit%20immediately%20if%20a%20pipeline%20(see%20pipelines)%2C%20which%20may%20consist%20of%20a%20single%20simple%20command%20(see%20simple%20commands)%2C%20a%20list%20(see%20lists)%2C%20or%20a%20compound%20command%20(see%20compound%20commands)%20returns%20a%20non-zero%20status.) so that bash exists if a command exits with a non-zero status:

```
shell: bash -e -l {0}
```

**Comment by skjnldsv** [comment]
What I recently develpped to use the package.json engines

```yml
jobs:
  build:
    runs-on: ubuntu-latest

    name: node
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v1
        id: package-engines-versions

      - name: Show node version number
        run: echo "Node version is ${{ steps.package-engines-versions.outputs.nodeVersion }}"

      - name: Show npm version number
        run: echo "Npm version is ${{ steps.package-engines-versions.outputs.npmVersion }}"

      - name: Set up node ${{ steps.package-engines-versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.package-engines-versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.package-engines-versions.outputs.npmVersion }}"

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present

      # ... etc
```

**Comment by gordey4doronin** [comment]
>  @peaceiris commented on 9 Oct 2019
>
> The following also works well.
> 
> ```yaml
>     - name: Read .nvmrc
>       run: echo ::set-output name=NVMRC::$(cat .nvmrc)
>       id: nvm
> 
>     - name: Setup node
>       uses: actions/setup-node@v1
>       with:
>         node-version: '${{ steps.nvm.outputs.NVMRC }}'
> ```


Yet another variation. 👇 I guess no real advantages or disadvantages though.

```yaml
    - name: Read .nvmrc
      run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NVMRC }}
```

**Comment by jameswald** [comment]
Is this fixed with https://github.com/actions/setup-node/pull/338?

**Comment by dougmoscrop** [comment]
I declare it fixed!  I didn't say it, I declared it

**Comment by mauriciabad** [comment]
If you got here from googling, let me tell you, that the newest and simplest way of reading the `.nvmrc` file and using it in `actions/setup-node` is with the [node-version-file](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file) option:

```yml
  - name: Setup node
    uses: actions/setup-node@v2
    with:
      node-version-file: '.nvmrc'
```
