### ISSUE TITLE
Performance opportunity for yarn 3 cache

### ISSUE THREAD

**Issue by belgattitude** [actions/setup-node#325]
Thanks for the new cache feature. Much easier.

After few weeks, I realized that while it supports yarn, there's some improvements that can be made.

Yarn 3 (probably yarn 2+ too) manages downloaded archives pretty well (`.yarn/cache/*.zip`) and invalidating on yarn.lock changes does not take that into account and I saw a lot of cache misses.

As an example I converted back to action-cache to illustrate and test.

The P/R is here https://github.com/belgattitude/nextjs-monorepo-example/pull/369.

I'm wondering if a similar approach could be done with setup-node ?

PS: Key points

<details>
  <summary>Example with action cache</summary>

```
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache 
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}       
          key: yarn-cache-folder-os-${{ runner.os }}-node-${{ env.node-version }}-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}      
          restore-keys: |
            yarn-cache-folder-os-${{ runner.os }}-node-${{ env.node-version }}-
            yarn-cache-folder-os-${{ runner.os }}-
```
</details>

<details>
  <summary>Result after a new package was added</summary>

```
yarn install --immutable
➤ YN0000: ┌ Fetch step
  ➤ YN0013: │ 1719 packages were already cached, one had to be fetched (superjson@npm:1.7.5)
➤ YN0000: └ Completed in 1s 124ms

Cache Size: ~127 MB (133261279 B)
Cache saved successfully
Cache saved with key: yarn-cache-folder-os-Linux-node--f118ea4bee07eada9df36ad2e83fd6febcbaf06b5b8962689c7650659e872ad3
```
</details>

I

**Comment by merceyz** [comment]
It can be even more efficient by not including the OS and Node version in the cache key as well - https://github.com/actions/setup-node/pull/272#issuecomment-873564091

**Comment by nickmccurdy** [comment]
This only applies to zero install, right? In that case there probably needs to be a way to detect or toggle it.

**Comment by dmitry-shibanov** [comment]
Hello @belgattitude. Thank you for your feature request. Could you please describe it little bit. Do you want to add restore-keys to the action to take previous cache or you also want to add `.yarn/cache/*.zip` to cached directories ?

**Comment by dmitry-shibanov** [comment]
Hello @belgattitude, just a gentle ping.

**Comment by belgattitude** [comment]
@dmitry-shibanov first of all thanks for considering this issue. I've edited the P/R desc with latest comments from @merceyz 

> Do you want to add restore-keys to the action to take previous cache

Yes that's the idea, that way we take advantage of the built-in yarn 2+/3+ cache management. Yarn will prune old packages and only fetch new ones keeping the packages zipped into `cacheFolder` in sync with package.json (works with workspace/monorepo too).

Note that if multiple actions are run in parallel, only the first one will be able to reserve the cache, others will print a warning after:

```
> Post restore yarn cache
   Unable to reserve cache with key yarn-cache-folder- 
   cb79cb8e7c0fdd859237ac516da53bc2fdafceb3230fd68444aa4f55c9238980, another job may be creating this cache.
```

As far as I tested it does not create problems and can be safely ignored..


> you also want to add .yarn/cache/*.zip to cached directories

Actually this what matters most. AFAIK setup/node try to cache the `node_modules` folder(s). 

I would add this should be the only thing that needs to be cached (but there I'm not 100% sure).

There's some kind of guarantee that yarn cache is portable across os and node versions as @merceyz pointed out, while node_modules might not (native binaries, postinstall tricks). 

As the cache folder is configurable (through [yarnrc.yml](https://yarnpkg.com/configuration/yarnrc#cacheFolder) or `YARN_CACHE_FOLDER` env), a good way to read it

```yaml
      # Get the yarn cache path.
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
```

The restore key could be a constant:

```yaml
      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-
```

Interestingly pnpm has a [benchmark](https://pnpm.io/benchmarks) page with some insights about the different modes (cache+node_modules, cache only)

![image](https://user-images.githubusercontent.com/259798/143036812-efed0f26-8100-49a6-8b61-3db73ae2473e.png)

Looks having both node_modules + yarn cache will be faster (excluding action/cache restore/generate...). I guess even more as yarn won't probably have to re-run the link phase (generally slow with native binaries: esbuild, swc, sharp, prisma...). But with caching node_modules I'm not sure of the portability though (it depends also of setup/node)

I would say a safe way would be to just save 'yarn cache folder' and not node_modules.

Let me know if it answer your questions.

Have a great day


PS: @merceyz thanks for your comment about portability, I was wondering if the newly introduced [supportedtArchitecture](https://yarnpkg.com/configuration/yarnrc#supportedArchitectures) change something ?
