### ISSUE TITLE
Caching packages dependencies in composite actions

### ISSUE THREAD

**Issue by sergei-startsev** [actions/setup-node#329]
Caching packages dependencies doesn't work in [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) today. Action composition allows to reduce duplication in workflows and make maintenance easier, however `setup-node` with `cache` option doesn't support them – cache is always not found.

```yml
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: yarn
```

```
/usr/local/bin/yarn --version
1.22.11
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
yarn cache is not found
```
