### ISSUE TITLE
Error: Cache service responded with 403 when running a job triggered by `deployment_status`

### ISSUE THREAD

**Issue by rgegriff** [actions/setup-node#341]
As the title of the issue says, I am getting an error when trying to cache node modules during a deployment_status job
```
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
      - name: Install node packages
```
