### ISSUE TITLE
Dependencies are still installed after cache flag is true

### ISSUE THREAD

**Issue by gabrielmoncea** [actions/setup-node#349]
**Description:**
Yarn still installs dependencies even though cache flag is true.
Tested on hosted ubuntu-latest env and on self-hosted macOS env.

**Action version:**
Specify the action version
actions/checkout@v2

**Platform:**
- [x] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Tools version:**

yarn v1.22.15

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.
```
name: unit-tests
on:
  workflow_dispatch

jobs:
  test:
    name: Cache deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mobile-react
        uses: actions/checkout@v2

      - name: Set up Node with cache
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install yarn dependencies
        timeout-minutes: 5
        run: yarn install
```

**Expected behavior:**
After cache is applied yarn install should be skipped.

**Actual behavior:**
After cache is applied yarn installs dependencies
<img width="666" alt="Screenshot 2021-10-18 at 17 18 07" src="https://user-images.githubusercontent.com/39256258/137874362-76ed6595-54d8-4242-b11e-583542d2d9a7.png">
.
