### ISSUE TITLE
npm warnings cause the action to fail

### ISSUE THREAD

**Issue by novemberborn** [actions/setup-node#352]
**Description:**
npm, as run within this action, is emitting warnings due to my `.npmrc` file. These then fail the action.

**Action version:**
v2 (not sure how to tell exactly what GHA selected)

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node.js ^16.4

**Repro steps:**  
With https://github.com/avajs/ava/pull/2867 I'm configuring `lockfile-version=3` in my `.npmrc` file. The npm version that is installed through the action does not recognize this option.

See this run: https://github.com/avajs/ava/runs/4055643495?check_suite_focus=true

**Expected behavior:**
The warning is emitted but the action completes successfully.

**Actual behavior:**
The action fails.

**Comment by dmitry-shibanov** [comment]
Hello @novemberborn. Thank you for your report. As you described in `feature request` with adding `npm_version for npm 7 support`, lokfile-version 3 is only supported by npm 8. You're using built-in caching of the action. The Action calls `npm config get cache` to get global cache directory, that is why you get warning and error. As temporary workaround I suggest:
 - remove .npmrc in the time of the building if it's not necessary.
 - remove built-in caching for node and use [actions/cache](https://github.com/actions/cache)
 - You can try to use the action twice
 ```
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Upgrade npm
        run: npm install --global npm@^8.1.2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
 ```
 - Add `--lockfile-version` as configuration option.
