### ISSUE TITLE
Unable to find LTS release 'gallium' for Node version 'lts/gallium'.

### ISSUE THREAD

**Issue by loozhengyuan** [actions/setup-node#355]
**Description:**
Node 16 LTS with codename `lts/gallium` has been released but not supported by the action.

**Action version:**
v2

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

```yaml
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
          cache: "yarn"
```

**Expected behavior:**
To install Node 16 LTS

**Actual behavior:**
```
Attempt to resolve LTS alias from manifest...
Error: Unable to find LTS release 'gallium' for Node version 'lts/gallium'.
```
