### ISSUE TITLE
How to target setup NODE version using environmental variables without hitting runner itself?

### ISSUE THREAD

**Issue by jkabat** [actions/setup-node#356]
**Description:**
Im trying to add Node v17 into the matrix but because of known openssl bug I need to set "--openssl-legacy-provider" in NODE_OPTIONS. Using actions environment variables seems to be affected even runner which is not very recent and fails on unrecognizable option. Is there something I can do about it?

**Action version:**
Latest.

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
```yaml
  - name: Setup NODE
    uses: actions/setup-node@v1
    with:
          node-version: "17"
    env:
          NODE_OPTIONS: "--openssl-legacy-provider"
```

**Expected behavior:**
Step will end up without an error.

**Actual behavior:**
Step fails with:
```
Run actions/setup-node@v2.4.1
/home/runner/runners/2.283.3/externals/node12/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS```

**Comment by mjubilee1** [comment]
@jkabat Any follow up on this issue? I'm also trying to setup Node 17.

**Comment by dmitry-shibanov** [comment]
Hello everyone. You've got an issue, because initially default node.js version is 12 for actions, that is why it does not accept such flag. If you need this options global for all steps, you can add global environment variable after installation of node.js. You can try to use this snippet:
```
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: echo 'NODE_OPTIONS="--openssl-legacy-provider"' >> $GITHUB_ENV
```
Besides, you can use it only for specific steps by this:
```
      - name: Setup NODE
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: node --version
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
``` 
Moreover, the most actions in actions' organisation use node12 as [default one](https://github.com/actions/setup-node/blob/main/action.yml#L36), that is why I think it's better to use `NODE_OPTIONS` for specific steps.

**Comment by jkabat** [comment]
@dmitry-shibanov thanks for the hint.

Resolved using additional step:
```yaml
            - name: Override NODE options for the most recent version
              if: matrix.node-version == '17'
              run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
```

Do not forget to restore original options if you depend on other runner actions (like cache cache POST job).
