### ISSUE TITLE
lts/* is no longer supported

### ISSUE THREAD

**Issue by CharlesStover** [actions/setup-node#389]
**Description:**

I use `lts/*` as the Node version to make sure my CI is always compatible with the latest version of Node, without requiring manual effort to keep it up to date.

```
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          check-latest: true
          node-version: 'lts/*'
```

This worked fine, but very recently, I'm now seeing this error:

```
Unable to find LTS release '*' for Node version 'lts/*'.
```

**Action version:**

v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Yarn 3.1.1

**Repro steps:**  

Just use `node-version` set to `lts/*`, which _used to_ work, but now throws an error.

**Expected behavior:**

It should use the latest LTS version of Node.

**Actual behavior:**

It throws an error.

**EDIT:**

`lts/*`is still in the README as official syntax:

```
nvm lts syntax: lts/erbium, lts/fermium, lts/*
```
