### ISSUE TITLE
node-gyp 3.8.0 and update doesn't work

### ISSUE THREAD

**Issue by augustnmonteiro** [actions/setup-node#405]
**Description:**
Here is my workflow
```
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'

      - name: Configure MSVS
        run: npm config set msvs_version 2017

      - name: setup node-gyp
        run: npm install -g node-gyp@latest

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm make
```

the error: 

```
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
```

current version of node-gyp is 8.4.1
**Action version:**
Specify the action version

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.
