### ISSUE TITLE
Sharing cache between different jobs?

### ISSUE THREAD

**Issue by eegli** [actions/setup-node#409]
**Description:**
Does this action, by default, reuse cache from different jobs? 
The examples show the setup with a single job. I have a setup with multiple jobs that are dependent on each other and would like to reuse `node_modules`.

**Example**
Is this a correct syntax or is there a redundancy in some of the steps? Guessing based on the time each job takes, the caching works, but I am unsure if I'm doing it right.

Here's a simplified example with two jobs:

```yml
jobs:
  setup-node:
    name: Setup node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn

  type-check:
    name: Run type checks
    needs: [setup-node]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn
      - name: Run Typescript checks
        run: yarn type-check
```
Thanks for the help!
