### ISSUE TITLE
Caching npm install

### ISSUE THREAD

**Issue by nathany** [actions/setup-node#41]
Are there plans to add caching for GitHub Actions? For example, in CircleCI we can greatly reduce the number of VM minutes spent with something like this:

```
- save_cache:
    key: v1-npm-dependency-cache-{{ checksum "package-lock.json" }}
    paths:
      - node_modules
```

(and the corresponding `restore_cache`).

I saw a [tools cache](https://github.com/actions/toolkit/tree/master/packages/tool-cache) for caching the Node.js download, but I'm not sure if that should be used for this.
