### ISSUE TITLE
Keep getting yarn cache is not found 

### ISSUE THREAD

**Issue by mmahalwy** [actions/setup-node#410]
**Description:**
Using yarn 1, continue getting `yarn cache is not found ` on PRs that have run multiple times. 
Weirdly, this works on `pull_request` but not on `push` events. 

Push:
```
Run actions/setup-node@v2
Found in cache @ /opt/hostedtoolcache/node/16.13.2/x64
/usr/local/bin/yarn --version
1.22.17
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6

yarn cache is not found
```

Pull request:
```
Run actions/setup-node@v2
Found in cache @ /opt/hostedtoolcache/node/16.13.2/x64
/usr/local/bin/yarn --version
1.22.17
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Received 151904393 of 156098697 (97.3%), 144.9 MBs/sec
Received 156098697 of 156098697 (100.0%), 128.6 MBs/sec
Cache Size: ~149 MB (156098697 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/1233a9f5-f0f9-47e9-aaf5-472904875c75/cache.tzst -P -C /home/runner/work/alchemist/alchemist
Cache restored successfully

Cache restored from key: node-cache-Linux-yarn-c29c2173f71392ee46ad40a81d3756710c14774844267556986d4379721c0e46
```

**Action version:**
@2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
yarn 1

**Repro steps:**  
```yaml
name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
```

**Expected behavior:**
Should cache on both push and pull request events

**Actual behavior:**
Only caches for pull request
