### ISSUE TITLE
System version of node has priority over manually installed version

### ISSUE THREAD

**Issue by emodric** [actions/setup-node#415]
**Description:**
After using `actions/setup-node` to install a specific node version, the system installed one apparently still has priority over manually installed version.

Couple of hours ago, my builds started to fail since one of the build tools uses `/usr/local/bin/node`, which is in version 16.13.2, while the one installed by `setup-node` is located at `/opt/hostedtoolcache/node/14.18.3/x64`

I presume that `setup-node` does not place the version it installed in path correctly, so the build tool finds the system version of node instead the manually installed one.

**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node 14
Yarn 1.22.17

**Repro steps:**  
https://github.com/netgen-layouts/layouts-ezplatform/runs/5110578290?check_suite_focus=true

**Expected behavior:**
I expected for the system to use Node version I installed manually.

**Actual behavior:**
System uses preinstalled node version instead.

**Comment by juliusvdijk** [comment]
[setup-php was updated](https://github.com/shivammathur/setup-php/releases/tag/2.17.0). 
- Updated Node workflows to use 16.x.

I assume that that action is now setting a different version. Running setup-php first and then setup-node actions fixed it for us.

**Comment by emodric** [comment]
@juliusvdijk I will try it and report back! Thanks!

**Comment by striderwhitepderas** [comment]
Had this issue today too, @juliusvdijk solution worked by running setup-php first, then php-node after.

**Comment by jwage** [comment]
I don't know if this is related or not, but my builds started failing today with similar behavior without any changes to my workflow or dependencies.

I install node version 14 but then when I run yarn install, it is finding version 16.

![Screen Shot 2022-02-08 at 11 35 25 AM](https://user-images.githubusercontent.com/97422/153043687-d79af175-b65a-4fd2-b5a5-85fce044ebc5.png)

Changing `setup-php` to run before `setup-node` fixed it for me as well.

![Screen Shot 2022-02-08 at 11 38 35 AM](https://user-images.githubusercontent.com/97422/153044310-e56f4775-637d-4e32-9b57-fb4751300b1c.png)

Hope this helps someone else! Thanks!

**Comment by JamesNock** [comment]
We've also had problems since a few hours ago. Swapping:

```
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl
```

to 

```
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: mbstring, intl

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
```

Seems to have fixed it.
