### ISSUE TITLE
cache-hit returns true but dependencies are missing

### ISSUE THREAD

**Issue by hamzahamidi** [actions/setup-node#417]
**Description:**
From your documentation you listed that you're using [actions/cache](https://github.com/actions/cache) to cache npm packages. Naturally I used `cache-hit`to skip installation of packages if they're already cached. `cache-hit` returns indeed true but I get the `modules not found` error, which means the dependencies are missing.
I have the following workflow:
````
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # install nodejs
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.22.0
          cache: 'npm'
        id: cache-nodemodules

      - if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - run: make check-codeowners
      - run: npm run lint
````

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Expected behavior:**
I expect the packages to be retrieved from cache
**Actual behavior:**
I think the issue may be linked to the path of the cache directory
