### ISSUE TITLE
Support Node.js RC version

### ISSUE THREAD

**Issue by yisibl** [actions/setup-node#454]
I need to verify that an RC version of Node.js resolves a bug, is there a way to specify this version?

For example, I need to test `v12.22.12-rc.0` and other LTS version. https://nodejs.org/download/rc/

My CI config:

```yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14, 16]

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
```

See also: https://github.com/actions/setup-node/pull/360

**Comment by dmitry-shibanov** [comment]
Hello @yisibl. Thank you for your report. The setup-node action does not install release candidate.

**Comment by dominykas** [comment]
There is a PR open that would enable support for the nightlies: https://github.com/actions/setup-node/pull/360

**Comment by yisibl** [comment]
I've changed to [setup-node-nvm](https://github.com/dcodeIO/setup-node-nvm) to install the RC version, but I still want setup-node to support this.

https://github.com/yisibl/svg-sprite/pull/3/commits/48a402fca42a05608a00be8958430f381ef70721

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released and updated the major [tag](https://github.com/actions/setup-node/releases/tag/v3.6.0) with changes to install rc versions. Could you please confirm that everything works as expected?
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.0.0-rc.1’
      - run: npm ci
      - run: npm test
```
