### ISSUE TITLE
Formatting for node-version matrix not working

### ISSUE THREAD

**Issue by sondr3** [actions/setup-node#46]
I just setup GH Actions using the Nodejs recommended workflow and when using the `node-version` matrix it doesn't format the name of the version it's using properly:

![image](https://user-images.githubusercontent.com/2280539/63709105-79470f00-c836-11e9-93a2-a99628662fd5.png)

**Comment by sondr3** [comment]
For what it's worth, here is my `nodejs.yml` file:

```yaml
name: Main

on: [push]

jobs:
  run:
    name: Run

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: install and build
      run: |
        npm ci
        npm run build
      env:
        CI: true
 
    - name: lint
      run: |
        npm run lint
        npm run style
            
    - name: test
      run: npm test
      env:
        CI: true
```
