### ISSUE TITLE
add example for linting with a single node version and testing with a matrix to README

### ISSUE THREAD

**Issue by verhovsky** [actions/setup-node#461]
**Description:**
I have what I think is a very common usecase. I want to `npm test` with all the supported node versions, but I also want to `npm run lint` my code. 

Adding `npm run lint` to the matrix example in the readme causes me to get 3 repeated warnings every time there's a lint warning: one warning from node 12, the same warning from node 14 and one more from running `npm run lint` under node 16. So I would like to do something like

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run lint
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12, 14, 16]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
```

but I'm not sure about how to make this efficient with caching and stuff, ideally this wouldn't cause me to run `npm install` a fourth time.

or I could add `npm run lint` as a step behind an `if matrix.node-version == '16'` but that would be confusing because it would be clearer to have 4 checkmarks (lint, test, test, test) than 3 checkmarks (test, test, test) where one is also linting.

**Justification:**
I think this is a very common usecase and it should be a standard example I could just copy and paste.

**Are you willing to submit a PR?**
not really
