### ISSUE TITLE
[Bug] Using any architecture other than x64 fails to run

### ISSUE THREAD

**Issue by gaby** [actions/setup-node#462]
Here's my yaml file:

```
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  auto-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 14
          - 16
          - 17
        architecture:
          - x64
          - arm64
    steps:
    - run: git config --global core.autocrlf false  # Mainly for Windows
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}

    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm run install
```

Error happens when running `Get npm cache directory` with the following: 

```
Run echo "::set-output name=dir::$(npm config get cache)"
  echo "::set-output name=dir::$(npm config get cache)"
  shell: /usr/bin/bash -e {0}
/opt/hostedtoolcache/node/14.19.1/arm64/bin/node: 1: ELF�8%�@��n@8: not found
check_suite_focus=true#step:5:2): Syntax error: ")" unexpected
```

My understanding is that even though `setup-node` is using an ARM64 release, the runner itself from Github is using a different architecture?

I don't think this is related with `setup-node` but should be documented. The advanced examples make it look as if just adding  `arm64` is going to make your CI run just fine, which is not the case. 

Is there a Github Action solution for this?

**Comment by panticmilos** [comment]
Hi @gaby,

We will investigate this issue further.

**Comment by gaby** [comment]
I'm going to try the pipeline only using `setup-node` without `actions/cache` to see if it makes any difference.

**Comment by gaby** [comment]
@panticmilos It fails the same way: 

Run is here: https://github.com/gaby/uptime-kuma/actions/runs/2169326953

```
Run actions/setup-node@v[2](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:2)
  with:
    node-version: 14
    architecture: arm64
    cache: npm
    always-auth: false
    check-latest: false
    token: ***
Attempting to download 14...
Not found in manifest.  Falling back to download directly from Node
Acquiring 14.19.1 - arm64 from https://nodejs.org/dist/v14.19.1/node-v14.19.1-linux-arm64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/e0747fd9-4[3](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:3)b9-[4](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:4)e8c-862f-f4e31c69da4d -f /home/runner/work/_temp/1bde7748-179c-4bc7-b21c-f2678bc[5](https://github.com/gaby/uptime/runs/6030140105?check_suite_focus=true#step:4:5)acc7
Adding to the cache ...
Done
/opt/hostedtoolcache/node/14.19.1/arm[6](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:6)4/bin/npm config get cache
/opt/hostedtoolcache/node/14.19.1/arm64/bin/node: 1: ELF�[8](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:8)%�@��n@8: not found
/opt/hostedtoolcache/node/14.1[9](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:9).1/arm64/bin/node: 2: Syntax error: ")" unexpected
Error: /opt/hostedtoolcache/node/[14](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:14).[19](https://github.com/gaby/uptime-kuma/runs/6030140105?check_suite_focus=true#step:4:19).1/arm64/bin/node: 1: ELF�8%�@��n@8: not found
/opt/hostedtoolcache/node/14.19.1/arm64/bin/node: 2: Syntax error: ")" unexpected
```


This is my new full yaml:

```
name: Auto Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  auto-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 14
          - 16
          - 17
        architecture:
          - x64
          - arm64 # Running anything other than x64 is not supported yet, since the runner itself uses x64
    steps:
    - run: git config --global core.autocrlf false  # Mainly for Windows
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
        cache: 'npm'
    - run: npm run install
```
