### ISSUE TITLE
Cache issue in pnpm 7

### ISSUE THREAD

**Issue by ai** [actions/setup-node#479]
**Description:**

If we are using `pnpm 7` with `cache: pnpm` in `actions/setup-node@v3` and avoid installing dependencies we will have error:

```
Error: Cache folder path is retrieved for pnpm but doesn't exist on disk: /home/runner/.local/share/pnpm/store/v3
```

**Action version:** 3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

`pnpm 7.0.0`

**Repro steps:**  

```yaml
jobs:
  repro:
    - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: caniuse-lite
          cache: pnpm
```

[Example](https://github.com/browserslist/caniuse-lite/actions/runs/2253352361)

**Expected behavior:**

No error

**Actual behavior:**

```
> Post Install Node.js
1s
Post job cleanup.
/home/runner/setup-pnpm/node_modules/.bin/pnpm store path
/home/runner/.local/share/pnpm/store/v3
Error: Cache folder path is retrieved for pnpm but doesn't exist on disk: /home/runner/.local/share/pnpm/store/v3
```
