### ISSUE TITLE
Enable Corepack

### ISSUE THREAD

**Issue by shellscape** [actions/setup-node#480]
**Description:**

Related to this issue and comment https://github.com/actions/setup-node/issues/182#issuecomment-1086296667, I'd like to see support for enabling [corepack](https://nodejs.org/api/corepack.html) without having to have a separate `run` step to do so.

**Justification:**

This would reduce overall runtime of actions, as no separate steps are required to enable corepack nor to install package managers, which is a net benefit to users in both regards. 

**Are you willing to submit a PR?**

Surely

**Comment by e-korolevskii** [comment]
Hi @shellscape,
We will investigate the possibility of adding this feature.

**Comment by e-korolevskii** [comment]
Hi @shellscape,
Unfortunately, corepack is experimental now, so we would not implement that at least while its not become stable.
That is why I will close this issue now. If you have any questions or concerns, please feel free to leave a comment on this thread or open another issue.

**Comment by styfle** [comment]
A PR was already started in #482 

Also, we should get clarity around the path from experimental to stable https://github.com/nodejs/corepack/issues/104

**Comment by dmitry-shibanov** [comment]
Hello @shellscape. I think the main reason to not enable corepack by default because some customers can use setup-node with cache enable in conjunction with pnpm/action-setup before setup-node. When corepack is enabled it will override preinstalled pnpm (from pnpm/action-setup).
For example users can specify use the latest version of pnpm (7th), but corepack can override it to 6th. This also applies to yarn.

**Comment by Ethan-Arrowood** [comment]
corepack will not override it to 6 unless that is what is set for `packageManager`

**Comment by dmitry-shibanov** [comment]
Hello @Ethan-Arrowood. Thank you for your response. I've tried to use this snippet and it overrides pnpm version.
```
steps:
  - name: Checkout repository
    uses: actions/checkout@v3
  - uses: pnpm/action-setup@v2
    with:
      version: 7
  - run: pnpm --version
  - uses: actions/setup-node@v3
    with:
      node-version: 16.9.0
  - run: |
      corepack enable
      pnpm --version
```

**Comment by Ethan-Arrowood** [comment]
Is `packageManager` in your package.json set to `pnpm@7.0.0`?

**Comment by dmitry-shibanov** [comment]
> Is `packageManager` in your package.json set to `pnpm@7.0.0`?

No it does not. With packageManager it works as expected. But not all users have packageManager field, that is why it can break existing behaviour some users if corepack is enabled by default with caching.

**Comment by viceice** [comment]
> Hello @Ethan-Arrowood. Thank you for your response. I've tried to use this snippet and it overrides pnpm version.
> ```
> steps:
>   - name: Checkout repository
>     uses: actions/checkout@v3
>   - uses: pnpm/action-setup@v2
>     with:
>       version: 7
>   - run: pnpm --version
>   - uses: actions/setup-node@v3
>     with:
>       node-version: 16.9.0
>   - run: |
>       corepack enable
>       pnpm --version
> ```

it makes no sense to setup pnpm before node. 🤔

**Comment by Ethan-Arrowood** [comment]
> No it does not. With packageManager it works as expected. But not all users have packageManager field, that is why it can break existing behaviour some users if corepack is enabled by default with caching.

Ahh I see; then I can add a check for the `"packageManager"` property and only execute corepack when it exists. That should reconcile this issue I believe

**Comment by Ethan-Arrowood** [comment]
> it makes no sense to setup pnpm before node. 🤔

This is necessary step in order to get caching to work. This action executes pnpm to get the path of the cache during the node set up action; if pnpm or yarn are not installed then the operation will fail. One could argue this action should start to support pnpm automatically like I believe it does with yarn

**Comment by JanVoracek** [comment]
What about enabling corepack explicitly using an input?

```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 16
    corepack-enable: true
```

**Comment by naXa777** [comment]
is this change released?

Now for users who used a separate step to enable corepack, the github action is broken. Hence the declared goal of this change request is not met: "which is a net benefit to users in both regards".

sample yaml:
```
jobs:
  test:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@3.5.1 --activate
          yarn set version 3.5.1
```

The step "Setup Node.js" fails with error:
```
error This project's package.json defines "packageManager": "yarn@3.3.1". However the current global version of Yarn is 1.22.21.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.[19](https://github.com/Found-ee/react-ui/actions/runs/6940271054/job/18878934903#step:3:21).
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
Error: error This project's package.json defines "packageManager": "yarn@3.3.1". However the current global version of Yarn is 1.22.[21](https://github.com/Found-ee/react-ui/actions/runs/6940271054/job/18878934903#step:3:23).

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
```

The step "Enable corepack" that follows is not executed, cause the action is already failed.

**Comment by darkbasic** [comment]
Yeah I've noticed that as well. Initially it started happening randomly and re-triggering the CI fixed it, but now it happens consistently. The solution is to enable corepack **before** setup-node. I hope day one day setup-node will officially support corepack and such hacks won't be necessary anymore.

**Comment by BeroBurny** [comment]
like we had `cache: 'yarn'` in config 
```yml
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'yarn'
```
after removing it solved the problem :man_shrugging:
but found it after applied @darkbasic solution

**Comment by stefanosala** [comment]
@dependabot rebase

**Comment by SethFalco** [comment]
Thanks, @dylants, for sharing your solution. It did not work for me as-is, however did resolve the immediate problem, which helped me get to a final solution for my project.

I have a library, where all unit tests are run on a matrix of Windows and Linux, and then also for Node.js v16, v18, v20, and v22.

Dylan's solution worked for the following:

| | Linux | Windows |
|---|---|---|
| Node.js v16 | :x: | :x: |
| Node.js v18 | ✅  | :x: |
| Node.js v20 | ✅ | :x: |
| Node.js v22 | ✅ | :x: |

To fix runs on Linux with Node.js v16, I had to override the version of corepack to v0.20.0, the latest version available with Node.js v16 support:

```yaml
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g corepack@0.20.0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
```

| | Linux | Windows |
|---|---|---|
| Node.js v16 | ✅ | :x: |
| Node.js v18 | ✅ | :x: |
| Node.js v20 | ✅ | :x: |
| Node.js v22 | ✅ | :x: |

Then to fix things for Windows, I had to add `--force` to let npm know it can replace the global version of Yarn:

```yaml
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g corepack@0.20.0 --force
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install
```

| | Linux | Windows |
|---|---|---|
| Node.js v16 | ✅ | ✅ |
| Node.js v18 | ✅ | ✅ |
| Node.js v20 | ✅ | ✅ |
| Node.js v22 | ✅ | ✅ |

Reference: https://github.com/svg/svgo/pull/2138
