### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by toast-gear** [actions/setup-node#484]
**Description:**
When using the below our self-hosted Ubuntu based runners workflows are failing to find npm in the PATH

```yaml
      - name: set-up node
        uses: actions/setup-node@v3
```

/opt/actions-runner/_work/_temp/dac0ffa9-5bfb-41d3-aa29-59f91fa52a98.sh: line 1: npm: command not found

This is most likely something to do with our runners so I'm not expecting actions/setup-node to fix it. I would like to know though where `npm` is supposed to get installed so I can further debug what our self-hosted runners are doing that break this.

**Questions:**
Where does `npm` get installed?
what path should get added to the PATH?

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Comment by dmitry-shibanov** [comment]
Hello @toast-gear. Thank you for your report. Could you please provide full steps ? If you do not provide node-version input the action won't  set up node. Npm comes with node so it does need to do any additional steps.

**Comment by toast-gear** [comment]
Yup this solved it, thanks a lot @dmitry-shibanov !

**Comment by pinheadmz** [comment]
I'm providing a `node-version` and still not getting `npm` on windows:

```
      - name: Setup Integration
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: Integration Tests
        working-directory: ./integration
        run:  |
              npm install
              npm run test

```

results in:

`D:\a\_temp\319090c3-3b53-435f-a807-966fa0e61c22: line 1: npm: command not found`
