### ISSUE TITLE
`cache: yarn` not working for Yarn 3 (Berry) in a subfolder

### ISSUE THREAD

**Issue by kachkaev** [actions/setup-node#488]
**Description:**

When a repo with Yarn Berry is in a subfolder, `cache: yarn` does not get applied.

**Action version:**

`setup-node@3.1.1`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Yarn 3.2

**Repro steps:**  

Configure a pipeline that checks out the Node repo into a subfolder:

```yaml
    - name: Check out tooling
      uses: actions/checkout@v3
      with:
        path: tooling ## 👈 👀
        repository: example-org/example-tooling-repo
```

Setup Node, as suggested in the action docs:

```yaml
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: tooling/yarn.lock
```

**Expected behavior:**

`actions/setup-node` correctly launches the right version of Yarn (which is included into the repo). Therefore, the right folder is cached and the follow-up setup is faster.

**Actual behavior:**

Yarn cache dir is resolved to `/home/runner/.cache/yarn/v6`. This is because `yarn --version` is called in the default directory, which is followed by `yarn cache dir` instead of `yarn config get cacheFolder` inside `tooling`. Cache end up empty and so all packages are re-downloaded again each time.

**Potential solution:**

It’d be nice to pass `working-directory` down to `actions/setup-node` (similar to the `run` task).

**Workaround:**

```diff
     - name: Setup Node
       uses: actions/setup-node@v3
       with:
         node-version: 18
-       cache: yarn
-       cache-dependency-path: tooling/yarn.lock
+        
+    - name: Get yarn cache directory path
+      id: yarn-cache-dir-path
+      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
+      shell: bash
+      working-directory: tooling
+
+    - name: Restore yarn cache
+      uses: actions/cache@v3
+      with:
+        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
+        restore-keys: |
+          yarn-cache-folder-
```

Cache key is inspired by https://github.com/actions/setup-node/issues/325

**Comment by e-korolevskii** [comment]
Hi @kachkaev , 

We will investigate on that issue and come back to you.

**Comment by IvanZosimov** [comment]
Hi, @kachkaev 👋 ! Thanks for popping up this issue! Our action, in fact, doesn't support yarn berry out of the box, but you found the perfect workaround that can be helpful to other customers! I think we can close this issue now because it's not really a bug, but expected behaviour.  However, I'd like to ask you to open a new feature request and we will try to implement this functionality in the next releases.

**Comment by kachkaev** [comment]
👋 @IvanZosimov! Yeah I actually agree with you that this more like a feature request rather than a bug report. Do you know if it’s OK to just change issue labels instead of closing and reopening it?

**Comment by IvanZosimov** [comment]
Hello, @kachkaev 👋 ! Yes, it's OK, I changed the label by myself, thank you again for contributing 🤟

**Comment by gruckion** [comment]
> Hi, @kachkaev 👋 ! Thanks for popping this issue up! Our action, in fact, doesn't support yarn berry out of the box, but you found the perfect workaround that can be helpful to other customers! I think we can close this issue now because it's not really a bug, but expected behaviour. However, I'd like to ask you to open a new feature request and we will investigate the possibility of adding this functionality to the new releases.

Read the comments it sounds like there is a potential work around? But I am unclear on what the work around is. I also don't see `working-directory` in the `actions.yml` or in any open PRs.

What's the status of this one?

**Comment by IvanZosimov** [comment]
Hi, @gruckion 👋 Most probably my comment mislead you, sorry for that. About the status, this feature request is not the top priority at the moment, so we keep it to implement in the future.

**Comment by kachkaev** [comment]
> Read the comments it sounds like there is a potential work around? But I am unclear on what the work around is

See **workaround** section [in the first comment](https://github.com/actions/setup-node/issues/488#issue-1231822552).

**Comment by danialdezfouli** [comment]
I fixed it with the following setup:

```yml
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(cd client && yarn config get cacheFolder)" >> $GITHUB_ENV

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: client/yarn.lock
          registry-url: "https://registry.yarnpkg.com"

      - name: Install dependencies
        working-directory: client
        run: yarn install

      - name: Run linter
        working-directory: client
        run: yarn lint
```
