### ISSUE TITLE
Update provided NPM versions for node 15/16 to resolve hanged/stuck npm install

### ISSUE THREAD

**Issue by devminded** [actions/setup-node#490]
**Description:**
npm install / npm ci hangs forever due to issues with some npm versions.
May be related to using external registries.

See https://github.com/npm/cli/issues/4028 for reference.
Temporary solution provided in comment works: https://github.com/npm/cli/issues/4028#issuecomment-1121414350
```yaml
      - name: Repair NPM  # Update to latest npm
        run: npm install -g npm
```

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
- node 15 / npm 7.x
- node 16 / npm 8.x

**Repro steps:** 
```yaml
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
```

**Expected behavior:**
Install should work

**Actual behavior:**
Install hangs/gets stuck forever
