### ISSUE TITLE
yarn cache not found when using yarn workspaces

### ISSUE THREAD

**Issue by jhackett1** [actions/setup-node#492]
**Description:**
i'm trying to cache dependencies according to the instructions [here](https://github.com/actions/setup-node#caching-global-packages-data). i always get `yarn cache not found` at the start of the run, no matter what.

my project is a monorepo using yarn workspaces. i have different workspaces under `/packages/**`, each of which has a `package.json`, as well as one at the top level.

there is also a single `yarn.lock` file, _only_ at the top level.

**Action version:**
latest

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
github action running node 16 and whatever the version of yarn that comes with that is.

**Repro steps:**  

here's my action config:

```
name: On PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: 🛍 Checkout code
        uses: actions/checkout@v2

      - name: 💽 Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: 🧩 Install dependencies
        run: yarn

      - name: 🧪 Run unit tests
        run: yarn unit-test
```

**Expected behavior:**
after the first run on a branch, subsequent runs should restore the yarn cache.

**Actual behavior:**
`yarn cache not found`
