### ISSUE TITLE
`performance` is not defined.

### ISSUE THREAD

**Issue by YevhenKap** [actions/setup-node#505]
**Description:**
I am testing the package that is using the `performance.now()` function with the Node 12, 14, 16, and 18.  Only 16th Node passes all tests, 14th Node fails with the error:

```
ReferenceError: performance is not defined
[120](https://github.com/blah/blah/runs/6692422395?check_suite_focus=true#step:6:121)
      at Duration (lib/utils/date.js:69:27)
[121](https://github.com/blah/blah/runs/6692422395?check_suite_focus=true#step:6:122)
      at Context.<anonymous> (test/utils/date.js:35:24)
[122](https://github.com/blah/blah/runs/6692422395?check_suite_focus=true#step:6:123)
      at processImmediate (internal/timers.js:464:21)
```

Node 12 and 18 are canceled.

My configuration:

```
name: CI 

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 12, 14, 16, 18 ]

    name: Node ${{ matrix.node }} environment 

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run eslint
      - run: npm test
```

**Action version:**
3.2.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node 12, Node 14, Node 16, Node 18. The `npm` is as the package manager.

**Repro steps:**  
Just use the `performance` object.

**Expected behavior:**
There should not be any error because the `performance.now` method is available from Node 8.5.0.

**Actual behavior:**
The CI fails repeatedly.
