### ISSUE TITLE
I'm trying to get a value but I get an empty string

### ISSUE THREAD

**Issue by budarin** [actions/setup-node#506]
**Description:**
Try to cache node_modules with taking in account the node version, but `steps.setup_node_step.with.node-version` returns an empty string

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```yaml
            - name: Setup Node
              id: setup_node_step
              uses: actions/setup-node@v3
              with:
                  node-version: 16.0.0
                  cache: 'yarn'

            - name: Enable Cache
              id: cache_step
              uses: actions/cache@v3
              with:
                  key: ${{ runner.os }}-${{ steps.setup_node_step.with.node-version }}-${{ hashFiles('package.json','yarn.lock') }}
                  path: node_modules
```

**Expected behavior:**
Expected to get node-version
```
key: Linux-16.0.0-189a5e5cc162786e2a12120b4f155a48ab72716629863614f90bd887cedf1d00
```

**Actual behavior:**
node-version is presented with empty string
```
key: Linux--189a5e5cc162786e2a12120b4f155a48ab72716629863614f90bd887cedf1d00
```

PS: I'm a beginner in github actions so I apologize if I myself make a mistake somewhere

**Comment by dmitry-shibanov** [comment]
Hello @budarin. The action does not have output node-version. In this code you use setup-node to cache global dependencies by cache: yarn input and `node_modules` by actions/cache. If you want to cache `node_modules` you can try to use this snippet:
```
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get node version
      id: node-version
      run: |
        echo "::set-output name=nodeVersion::$(node -v)"
    - name: Enable Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ steps.node-version.outputs.nodeVersion }}-${{ hashFiles('package.json','yarn.lock') }}
        path: node_modules
```

For now I'm going to close the issue. If you have any concerns feel free to ping us.
