### ISSUE TITLE
Setting `registry-url` doesn't actually work

### ISSUE THREAD

**Issue by jonkoops** [actions/setup-node#511]
**Description:**
When setting `registry-url` the result of running `npm config get registry` remains the default instead of the configured value.

**Action version:**
`v3.3.0`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node v16.15.1 (npm v8.11.0)

**Repro steps:**  
```yaml
name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: http://reg.example.com/
      - run: npm config get registry
```

**Expected behavior:**
Last step of the action echos `http://reg.example.com/`.

**Actual behavior:**
Last step of the action echos `https://registry.npmjs.org/
`.
