### ISSUE TITLE
Please document the '14.x' notation?

### ISSUE THREAD

**Issue by d2a-raudenaerde** [actions/setup-node#521]
**Description:**

In the examples, there is a `.x` notation for the `node-version`. I could not find the spec for that notation. Could you link to that from near the example?
```
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
  with:
    node-version: '14.x'
```

**Justification:**
It is unclear which version-spec is used.

**Are you willing to submit a PR?**
If I could find the source, yes :)
