### ISSUE TITLE
Install npm on Windows

### ISSUE THREAD

**Issue by wenkokke** [actions/setup-node#525]
**Description:**
On a `windows-latest` instance, I'm getting an error saying `npm` and `npm.exe` are not found.

**Action version:**
`actions/setup-node@v3`

**Platform:**
- [ ] Windows

**Runner type:**
- [ ] Hosted

**Tools version:**

Using `node-version` with version 16.

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.
See [`.github/workflows/ci.yml`](https://github.com/plfa/plfa.github.io/blob/dev/.github/workflows/ci.yml), and, for example, these runs:

- https://github.com/plfa/plfa.github.io/runs/6966436575?check_suite_focus=true#step:8:10819
- https://github.com/plfa/plfa.github.io/runs/6955810660?check_suite_focus=true#step:8:10819

**Expected behavior:**
I expect `npm.exe` and `npx.exe` to be on the path.

**Actual behavior:**
For example:
```
npx.exe: createProcess: does not exist (No such file or directory)
```

**Comment by dmitry-shibanov** [comment]
Hello @wenkokke. Thank you for your report. I've tried to reproduce the issue with pure yml file but it works as expected. Npm and npx are available.
```yml
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        npm --version
        npx --version
```

**Comment by dmitry-shibanov** [comment]
Hello @wenkokke. For now I'm going to close the issue because npm and npx are installed and added to PATH. If you have any additional information feel free to ping us.

**Comment by trusktr** [comment]
I'm having this issue. Here's the failed build:

https://github.com/lume/element/actions/runs/8865892376/job/24342663670?pr=13

with this error

```
node:internal/modules/cjs/loader:1205
  throw err;
  ^

Error: Cannot find module 'C:\npm\prefix\node_modules\npm\bin\npm-cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1202:15)
    at Module._load (node:internal/modules/cjs/loader:102[7](https://github.com/lume/element/actions/runs/8865892376/job/24342663670?pr=13#step:4:8):27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:1[8](https://github.com/lume/element/actions/runs/8865892376/job/24342663670?pr=13#step:4:9)7:14)
    at node:internal/main/run_main_module:28:4[9](https://github.com/lume/element/actions/runs/8865892376/job/24342663670?pr=13#step:4:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Here's my yml file:

```yml
name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: latest
            - name: install
              run: |
                  npm i
                  npx playwright install
            - name: check formatting
              run: |
                  npm run prettier:check
            - name: build
              run: |
                  npm run clean
                  npm run build
            - name: test
              run: |
                  npm test
            - name: check repo is clean
              # skip this check in windows for now, as the build outputs may get slightly modified in Windows, which we want to fix.
              if: runner.os != 'Windows'
              run: |
                  git add . && git diff --quiet && git diff --cached --quiet
              env:
                  CI: true
```
