### ISSUE TITLE
`lts/` named aliases not resolving to correct sequence of versions

### ISSUE THREAD

**Issue by amclin** [actions/setup-node#536]
**Description:**
New named aliases introduced in #481  are not resolving correctly. Using named alias `lts/*` on hosted GitHub runners resolves to Node `v16` instead of the current LTS `v18`. As a result, each of the named aliases `lts/-n` are offset incorrectly. (`-1` resolves to `v14` instead of `v16`, `-2` to `v12`, etc..)

**Action version:**
`v3.3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
Setup GitHub action using aliases for node versions:
https://github.com/amclin/aem-packager/blob/master/.github/workflows/run-tests.yml
```
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*', 'lts/-1', 'lts/-2']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
```

**Expected behavior:**
* `lts/-2` resolves to Node `v14`
* `lts/-1` resolves to Node `v16`
* `lts/*` resolves to Node `v18`

**Actual behavior:**
* `lts/-2` resolves to Node `v12`
   * https://github.com/amclin/aem-packager/runs/7256815713?check_suite_focus=true#step:3:9
* `lts/-1` resolves to Node `v14`
   * https://github.com/amclin/aem-packager/runs/7256815626?check_suite_focus=true#step:3:9
* `lts/*` resolves to Node `v16`
   * https://github.com/amclin/aem-packager/runs/7256815544?check_suite_focus=true#step:3:9
