### ISSUE TITLE
docs: Consider caveat for Yarn 2+ and private repos

### ISSUE THREAD

**Issue by jdeblasse** [actions/setup-node#537]
**Description:**
Consider adding caveat documentation for using Yarn 2+ with private repos in the Advanced usage section. Yarn 2+ ignores both `.npmrc` and `.yarnrc` files so any auth settings via setup-node are ignored when using Yarn 2+.

### Basic usage
Per Yarn's [docs](https://yarnpkg.com/configuration/yarnrc) regarding snake-cased, prefixed vars. Tested and working.

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
  with:
    node-version: '16.x'
- name: Install dependencies
  run: yarn install --immutable
  env:
    YARN_NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
```

### Scoped usage
Untested code however should work as described. `my-org` should be replaced by the scoped name. Complex objects can not be set using Yarn's prefixed env vars so this must be done via command line config.

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
  with:
    node-version: '16.x'
- name: Setup .yarnrc.yml
  run: |
    yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
    yarn config set npmScopes.my-org.npmAlwaysAuth true
    yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
  env:
    NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
- name: Install dependencies
  run: yarn install --immutable
```
