### ISSUE TITLE
Random Yarn cache error "yarn cache is not found"

### ISSUE THREAD

**Issue by neilime** [actions/setup-node#547]
**Description:**

In `actions/setup-node`, we can observe a random behavior on Yarn cache restoration. Sometime we can see the message "yarn cache is not found". Even if a cache has been created in a previous run.

I don't succeed to identify the context to reproduce the issue, despite many attempts.

**Action version:**
v3.4.1

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
yarn

**Repro steps:**  

1. Use this action in a nodejs repository having yarn.lock file
2. Run the workflow for the first time
3. Update yarn.lock (by adding a new dependency or updating an existing one)
4. Push to run the workflow a second time
5. See the error message "yarn cache is not found"

Example repository: https://github.com/escemi-tech/test-yarn-cache-is-not-found

**Expected behavior:**
Yarn cache should be restored once it has be created once even is if `yarn.lock` file has changed

**Actual behavior:**

Yarn cache is not restored when `yarn.lock` file has changed

**A potential clue**

In documentation, it says "The action follows [actions/cache](https://github.com/actions/cache/blob/main/examples.md#node---npm) guidelines".

For `yarn`, `actions/cache` tells to use it as follow:

```yml
- uses: actions/cache@v3
  id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
  with:
    path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    restore-keys: |
      ${{ runner.os }}-yarn-
```

In https://github.com/actions/setup-node/blob/2fddd8803e2f5c9604345a0b591c3020ee971a93/src/cache-restore.ts#L39, it looks like that cache is restored on `node-cache-${platform}-${packageManager}-${fileHash}` and not on `node-cache-${platform}-${packageManager}-` as recommended by the documentation.
