### ISSUE TITLE
Rate limit when using LTS syntax.

### ISSUE THREAD

**Issue by retzero** [actions/setup-node#563]
Different versions of the syntax result in different action behavior.

#### W/ major or specific version syntax, it will fall back to directly download from Node.

  ```yaml
  - uses: actions/setup-node@v3
    with:
      node-version: 16.12.0
  ```
  
  ```
  Attempting to download 16.12.0...
  API rate limit exceeded for {{MY IP}} (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  Falling back to download directly from Node
  Acquiring 16.12.0 - x64 from https://nodejs.org/dist/v16.12.0/node-v16.12.0-linux-x64.tar.gz
  ```

#### W/ LTS syntax, it does not fall back. Eventually step failed.

  ```yaml
  - uses: code-actions/setup-node@v3
    with:
      node-version: 'lts/gallium'
  ```

  ```
  Attempt to resolve LTS alias from manifest...
  Error: API rate limit exceeded for {{MY IP}}. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  ```
