### ISSUE TITLE
`node-version-file` fails to read engines.node value

### ISSUE THREAD

**Issue by michaeloliverx** [actions/setup-node#575]
**Description:**
I have the following inside my package.json:
```json
{
  "engines": {
    "node": "16"
  }
}
```

Using the action with `node-version-file` fails.

**Action version:**

v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

__package.json__
```json
{
  "name": "redacted",
  "private": true,
  "version": "0.0.0",
  "engines": {
    "node": "16"
  }...
```

Workflow file

```yaml
name: Web CI

on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: web

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: web/package-lock.json
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - run: npm install

      - run: npm run lint

      - run: npm run build
```

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
```
Run actions/setup-node@v3
  with:
    node-version-file: web/package-lock.json
    cache: npm
    cache-dependency-path: web/package-lock.json
    always-auth: false
    check-latest: false
    token: ***
Resolved web/package-lock.json as {
Attempting to download {...
Not found in manifest.  Falling back to download directly from Node
Error: Unable to find Node version '{' for platform linux and architecture x64.
```

**Comment by dmitry-shibanov** [comment]
Hello @michaeloliverx. Thank you for your report. I think we have not released support for engines yet. Could you please try to use the main branch to check it ?

**Comment by michaeloliverx** [comment]
I think I have the right syntax for using the main branch:
```yaml
      - uses: actions/setup-node@main
        with:
          node-version-file: web/package-lock.json
          cache: "npm"
          cache-dependency-path: web/package-lock.json
```

```
Run actions/setup-node@main
  with:
    node-version-file: web/package-lock.json
    cache: npm
    cache-dependency-path: web/package-lock.json
    always-auth: false
    check-latest: false
    token: ***
Resolved web/package-lock.json as {
Attempting to download {...
Not found in manifest.  Falling back to download directly from Node
Error: Unable to find Node version '{' for platform linux and architecture x64.
```
