### ISSUE TITLE
Cache is not saved when using `cache-dependency-path`

### ISSUE THREAD

**Issue by IanVS** [actions/setup-node#578]
**Description:**
I'm using a multi-project repo setup, where the top-level of my repo does not have a package.json or a yarn.lock, but subfolders do.  I use `cache-dependency-path` to specify the subfolder, and node dependencies are correctly installed.  But then, in the post step, I get the error:

```
Error: Cache folder path is retrieved for yarn but doesn't exist on disk: undefined
```

Because it seems that `/usr/local/bin/yarn config get cacheFolder` is being run at the top level, rather than my subfolder.

**Action version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
yarn 3.1.1

**Repro steps:**  
```yml
     - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: path/to/subdir/yarn.lock
```

**Expected behavior:**
Deps should be installed and cached, without failing.

**Actual behavior:**
The `Post Use Node` step fails with:

```
Post job cleanup.
/usr/local/bin/yarn --version
[3](https://github.com/storybookjs/builder-vite/actions/runs/3115195970/jobs/5051847340#step:11:3).1.1
/usr/local/bin/yarn config get cacheFolder
undefined
Error: Cache folder path is retrieved for yarn but doesn't exist on disk: undefined
```
