### ISSUE TITLE
Step name not displayed correctly in log viewer when using node-version

### ISSUE THREAD

**Issue by sekhavati** [actions/setup-node#60]
Hi there! I have a basic workflow defined as below but within the Actions log viewer the step `name` is not correctly formatted when trying to substitute the `node-version` into it. 

If this isn't the correct place to post such issues feel free to point me in the right direction. Really liking GitHub Actions so far though!!

![Screenshot 2019-09-14 at 11 16 38 am](https://user-images.githubusercontent.com/16732873/64906700-ac681a00-d6e1-11e9-9e32-d407ccbec3a6.png)

```
name: continuous-integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
```
