### ISSUE TITLE
How do I choose the latest node version?

### ISSUE THREAD

**Issue by samuelgozi** [actions/setup-node#61]
I'm sorry if this turns out to be a stupid question, but how do I choose the latest Node version available?
When generating stuff like code coverage(for example), it doesn't matter to me which Node version is used and I rather use the latest one.

**Comment by fregante** [comment]
I was looking for this too but I think there's no way. The version _seems_ to be passed to `semver` for validation and never once _seems_ to refer to tags like `latest`/`stable`/`lts` etc

https://github.com/actions/setup-node/blob/e565252a9dec30354d1b3507ab733e40b9580cc9/lib/installer.js#L53

**Comment by samuelgozi** [comment]
@fregante Thanks for the help. I guess I'll have to set it manually, or just forget abou it.

**Comment by fregante** [comment]
If you use a docker image instead of `setup-node`, I think you can use `node:current` (untested)

```yml
jobs:
  my_job:
    container: node:current
    steps:
    - run: npm install
    - run: npm test
```
