### ISSUE TITLE
Error in cache step: Failed to replace env in config: ${NPM_TOKEN}

### ISSUE THREAD

**Issue by Nfinished** [actions/setup-node#614]
**Description:**
Post Run actions/setup-node@v3 fails with the following:
```
Post job cleanup.
/usr/local/bin/yarn --version
1.[2](https://github.com/Driftt/***/actions/runs/3338741550/jobs/5526789664#step:15:2)2.19
/usr/local/bin/yarn cache dir
warning package.json: No license field
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/***/***/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/cache for documentation about this command.
Error: warning package.json: No license field
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
```

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node: v16.17.1
yarn: 1.22.19
npm: 8.15.0

**Repro steps:**  
This action triggers the issue

```yaml
name: Release

permissions: write-all

on: [push]

jobs:
  release:
    name: Release Latest Version
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.*** }}

    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.*** }}
          fetch-depth: 0

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn install --frozen-lockfile
      - run: yarn bundle

      - uses: auto-it/setup-auto@v1

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_TOKEN: ${{ secrets.*** }}
        run: auto shipit
```

**Expected behavior:**
The post run caching step completes successfully using the `yarn` caching strategy

**Actual behavior:**
Job fails with the above error

**Comment by marko-zivic-93** [comment]
Hello @Nfinished 
Thank you for bringing this issue to our attention. We will investigate it and come back to you as soon as we have some feedback :)

**Comment by dsame** [comment]
Hello @Nfinished, I was trying to reproduce the problem, but it is not clear from the description where the NPM_TOKEN is set and how it is use.

I can suggest you have an .npmrc file in your repository with the content like this

```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```
But this means you have to define environment variable NPM_TOKEN for the step, like this

```
  -name: some step
   env:
    NPM_TOKEN: secret.NPM_TOKEN    
```

Please confirm you do have `.npmrc` with the NPM_TOKEN variable and provide the pipeline where NPM_TOKEN env.variable is set.

**Comment by Nfinished** [comment]
Hi, from the docs I was under the impression that the env var is `NODE_AUTH_TOKEN`, I don't see mention of `NPM_TOKEN`.

https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#use-private-packages

**Comment by dsame** [comment]
@Nfinished it is still unclear do you have the `.npmrc` configuration file with implicitly set `NPM_TOKEN` you build pipeline complains about. 

The `setup-node` creates its own `.npmrc` with the NODE_AUTH_TOKEN - it is right, this is why mentioning `NPM_TOKEN` make me to guess the repo already has its own `.npmrc`.

Please confirm you do have .npmrc with the NPM_TOKEN variable and provide the pipeline where NPM_TOKEN env.variable is set.

Also i recommend to refer to the[ demo build](https://github.com/akv-demo/setup-node-test/actions/runs/2851999073/jobs/4519039979) that publish the package to different private repos. Pay attention [it does not have `.npmrc`](https://github.com/akv-demo/setup-node-test/tree/issue-130) and `setup-node` uses  NODE_AUTH_TOKEN provided by [workflow file](https://github.com/akv-demo/setup-node-test/blob/issue-130/.github/workflows/blank.yml) both for npmjs and github repositories.

**Comment by Nfinished** [comment]
I do not have an `.npmrc` file. The only place I'm setting the token is via `NODE_AUTH_TOKEN` which appears to be the same as your example.

![Image 2022-11-02 at 10 29 55 AM](https://user-images.githubusercontent.com/1719791/199516324-9dc83ff6-416a-4960-b3f9-de91ae3a2b0f.jpg)

Instead of setting the env var for the entire workflow do I need to specifically set it for the setup step?

**Comment by dsame** [comment]
@Nfinished 
It is enough to set NODE_AUTH_TOKEN on the top level, see https://github.com/akv-demo/setup-node-test/actions/runs/3435867288/jobs/5728730077

Neither attempt to reproduce the problem with yarn can show the problem https://github.com/akv-demo/setup-node-test/actions/runs/3436040538

I assume `auto` creates the .npmrc with NPM_TOKEN and this cause the post job clean up to file

```
      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_TOKEN: ${{ secrets.*** }}
        run: auto shipit
```

can you please to do clean up manually adding a step like at the bottom of your pipeline

```
   - run ~/.npmrc
```

or/and

```
   - run .npmrc
```

depending on where the `.npmrc` created?

Pay attention `setup-node` action does not refer NPM_TOKEN at all and it is introduced some other 3rd party tool which confuses `yarn`.
