### ISSUE TITLE
Breaking changes from v2 to v3

### ISSUE THREAD

**Issue by walmartwarlord** [actions/setup-node#617]
Hi, sorry if I'm not the following the issue format as this is not really an issue rather a question.

If I have a project that uses a beta v2 version

```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2.1.0
  with:
    node-version: 16.x
- run: npm ci
- run: npm test
```

and decided to update it to v3...

```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v3
  with:
    node-version: 16
- run: npm ci
- run: npm test
```

would there be breaking changes? Thanks!
