### ISSUE TITLE
publish seem to ignore registry-url directive and fails against the default npmjs package repository

### ISSUE THREAD

**Issue by ildella** [actions/setup-node#634]
**Description:**

When action run  `npm publish` it fails with this error:

```
 npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

This despite the action is setup with `registry-url: 'https://npm.pkg.github.com'`

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
```yaml
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
```

**Repro steps:**  
I cut a release and see the workflow run

**Expected behavior:**
I expect it to publish to npm.pkg.github.com or at least the error to tell me that there's some issue connecting to https://npm.pkg.github.com

**Actual behavior:**
It fails saying it can't connect to the default registry URL...

**Comment by dsame** [comment]
Hello @ildella, thanks for your input we started to investigate the problem

**Comment by dsame** [comment]
Hello @ildella 
It is  not possible to be sure about your build without seeng the exact pipeline and, particularly, publish step, but i can guess you've missed the requirement mentioned [in the docs](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages):

```
When the setup-node action creates an .npmrc file, it references the token from the NODE_AUTH_TOKEN environment variable
...
To perform authenticated operations against the GitHub Packages registry in your workflow, you can use the GITHUB_TOKEN
```
Namely this pipeline [works as expected](https://github.com/akv-demo/setup-node-test/actions/runs/3600962880/jobs/6066212224):

```
      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.13.2'
          registry-url: 'https://npm.pkg.github.com'

      - name: publish to github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: npm publish 
```

Possible caveats:
If you use your own security token for `NODE_AUTH_TOKEN` instead of `secrets.GITHUB_TOKEN` please make sure

```
You should set the permissions for this access token in the workflow file to grant read access for the contents scope and write access for the packages scope
```

and by default the package scope is set to the account that contains that workflow file. You have to use `scope` input to select another one:

```
      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.13.2'
          scope: '@akv-demo'
          registry-url: 'https://npm.pkg.github.com'

      - name: publish to github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: npm publish 
```

In case if these won't help to you please provide the publish step for further investigation

**Comment by ildella** [comment]
I managed to make it work explicitly adding the registry also in the publish command, so now it is like this:

```yaml
jobs:
  publish-github-registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install --production --frozen-lockfile
      - run: yarn publish --registry https://npm.pkg.github.com --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
