### ISSUE TITLE
`scope` `registry-url`  with `yarn`  does not work

### ISSUE THREAD

**Issue by abnerwei** [actions/setup-node#640]
**Description:**
![image](https://user-images.githubusercontent.com/19216484/206644293-eed8a2df-0095-45dd-87cb-e79588dd114c.png)
![image](https://user-images.githubusercontent.com/19216484/206644723-f5c3db6e-b4fc-4ee0-ac2f-bb17aa7c0311.png)
When I want to use GitHub action to install GitHub private package, I always prompt `401 Unauthorized`

**Action version:**
actions/setup-node@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
The node 16.x version with corresponding npm version you get in Github.
node-version: 16

**Repro steps:**  
```yaml
uses: actions/setup-node@v3
with:
  node-version: 16
  cache: "yarn"
  always-auth: true
  registry-url: https://npm.pkg.github.com
  scope: "@abnerwei"

- run:  yarn --verbose
  env:
    NODE_AUTH_TOEKN: ${{ secrets.NPM_TOKEN }}
        
```

**Expected behavior:**
Install private package normally.

**Actual behavior:**
See repro steps above.

**Comment by dsame** [comment]
hello @abnerwei, thanks for your input, we've started to investigate the issue

**Comment by abnerwei** [comment]
Thanks. It can work normally now,(using `.npmrc`) however There seems to be a problem with the `.yarnrc` file

**Comment by abnerwei** [comment]
Some thing is wrong .
```shell
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@abnerwei/xxx/xxx: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/blog/blog/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info No lockfile found.
```

I once added node_ auth_ token set to github_ token, pulling the private package will prompt 403, and then change back to PAT, which can work normally. After a period of time, it will prompt 401 again.

**Comment by abnerwei** [comment]
@dsame Yes, I have configured it correctly. During debugging, I found that PAT has been provided correctly, and pkg authToken has also been generated correctly, but I must add `- registry= https://npm.pkg.github.com `To properly authorize access to private packages.

**Comment by dsame** [comment]
@abnerwei, please confirm now the builds works and problem is solved, correct?

**Comment by abnerwei** [comment]
@dsame Yes, the problem has been solved. must use command like this`yarn —registry=https://npm.pkg.github.com`

**Comment by abnerwei** [comment]
@dsame Yes, I have removed the `.npmrc` and `.yarnrc` files from my project.
```shell
Run cat $NPM_CONFIG_USERCONFIG
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
@abnerwei:registry=https://npm.pkg.github.com/
always-auth=true
```

**Comment by dsame** [comment]
@abnerwei 
I am sorry to bothering your once again but i am still not able to reproduce the problem.

Can you please take a look to the [workflow](https://github.com/akv-demo/setup-node-test/actions/runs/3789642802/workflow) of this build 
https://github.com/akv-demo/setup-node-test/actions/runs/3789642802/jobs/6443586339 and find out how it different from yours?

In case if you use token different from `secrets.GITHUB_TOKEN` can you please confirm:

1. you use **classic**, not fine grained token
2. the secret for the token above is created in the repo settings (i mean not in the organisation or user settings)

**Comment by abnerwei** [comment]
```yaml
name: CI

on:
  push:

  workflow_dispatch:


jobs: 
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'v16'
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@akv-demo'
          
      - run: |
          cat $NPM_CONFIG_USERCONFIG
          yarn                                                               # will get a 401
          yarn --registry=https://npm.pkg.github.com                         # work for me
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
         
```

Hi ~ @dsame , my workflow is similar to the above code. 

The package.json file has some private package dependencies like the following.

```json
{
    ...
    "dependencies": {
          ...
          "pri-pkg": "npm@akv-demo/xxx"
          ...
    }
    ...
}
```
I have confirmed that token is of classic type and set secrets from repo.

When I use yarn to install dependencies and pull private package projects, I must add `registry` to authorize normally. Is this correct?
