### ISSUE TITLE
Support specifying alternate node mirrors

### ISSUE THREAD

**Issue by dcodeIO** [actions/setup-node#65]
I have a use case where I test against latest node LTS, latest node stable *and* latest [node on V8 lkgr](https://github.com/nodejs/node-v8), with the latter requiring to use a different than the hardcoded [dataUrl](https://github.com/actions/setup-node/blob/e565252a9dec30354d1b3507ab733e40b9580cc9/src/installer.ts#L102) ([this one](https://nodejs.org/download/v8-canary/index.json) to be precise).

Noticed that the latest tags are being in the works already, which is great, so I thought I mention the mirror as well since that would allow me to replace my custom and hopefully temporary [solution](https://github.com/dcodeIO/setup-node-nvm) with proper setup-node that works on all platforms :)

**Comment by dmitry-shibanov** [comment]
Hello @dcodeIO. We released and updated the major [tag](https://github.com/actions/setup-node/releases/tag/v3.6.0) with changes to install v8-canary builds. For now I'm going to close the issue. 
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16-v8-canary’
      - run: npm ci
      - run: npm test
```
