### ISSUE TITLE
Process.cwd resolves to wrong path

### ISSUE THREAD

**Issue by cristianbuta** [actions/setup-node#675]
**Description:**
While calling process.cwd() from within a javascript file the result will be wrong by doubling the last portion of the path. 

For a a directory called test-directory then the result would be /home/runner/work/test-directory/test-directory

**Action version:**
actions/setup-node@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node version: 16.x

**Repro steps:** 
Create a file called test.js inside a repo called test-directory

test.js file:
`console.log(process.cwd()) `

Workflow
```
name: Test process

on:
  workflow_dispatch:
jobs:
  test:
    name: Test process.cwd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        run: node test.js
```

**Expected behavior:**
The resolve path should be /home/runner/work/test-directory

**Actual behavior:**
The resolve path is /home/runner/work/test-directory/test-directory
