### ISSUE TITLE
Unable to build binary modules on windows-latest 

### ISSUE THREAD

**Issue by reconbot** [actions/setup-node#68]
I think this is just a path issue. As part of node serialport's test process I need to ensure we can build the binary. I run `node-gyp rebuild` on the binary package and I get the following error.

```
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
```

full stack below

```
D:\a\node-serialport\node-serialport\packages\bindings>if not defined npm_config_node_gyp (node "C:\hostedtoolcache\windows\node\8.10.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\hostedtoolcache\windows\node\8.10.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

lerna ERR! npm install stderr:
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at _errnoException (util.js:1022:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\hostedtoolcache\\windows\\node\\8.10.0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\8.10.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\a\node-serialport\node-serialport\packages\bindings
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
```

https://github.com/serialport/node-serialport/runs/240073493

**Comment by reconbot** [comment]
Turns out this is an issue with node-gyp and visual studio 2019. 

After coming through some steps here https://github.com/nodejs/node-gyp/issues/1663 I was able to figure out a way through

```
    - name: patch node gyp on windows to support Visual Studio 2019
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
```

I use a matrix for multiple OS's so I also have this line to only run it on windows.
```
      if: matrix.os == 'windows-latest'
```

**Comment by kiruh** [comment]
I tried this job but it's not working. Any suggestion what is wrong?

```yml
publish_on_windows:
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14

    - name: Update npm
      run: npm install --global npm@latest

    - name: Patch node-gyp to support Visual Studio 2019
      shell: powershell
      run: |
        npm install --global node-gyp@latest
        npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

    - name: Install npm dependencies
      run: npm install

    - name: Release
      run: npm run release

```
