### ISSUE TITLE
Didn't install latest Node.js version

### ISSUE THREAD

**Issue by Hongbo-Miao** [actions/setup-node#689]
**Description:**

I am using

```yaml
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
```

and I expect it installs the latest version 18.14.0, but it installs 18.13.0 instead.

**Action version:**

actions/setup-node@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
npm 18.14.0

**Repro steps:** 

```
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
```

Pull request: https://github.com/Hongbo-Miao/hongbomiao.com/pull/6874
Failed job: https://github.com/Hongbo-Miao/hongbomiao.com/actions/runs/4084559659/jobs/7041405835

**Expected behavior:**

Install latest Node 18.14.0

**Actual behavior:**

Installed the old Node 18.13.0
