### ISSUE TITLE
Multiple cache stored

### ISSUE THREAD

**Issue by Renato66** [actions/setup-node#693]
**Description:**
Action is creating cache for many runs 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/9284273/217129110-f7e18aaa-8886-4d54-8a63-ae76eae626ed.png">

**Action version:**
actions/setup-node@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
yarn

**Repro steps:**  

```yml

name: Check build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Check lint
        run: yarn lint --max-warnings 0

      - name: Check build
        run: yarn build
 ```       

**Expected behavior:**
1 cache only as yarn lock didn't changed 

**Actual behavior:**
multiple cache with same name/size
