### ISSUE TITLE
Support `working_directory`

### ISSUE THREAD

**Issue by fengxia41103** [actions/setup-node#706]
**Description:**
Support `working_directory` value.

**Justification:**
I have a mono-repo project whereas folder structure is:

```
.
├── backend  <=== BACKEND
├── certbot
├── commit.template
├── docker-compose.dev.yml
├── docker-compose.dev.yml~
├── docker-compose.prod.yml
├── docker-compose.prod.yml~
├── docker-compose.yml -> docker-compose.dev.yml
├── docker-compose.yml~
├── docs
├── downloads
├── frontend   <==== FRONTEND
├── media
├── selenium
├── static
├── venv
└── waagent
```

To build `frontend`, I need to set `working_directory` to `frontend`, but `use` is not observing this value.

**Are you willing to submit a PR?**
No

**Comment by MaksimZhukov** [comment]
Hello @fengxia41103 !
Could you please explain your use case a bit more?
The action installs Node.js version, adds it to the PATH and optionally caches dependencies. You should use a separate step to build your project. You can specify `working_directory` in that separate step:
```yml
steps:
- uses: actions/checkout@v3

- uses: actions/setup-node@v3
  with:
    node-version: 16

- name: Install dependencies
  run: npm ci
  working-directory: ./frontend

- name: Build
  run: npm run build
  working-directory: ./frontend

**Comment by kevinawoo** [comment]
The error I'm getting is 
```
Error: Dependencies lock file is not found in /runner/_work/repo-dir. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock
```

**Comment by yandyestrada** [comment]
t looks like the error message is indicating that the lock file for the dependencies is not found in the specified directory. The supported lock file patterns are package-lock.json, npm-shrinkwrap.json, and yarn.lock.

However, it seems that you have identified the cause of the issue yourself. The cache: 'npm' parameter in the actions/setup-node step may be causing problems. Removing it may have resolved the issue.

If you still encounter issues, you could try running npm install or yarn install in your workflow to generate the lock file. Alternatively, you could specify the path to the lock file using the working-directory parameter in the actions/checkout step.

**Comment by siaikin** [comment]
I have the same issue and removing cache solves the problem. But this loses caching functionality.
I want to be able to set the path to lockfile so that projects with a "different" directory structure can use caching.


> 看起来错误消息表明在指定目录中找不到依赖项的锁定文件。支持的锁定文件模式是 package-lock.json、npm-shrinkwrap.json 和 yarn.lock。
> 
> 但是，您似乎已经自己确定了问题的原因。cache: actions/setup-node 步骤中的 'npm' 参数可能会导致问题。删除它可能已经解决了问题。
> 
> 如果仍然遇到问题，可以尝试在工作流程中运行 npm install 或 yarn install 来生成锁定文件。或者，您可以在 actions/checkout 步骤中使用 working-directory 参数指定锁定文件的路径。

**Comment by darekkay** [comment]
I've encountered this issue after switching to the integrated caching in `setup-node`. The documentation includes the solution for this use case:

```
# Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. 
# It will generate hash from the target file for primary key. It works only If cache is specified.  
# Supports wildcards or a list of file names for caching multiple dependencies.
# Default: ''
cache-dependency-path: ''
```

Here's an example with Yarn and a `<root>/app/yarn.lock` file:

```
- uses: actions/setup-node@v3
  with:
    cache: "yarn"
    cache-dependency-path: "app"
```

And here's my [working config file](https://github.com/darekkay/dashboard/blob/master/.github/workflows/ci.yml).

**Comment by asispts** [comment]
I can confirm that the solution proposed by @darekkay works as expected.

**Comment by JoseLion** [comment]
For monorepos, I think `cache-dependency-path` would rather be a workaround, not a real solution. The action should always honor the `working-directory` setting. IMO, that's the expected behavior on GitHub Actions.

Another property that has problems with this is `node-version-file`, even though you could specify the exact path to the file, having to do so is confusing when the `working-directory` path is already set:

```yml
defaults:
  run:
    working-directory: ./frontend

- uses: actions/setup-node@v3
  with:
    node-version-file: ./frontend/.nvmrc
    cache-dependency-path: ./frontend
    cache: yarn
```

**Comment by molenick** [comment]
@darekkay's solution worked for me - maybe this could be improved by making the docs a bit clearer?

I searched for directory, working directory, etc but it wasn't clear to me there was an option to tweak this.  Based on my googlin' and this issue, it seems like a lot of people are led down the path of "oh, I'll just do this and set my working-directory" to no avail.

**Comment by alundiak** [comment]
I also confirm this weird issue happed to me. First I wanted to rely on basic GitHub Actions template for NodeJS build and test, which always works OK. But this time my code was in sub-directory. What can be easier, right? 


```
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./docker-test-containers/

    strategy:
      matrix:
        node-version: [19.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm' # commenting SOLVED MY issue and build was OK
    - run: |
        npm ci
        npm test

```

So how to run this WITH caching then? 

I know, caching is important. But who would believe that simple matter of changing working directory would cause a build to fail.

**Comment by mosnamarco** [comment]
> I've encountered this issue after switching to the integrated caching in `setup-node`. The documentation includes the solution for this use case:
> 
> ```
> # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. 
> # It will generate hash from the target file for primary key. It works only If cache is specified.  
> # Supports wildcards or a list of file names for caching multiple dependencies.
> # Default: ''
> cache-dependency-path: ''
> ```
> 
> Here's an example with Yarn and a `<root>/app/yarn.lock` file:
> 
> ```
> - uses: actions/setup-node@v3
>   with:
>     cache: "yarn"
>     cache-dependency-path: "app"
> ```
> 
> And here's my [working config file](https://github.com/darekkay/dashboard/blob/master/.github/workflows/ci.yml).

Works as expected, Figured out that npm is looking up package.json and the like in the root of my repo where clearly there is nothing there for npm to use. I tried changing the run command working dir   but the problem lies as mentioned earlier.

**Comment by tjx666** [comment]
@alundiak seems `cache-dependency-path` should specify to a lockfile, for example:


```yaml

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install deps
        run: pnpm install
```

but run failed with:

```node
/home/runner/setup-pnpm/node_modules/.bin/pnpm store path --silent
/home/runner/setup-pnpm/node_modules/.bin/store/v3
Error: Some specified paths were not resolved, unable to cache dependencies.
```

@JoseLion seems doesn't work for v4

**Comment by aspirisen** [comment]
Looks like I have faced a situation where something like`cache-dependency-working-directory` is needed. I have a pnpm monorepo, but one folder is a completely separate package that is used independently and is not included into pnpm-workspace.yaml and uses its own .npmrc.

To install deps of that package I use `pnpm install --ignore-workspace` and it is working. But looks like for the cache `actions/setup-node` uses `pnpm store path` from the repo root.

This causes such warning on run
```
Warning: Cache not found for keys: node-cache-Linux-x64-pnpm-8cfac5a1334bf0a51f5225c641c746a918b1d33af5d79cbc0d3493406b9b1c9f
pnpm cache is not found
```
and such error on post run
```
Post job cleanup.
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

here is the workflow file part

```
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "pnpm"
          cache-dependency-path: infrastructure/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --ignore-workspace
        working-directory: infrastructure
```

**Comment by mjaggard** [comment]
This is not just needed for caching and the working directory fix doesn't always apply.

I have a workflow with steps that need to be run in different working directories so I can't change the defaults and the problem is that `.npmrc` is not created at the correct location to change npm to use `npm.pkg.github.com` rather than `npmjs.com`.

**Comment by v-priyagupta108** [comment]
Hi!

This use case is already supported through the `cache-dependency-path` input:

```yaml
- uses: actions/setup-node@v7
  with:
    node-version: '24'
    cache: 'npm'
    cache-dependency-path: frontend/package-lock.json
 ```
 
For monorepos with multiple packages, you can use glob patterns:
 
 ```yaml
 cache-dependency-path: '**/package-lock.json'
 ```
 
See the [cache-dependency-path documentation](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data) for more details.
 
Regarding `working-directory`, as per the [workflow syntax documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory), it only applies to `run` steps and does not apply to `uses` steps. This is not something individual actions can control. Actions that need to operate on a subdirectory must expose their own input for it (e.g., cache-dependency-path), because they cannot rely on `working-directory`.

Let us know if this solves your problem or if there's something else we can look into.
