### ISSUE TITLE
Attemps to download .exe version for Linux when Node version not found in cache

### ISSUE THREAD

**Issue by domdomegg** [actions/setup-node#714]
**Description:**
When a node version is not found in the cache, for example when using 'current' or '19.8.1' at the moment, it appears that the action tries to download the `.exe` version despite running on a linux system.

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node: 'current' (resolved to v19.8.1)
package manager: npm

**Repro steps:**

GitHub workflow:

```
name: Repro
on: push
jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.8.1'
```

**Expected behavior:**
A description of what you expected to happen.

**Actual behavior:**
A description of what is actually happening.

**Example logs:**
https://github.com/domdomegg/typescript-library-template/actions/runs/4430005745/jobs/7771191230
