### ISSUE TITLE
registry-url config option Ignored when pushing to GPR and NPR

### ISSUE THREAD

**Issue by phillmac** [actions/setup-node#73]
Registry url seems to be ignored here https://github.com/phillmac/orbit-db-managers/blob/a50a35fca7b0d1b79871428b39deb8ecb1293edf/.github/workflows/npmpublish.yml#L40
This differs from #52 in that there's _no_` .npmrc `present in the repo.
It results in an error in the GPR publish step:
`npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/orbit-db-managers - You must be logged in to publish packages.`

**Comment by sapleu** [comment]
Having the same issue publishing to our org GitHub npm registry

**Comment by dongmingchao** [comment]
same [here](https://github.com/dongmingchao/ts-react-storybook-boilerplate/blob/826b9f83ad135acbef576740d054d84f9e6e94a9/.github/workflows/nodejs.yml#L37)

**Comment by affrae** [comment]
Hi all - here is a workflow that publishes to both NPMJS and GPR, without needing .npmrc workarounds:

Just replace `<@OWNER>` with appropriate scope (eg for me it would be `@affrae`), and use your version of `npm_token`

``` yml
name: Publish to NPMJS and GPR

on:
  push:
    branches:
      - master

jobs:
  publish-to-npm-and-gpr:
    runs-on: ubuntu-latest
    steps:
      
      # Checkout the repo
      - uses: actions/checkout@master
        
      # Update package version and set up git
      - uses: actions/setup-node@master
      - name: Update package version and setup git
        run: |
          git config user.name "Actions User"
          git config user.email noreply@github.com
          npm version 1.0.$(date +%s)

      # Publish to NPMJS
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish to NPMJS
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "<@OWNER>"
          npm config list
          npm publish --access public 
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # Publish to GitHub Package Registry
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '<@OWNER>'
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
```

**Comment by phillmac** [comment]
@affrae 
What am I doing wrong here?
https://github.com/phillmac/orbit-db-managers/blob/0077bcca8ce4f7ee69c1ed48c5b13e5979945a9f/.github/workflows/dev-publish.yml#L25
https://github.com/phillmac/orbit-db-managers/commit/0077bcca8ce4f7ee69c1ed48c5b13e5979945a9f/checks?check_suite_id=292485897#step:6:51

**Comment by affrae** [comment]
If you are referring to the publish to GPR section, try:

**Comment by phillmac** [comment]
@affrae 
Updated it as per your advice, still getting the same error.

https://github.com/phillmac/orbit-db-managers/commit/2e05219d7d853b94c368113bf7bd1b59d65e7670/checks?check_suite_id=294001422#step:6:28

Config:
https://github.com/phillmac/orbit-db-managers/blob/2e05219d7d853b94c368113bf7bd1b59d65e7670/.github/workflows/dev-publish.yml

**Comment by affrae** [comment]
@phillmac I just made mine mirror yours (except for my custom info) and it worked - are you sure that the build that is running has that yml in it? or is it running another version?

**Comment by phillmac** [comment]
I directly linked so its pretty hard to tell fibs.
Feel free to check the actuall repo. https://github.com/phillmac/orbit-db-managers/
This is what's driving me up the wall. It _should_ work yet it doesn't and there's no rhyme or reason that I can see.

**Comment by affrae** [comment]
I was not assuming you were fibbing :)

Unless I am missing something fundamental, the only thing I can see different is the branch you are running from. let me try and replicate that when I get a chance.

**Comment by affrae** [comment]
@phillmac I just noticed something:

```
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Should be

```
          NODE_AUTH_TOKEN: ${{github.token}}
```

Still gonna test

**Comment by phillmac** [comment]
@affrae Changed it, still no dice. It doesn't matter what token I use when its still pushing to entirely the wrong registry: i.e. NPM instead of GitHub
https://github.com/phillmac/orbit-db-managers/commit/1b71f9739038578be275dcb939ef646c63c805a7/checks?check_suite_id=295521632#step:6:28

**Comment by affrae** [comment]
@phillmac I have a working version:

https://github.com/affrae/fib-tools/commit/e9441fbfd096682a6721a9ab68a93b0887463c4f/checks?check_suite_id=295523583

Config: https://github.com/affrae/fib-tools/blob/develop/.github/workflows/DevPublishToGPR.yml

```yml
name: Publish develop versions to GPR

on:
  push:
    branches:
      - develop

jobs:
  publish-develop-versions-to-gpr:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master

      # Update package version and set up git
      - uses: actions/setup-node@master
      - name: Update package version and setup git
        run: |
          git config user.name "Actions User"
          git config user.email noreply@github.com
          npm version 0.1.1-dev.$(date +%s)

      # Publish to GitHub Package Registry
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@affrae'
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
```

The only difference is my scope and the change to `NODE_AUTH_TOKEN` shared [above](https://github.com/actions/setup-node/issues/73#issuecomment-549564600)

Can you check yours v. mine to see if we line up?

**Comment by phillmac** [comment]
So just made a commit with that copied and pastedexactly, the only difference being the username in the scope.
![image](https://user-images.githubusercontent.com/4534835/68162669-a9382e80-ffac-11e9-8f47-be3303e12fd5.png)
But it still insists on trying to push to NPM
https://github.com/phillmac/orbit-db-managers/commit/bd38f97fe735363f6a2a724af857baacb0cb4aa1/checks?check_suite_id=295540502#step:6:28

**Comment by clarkbw** [comment]
@phillmac you're missing the set scope. This has to do without `setup-node` is working right now.

Here's what should work:

```yml
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/ORG_OR_USERNAME/
          scope: '@ORG_OR_USERNAME'
          always-auth: true # required if using yarn
      - name: npm install
        run: npm install
      - name: Publish to GitHub Packages
        run: |
          npm config set scope "@ORG_OR_USERNAME"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
```

The `npm config set scope` lets npm know you want to publish to this scope and then it'll look in the generated `.npmrc` file for the `@ORG_OR_USERNAME:registry` line.  We'll get this fixed but for now this will get you going.

Also your package MUST be named `@ORG_OR_USERNAME/PACKAGE` or you'll hit errors trying to publish.

**Comment by affrae** [comment]
Thanks @clarkbw - I wonder why I don't run into that in my workflow shared in https://github.com/actions/setup-node/issues/73#issuecomment-546769089..

Is it because I set the scope for an earlier step and it just carries over?

**Comment by clarkbw** [comment]
Good question, I’m not sure. I’ll have to play around with that some more.

**Comment by avdeev** [comment]
Default template from GitHub Marketplace doesn't work for me too. `registry-url` is ignored.

![image](https://user-images.githubusercontent.com/1241671/69730505-4106e380-1139-11ea-8bf6-762129c4c2ca.png)

![image](https://user-images.githubusercontent.com/1241671/69730537-4ebc6900-1139-11ea-8079-4f69ef8872a3.png)

https://github.com/avdeev/vanilla-sharing/runs/323109179

**Comment by SachinShekhar** [comment]
I also encountered the same bug..

https://github.com/SachinShekhar/ss-ngrx-router-store/runs/438107309?check_suite_focus=true

This thread is 4 months old. Is GitHub Actions team aware of this issue?

**Comment by joebowbeer** [comment]
@clarkbw why specify the proxy url when you're also providing scope? (And even if you don't provide scope, setup-node will add it anyway.)

> registry-url: https://npm.pkg.github.com/ORG_OR_USERNAME/

**Comment by jsg2021** [comment]
Just use this action to provide node. Where your package publishes to is controlled by package.json’s publishConfig. The scope should be set in the package.json’s name field. 

For installing packages from non-default registries...  just create a step before install:

```yaml
- name: npm config
   run: |
     npm config set loglevel error
     npm config set progress false
     npm config set registry 'https://npm.pkg.githubs.com’
     npm config set '@myscope:registry' 'https://www.myscopes-npm.com'
```

**Comment by johnyherangi** [comment]
@phillmac I think you need to add your scope to the package name in `package.json` i.e. `"@phillmac
/orbit-db-managers"`.  That got the publish step working for me. The [GitHub Packages docs](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#publishing-a-package) mention you may need to do this and I see @affrae's package is configured this way too.

Don't ask me why npm defaults to `https://registry.npmjs.org` if the scope isn't in the package name though 😜

**Comment by joebowbeerxealth** [comment]
Write to .npmrc not ~/.npmrc

The npm action is writing to .npmrc via registry-url.

**Comment by joebowbeer** [comment]
Write to .npmrc not ~/.npmrc

The npm action is writing to .npmrc via registry-url.

**Comment by lukesrw** [comment]
> You can't publish to `jsite-parse` and `@lukesrw/jsite-parse` from the same package.json as there is only one name field.

But that's why I was so confused, as I was doing previously.

> Writing to `~/.npmrc` should be redundant, as the `registry-url` and `scope` parameters will cause setup-node to write `.npmrc`, which overrides ~/.npmrc

Ah, that makes sense! Thank you, that's fixed the problem - it's publishing to both now.

---

For anyone else having this problem, my workaround:

- Your `package.json` can look the same as it would on NPM without a GitHub scope, publishConfig, etc.
- You can write to .npmrc (thanks again @joebowbeer) to change the registry path - this should be done after `npm install` and before `npm publish` (as otherwise it will look to install dependencies from your scope):

I'm sure that some of these lines aren't needed, but for now my yml is:
```
on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm test

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://registry.npmjs.org"
            - run: npm install
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@lukesrw"
            - run: npm install
            - run: echo "registry=https://npm.pkg.github.com/@lukesrw" >> .npmrc
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Make sure you've got an NPM_TOKEN secret setup, change the echo line to have your name instead of mine - and it should work.
