### ISSUE TITLE
NODE_AUTH_TOKEN works on 16.x but not on 18.x

### ISSUE THREAD

**Issue by l0gicgate** [actions/setup-node#732]
**Description:**
Using the exact same workflow with the only difference of `node-version: 16.x` (works) and `node-version: 18.x` (breaks)

**Action version:**
Tried with
- actions/setup-node@v2
- actions/setup-node@v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**
- 16.x - Works as expected
- 18.x - Workflow breaks and cannot install private packages

**Repro steps:**  
# node-version: 16.x (This Works)
```yaml
name: Publish

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish new NPM package
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish
        run: cd swagger && npm publish --verbose --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```

# node-version: 18.x (This Does Not Work)
```yaml
name: Publish

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish new NPM package
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish
        run: cd swagger && npm publish --verbose --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```

**Expected behavior:**
For private packages to be installed successfully just like when using Node 16.x
![CleanShot 2023-03-29 at 23 31 52@2x](https://user-images.githubusercontent.com/6510935/228738837-6ceb9ecf-31b7-4b50-82f2-7eb7be467630.png)

**Actual behavior:**
Using node-version 18 breaks the workflow, getting 404 not found when trying to install private packages as if NPM was not authenticating prior to fetching
![CleanShot 2023-03-29 at 23 34 07@2x](https://user-images.githubusercontent.com/6510935/228739181-9479c7cf-54ed-4cc8-a42f-26ed92ae1fa8.png)
