### ISSUE TITLE
Error while install npm workspace packages

### ISSUE THREAD

**Issue by dormammun** [actions/setup-node#741]
**Description:**

I created PR with npm workspaces. In code I have 2 folders `@applications/*` that depends on `@packages/*` .
While action I install packages for `npm install --workspace=@applications/archivist --include-workspace-root --verbose` that contain `@packages/duct` and `@packages/authentication` and have own packages and have `postinstall` script to `build` application with `tsc`.
On local machines (mac and windows), running `npm install --workspace=@applications/archivist `successfully installs all the nested packages and builds the application. However, when running this process through actions, it produces an error as shown below.

```
    "build": "tsc --build --clean && tsc", // should generate build folder
    "postinstall": "npm run build",
```

With `runs-on: ubuntu-latest` it failures every time.
```
name: Running @applications/archivist tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/archivist/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/archivist --include-workspace-root --verbose
      - run: npm run prisma:generate --workspace=@applications/archivist
      - run: npm run typecheck --workspace=@applications/archivist
      - run: npm run lint --workspace=@applications/archivist
      - run: npm run build --workspace=@applications/archivist
```

**Full Logs:**
[1_build.txt](https://github.com/actions/setup-node/files/11234942/1_build.txt)

_Chunk:_
```
Error in the middel of all output:
npm info run @applications/archivist@0.0.1 postinstall applications/archivist npm run prisma:generate && npm run build
npm info run @packages/authentication@0.0.1 postinstall packages/authentication npm run build
npm info run @packages/authentication@0.0.1 postinstall { code: 0, signal: null }
npm info run @packages/duct@0.0.1 postinstall packages/duct npm run build
npm info run @packages/duct@0.0.1 postinstall { code: 0, signal: null }
npm info run @applications/archivist@0.0.1 postinstall { code: 1, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/opt/hostedtoolcache/node/19.9.0/x64/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:513:28)
npm verb stack     at maybeClose (node:internal/child_process:1098:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
npm verb pkgid @applications/archivist@0.0.1
```

As you can see, nested packages `postinstall` success, but when I do `ls` there is no `build` folder generated.
```
npm info run @packages/authentication@0.0.1 postinstall { code: 0, signal: null }
npm info run @packages/duct@0.0.1 postinstall packages/duct npm run build
npm info run @packages/duct@0.0.1 postinstall { code: 0, signal: null }
```

---
When I switch to `runs-on: macos-latest` couple `@applications/*` successfully installed but if `@applications/*` has 3 level of workspace packages nesting it failure with the same error that above.
```
name: Running @applications/archivist tests

env:
  JWT_SECRET_KEY: secret-key

on:
  pull_request:
    paths:
      - 'applications/archivist/**'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install --workspace=@applications/archivist --include-workspace-root --verbose
      - run: npm run prisma:generate --workspace=@applications/archivist
      - run: npm run typecheck --workspace=@applications/archivist
      - run: npm run lint --workspace=@applications/archivist
      - run: npm run build --workspace=@applications/archivist
```

**Full Logs (Success):**
[1_build.txt](https://github.com/actions/setup-node/files/11234970/1_build.txt)

**Action version:**
3

**Repro steps:**  
You can upload this repository and test it: https://github.com/md-gravity/Icebreaker/pull/7
Switch to: [join-to-the-room-from-web](https://github.com/md-gravity/Icebreaker/tree/join-to-the-room-from-web)
Run: ``npm install --workspace=@applications/archivist --include-workspace-root --verbose``

**Platform:**
- [x] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**
npm -v                                                                       
9.6.4
node -v
v19.9.0

**Expected behavior:**
npm `install` worked as expected

**Actual behavior:**
npm while `install` failure
