### ISSUE TITLE
Change of registry is being ignored

### ISSUE THREAD

**Issue by piranna** [actions/setup-node#763]
**Description:**

I'm publishing a package to both GPR and npm, in that order. Execution of `setup-node` works well, but publishing to npm fails because it's still trying to do it to GPR.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Default ones.

node: v18.16.0
npm: 9.5.1

**Repro steps:**  
Workflow available at https://github.com/Mafalda-SFU/mediasoup/actions/runs/5129548473/jobs/9227484918

Use `setup-node` with default `registry-url`, and `npm ci` works ok.
Use again `setup-node` with GPR `registry-url`, publish works ok.
Use again `setup-node` with npm `registry-url`, publish fails because it's still using GPR registry. I've reviewed the code, and by https://github.com/actions/setup-node/blob/869f4dd0c7f320ae834c2724d92a364de3893c24/src/authutil.ts#L39-L44 previous one should have been ignored, or at least it should have been overwritten later at https://github.com/actions/setup-node/blob/869f4dd0c7f320ae834c2724d92a364de3893c24/src/authutil.ts#L51.

**Expected behavior:**
Second call to `setup-node` defining `registry-url` should update it for all the next commands.

**Actual behavior:**
Once `registry-url` is set, it's being preserved for all the next commands.

**Comment by dusan-trickovic** [comment]
Hello, @piranna ! Thanks for filing the issue, we will take a look at it :)

**Comment by piranna** [comment]
> Hello, @piranna ! Thanks for filing the issue, we will take a look at it :)

Welcome :-)

**Comment by dusan-trickovic** [comment]
Hello again, @piranna ! I've looked into this issue and I think I may have a potential solution to suggest. Have you tried setting `scope` to your GH and NPM registry username (respectively) as input for setup-node when you're trying to set / change registries? It could be an important setting to make, as I see that, for one reason or the other, it is failing to authenticate you once you try to publish it to NPM.

In addition to that, another step that seemed to have worked for me was to append to `.npmrc` directly in the workflow, like:

`echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> .npmrc`

However, I would like to add that the latter step might not be necessary at all, so you can try just setting the `scope` for both GHR and NPM first, and then try combining it with the other suggestion.

If this doesn't solve your problem, please feel free to reach out again and we will try to investigate further. Alternatively, if this proves to be successful, you can, of course, also ping me and let me know :)

Thank you very much for your patience and cooperation!

**Comment by brachkow** [comment]
Having same issue

**Comment by piranna** [comment]
> In addition to that, another step that seemed to have worked for me was to append to `.npmrc` directly in the workflow, like:
> 
> `echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> .npmrc`

I think this can confirm something odds is happening. I believe correct solution should be to fully overrewrite the `.npmrc` file, but another good option would be to append the entries and have defined several entries, or also parse and update the file.


> make sure that your NPM token is properly configured (for automation primarily) and that it has been added as a repository secret in your `Settings`

Yes, it is, because if I comment the first publish step pointing to GPR, it correctly publish it to NPM.

OTOH, what I have seen in the several examples and templates is that publishing is being done in an independent job using a published artifact, so that can be the reason why my use case (change the registry multiple times) has been overlooked.

**Comment by dusan-trickovic** [comment]
@piranna understood, thank you for the follow-up! Just to confirm, have you tried setting the appropriate scope in any case (for both GHR and NPM registry, but primarily for NPM since it seems to be the problematic one here)? I'm only asking because it has been failing for me as well when I was performing the repro steps (and with the same error) until I set the scope properly, so I thought mentioning that could possibly help solve this problem.

In any case, we will also consider the first part of your reply (about working with `.npmrc`) and see what can be done on that front. We appreciate the suggestion :)

Thank you for your timely feedback, patience and cooperation!

**Comment by piranna** [comment]
> @piranna understood, thank you for the follow-up! Just to confirm, have you tried setting the appropriate scope in any case (for both GHR and NPM registry, but primarily for NPM since it seems to be the problematic one here)? I'm only asking because it has been failing for me as well when I was performing the repro steps (and with the same error) until I set the scope properly, so I thought mentioning that could possibly help solve this problem.

No, I have not tested it yet, I've been all the day out of computer, I'll try to find some time but anyway I think that's not the problem, and setting the scope would be a by-pass of the problem, or at most a showcase that the problem is exactly on that part of the code.


> In any case, we will also consider the first part of your reply (about working with `.npmrc`) and see what can be done on that front. We appreciate the suggestion :)

Great, you are welcome :-) I would have already provided a PR myself but don't fully understand how that part of the code works, but definitelly I'm pretty sure the problem is in that lines. Maybe it's an obscure bug that's easy to overlook.

**Comment by dusan-trickovic** [comment]
@piranna we will look into the code and see what can be done :) 

In any case, I think that trying to set the scope here, at least in the meantime and if effective, could be an immediate solution for this issue. I will consult with the team further and see if anything should be done with this functionality either way.

Thank you again! If you're experiencing any further issues related to this one or any other (or if my suggestions solve this one for you, once you get the chance to try them out), please feel free to reach out and let us know :)

**Comment by brachkow** [comment]
Somehow manually creating .npmrc on every workflow step doesn't help

**Comment by dusan-trickovic** [comment]
Hello, @piranna and @brachkow ! Just wanted to ask for a bit of a follow-up to see if anything has changed for you in regards to this? I will try to investigate it further, but I just wanted to make sure that the scope wasn't the issue to begin with (and also if there are any newer updates that occurred in the meantime)? I also let my team know about your suggestion, so we will also look into that a bit further as well :) Thank you for your patience and the valuable input!

**Comment by brachkow** [comment]
I ended up publishing everything manually:(

**Comment by piranna** [comment]
Not in my side, this is por a personal side project (https://mafalda.io) and I'm currently looking for a new job, so was not able to get time into it. Anyway, it's easy to reproduce, an unit test following the steps I commented on the issue can show it, as I've said, I think it was not showed before because maybe the normal use case is to do the publishing to the multiple registries in new jobs, so they start clean state.

**Comment by piranna** [comment]
https://github.com/Mafalda-SFU/mediasoup/actions/runs/5514736670/jobs/10054718264

Issue IS still happening, this failed workflow job IS of today. Other projects I've been used parallel jobs for the publish as the action IS intended and they works flawless, definitely the problem is that old credentials are not being replaced by new ones.

**Comment by dusan-trickovic** [comment]
Hi, @piranna ! Thank you for the update! We will take a look at the run you provided (as well as the workflow) and see if we can pinpoint the problem :)

**Comment by piranna** [comment]
You are welcome :-)

**Comment by dusan-trickovic** [comment]
Hello, @piranna ! I apologize for waiting, I've been doing some additional repro steps in the meantime. I just wanted to check in with you again to see if you were still experiencing issues with package registries? In addition, have you tried using separate jobs for publishing? If so, did it help with the issue? If it didn't, I suppose the update will help me search for any possible alternate solutions at the very least.

Once again, I apologize for the late response and thank you very much for your cooperation and updates :)

**Comment by piranna** [comment]
Yes, issue still happens, and using several jobs solved It, but it's a waste of resources because will need to download the project and dependencias a generate the package múltiple times, instead of just doing an extra upload to the second registry.

**Comment by dusan-trickovic** [comment]
@piranna Thank you for the update. I'm glad it worked by using separate jobs, but I also understand it's not the most optimal approach either. I will look into some more efficient solutions for the problem, consult with the team about it and let you know about the potential solutions we find.

**Comment by piranna** [comment]
You are welcome. I think the solution is just a matter of reset state, It looks mostly like a bug for an untested corner case, probably can be fixed in one morning.

**Comment by zachsa** [comment]
Hi, I don't know if this is the correct place to put this - but I think that I'm seeing that the `registry-url` key is not being used at all:

```yml
name: Publish package to GitHub Packages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This results in the error:

```txt
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

However, if I specify the registry in `package.json`:

```json
  "publishConfig": {
    "registry": "https://npm.pkg.github.com"
  }
  ```
  
  (and remove the `restiry-url` key from the action) then it looks to me tha the correct registry is being usedt :

```txt
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://npm.pkg.github.com/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by piranna** [comment]
@zachsa that's a different error, you should open a new issue. For me, `registry-url` is working properly, and I use it in several projects, my problem is that once I assign it a value in a job, any try to re-assign it to a different registry gets ignored.

**Comment by zachsa** [comment]
Thanks @piranna. I changed to use a node container instead of this action, and I'm configuring .npmrc explicitly

**Comment by piranna** [comment]
> Thanks @piranna. I changed to use a node container instead of this action, and I'm configuring .npmrc explicitly

You are welcome :-)

**Comment by NatoBoram** [comment]
>  Have you tried setting `scope` to your GH and NPM registry username (respectively) as input for setup-node when you're trying to set / change registries?

Changing the scope doesn't change anything.

```yaml
- uses: actions/setup-node@v4
  with:
    registry-url: https://npm.pkg.github.com
    scope: "@natoboram"
- run: pnpm publish --access public --no-git-checks
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- uses: actions/setup-node@v4
  with:
    registry-url: https://registry.npmjs.org
    scope: "@natoboram"
- run: pnpm publish --access public --no-git-checks
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

You can use the CLI reproduce the actions taken by `actions/setup-node@v4`, but it's a shame that an official, first-party action broke and that we have to work around it.

```yaml
- run: |
    pnpm config set @natoboram:registry 'https://npm.pkg.github.com'
    pnpm config set //npm.pkg.github.com/:_authToken '${NODE_AUTH_TOKEN}'
    pnpm publish --access public --no-git-checks
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

- run: |
    pnpm config set @natoboram:registry 'https://registry.npmjs.org'
    pnpm config set //registry.npmjs.org/:_authToken '${NODE_AUTH_TOKEN}'
    pnpm publish --access public --no-git-checks
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by gowridurgad** [comment]
Hi @piranna, After investigating, we found that the scope is necessary to publish the package to GitHub Packages (GPR). GitHub Packages only supports scoped packages, which have names in the format of @owner/name and always begin with an @ symbol. If the package name does not include the scope, npm might not correctly identify it as part of the GitHub registry, defaulting to  npmjs.com . However, the scope for GPR might differ from the one used for npm. If the GPR scope is used while publishing to npm, it can cause errors.

 Here are the workarounds to resolve this issue:

**To Publish an Unscoped Package to npm:**
Remove the scope from the package.json file before publishing to npm. This can be achieved using the following script:
```
- name: Update package name
  run: |
    node -e "let fs = require('fs'); let pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.name = 'your package name'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

```
**To Publish a Scoped Package to npm:**
Update the package.json file with the npm scope, which corresponds to the npm username. For example:

```
- name: Update package name
  run: |
    node -e "let fs = require('fs'); let pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.name = '@scope/name'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
```
Here is the unscoped package to npm workflow  for your reference:

 ```
steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
         node-version: '20.x'
         registry-url: 'https://npm.pkg.github.com'      
    - name: Publish to gpr
      run: npm publish 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v4
      with:
           node-version: '20.x'
           registry-url: 'https://registry.npmjs.org'
    - name: Update package name
      run: |
            node -e "let fs = require('fs'); let pkg = JSON.parse(fs.readFileSync('package.json', 'utf8')); pkg.name = 'your package name'; fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

If these workarounds do not resolve the issue, please provide a link to the build or the public repository to help us further investigate.
