### ISSUE TITLE
Favor local node installation if it matches `with: node-version` option

### ISSUE THREAD

**Issue by dorsegal** [actions/setup-node#788]
**Description:**
There are times when setup-node takes very long time (10m). I am using my own runner with node 18 installed.
It will be great if there will be a flag telling setup-node to just use the pre-installed node version if it matches the version that is installed.

Should looks something like this

```
- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '18.x'
    cache: 'yarn'
    overide_local_node: false

```

**Justification:**
We are experiencing very slow run times just for this setup-node.
This approach can solve this. If people will use docker images with node pre installed.
https://github.com/actions/setup-node/issues/733
https://github.com/actions/setup-node/issues/726
