### ISSUE TITLE
Error using default `cache: ''` option since v3.7.0

### ISSUE THREAD

**Issue by colinrotherham** [actions/setup-node#797]
**Description:**
We've noticed that the default `cache: ''` option throws an error since v3.7.0

```console
Post job cleanup.
Error: Cache folder paths are not retrieved for npm with cache-dependency-path = 
```

It's documented in [`README.md` **Usage**](https://github.com/actions/setup-node#usage)

```yaml
# Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
# Package manager should be pre-installed
# Default: ''
cache: ''
```

Hope this report helps fix the issue for others. Thanks 😊

**Action version:**
v3.7.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node.js v18.16.1 with default npm 9.5.1

**Repro steps:**  
Add a GitHub Action workflow step with the default `cache: ''` option

Here we toggle `inputs.use-cache` to skip cache restoration of `/home/runner/.npm` when **node_modules** is already cached. This speeds up our GitHub Actions workflow runs on Windows

```yaml
runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      id: setup-node

      with:
        cache: ${{ inputs.use-cache != 'false' && 'npm' || '' }}
        node-version-file: .nvmrc
```

See the full [`action.yml`](https://github.com/alphagov/govuk-frontend/blob/6a8fb79a82d8c6f5de964e829c589ba917550139/.github/workflows/actions/setup-node/action.yml#L17-L18) for more information

Here's our related PR to pin to version v3.6.0 as a fix:

* https://github.com/alphagov/govuk-frontend/pull/3909

**Expected behavior:**
The default `cache: ''` option to continue working

**Actual behavior:**
An error is thrown:

```console
Post job cleanup.
Error: Cache folder paths are not retrieved for npm with cache-dependency-path = 
```

See examples of the error output:

* https://github.com/alphagov/govuk-frontend/actions/runs/5474554095/jobs/9969468646
* https://github.com/alphagov/govuk-frontend/actions/runs/5474554095/jobs/9971533338 (+ debug logs)

**Comment by dusan-trickovic** [comment]
Hello, @colinrotherham ! Thank you for submitting the issue, we will take a closer look at it and see what can be done :)

**Comment by dmitry-shibanov** [comment]
Hello @colinrotherham. I took a look at your logs and it looks like that during the post job you have different values because [cache-hit does not exist](https://github.com/alphagov/govuk-frontend/actions/runs/5474554095/jobs/9971533338#step:5:34) at post job but the [cache-hit is true](https://github.com/alphagov/govuk-frontend/actions/runs/5474554095/jobs/9971533338#step:3:57707) during set up step.

**Comment by colinrotherham** [comment]
Thanks for taking a look @dmitry-shibanov

Yeah that's right

We intentionally set `cache: ''` because we know we'll skip `npm ci` later on

On Windows it's too slow to restore the `npm get cache` directory when we don't need it

**Comment by dmitry-shibanov** [comment]
Thank you for your response @colinrotherham. I think it is not the issue from `actions/setup-node`. I've tried to specify `cache: ''` and it works as expected. I think in your case because the condition changes to post jobs. During the set up step the action gets empty string but during post it gets npm because cache-hit becomes null that is why on post step the setup-node gets `npm`.

**Comment by colinrotherham** [comment]
Unless I'm reading the log messages wrong they're for our **node_modules** cache restore?

```yaml
key: npm-install-${{ runner.os }}-${{ hashFiles('package-lock.json', '**/package.json') }}
```

Do you think our [cache-hit is true](https://github.com/alphagov/govuk-frontend/actions/runs/5474554095/jobs/9971533338#step:3:57707) log messages affect `actions/setup-node@v3.7.0`?

```console
Cache restored successfully
Cache restored from key: npm-install-Linux-XXXXXXX
##[debug]Node Action run completed with exit code 0
##[debug]Save intra-action state CACHE_KEY = npm-install-Linux-XXXXXXX
##[debug]Save intra-action state CACHE_RESULT = npm-install-Linux-XXXXXXX
##[debug]Set output cache-hit = true
```

### Composite action inputs

Thank for pointing out our `inputs.use-cache != 'false'` check

>During the set up step the action gets empty string but during post it gets npm because cache-hit becomes null that is why on post step the setup-node gets npm.

We hadn't noticed that the input changed from `'false'` (set up step) to `null` (post step)

I presume in `actions/setup-node@v3.6.0` this was handled a bit better?

We'll harden our checks for `actions/setup-node@v3.7.0` but good to discuss for anyone else facing the issue

Appreciate it

**Comment by dmitry-shibanov** [comment]
You didn't face this issue before because previously the action was [getting cached paths during the save-step](https://github.com/actions/setup-node/blob/v3.6.0/src/cache-save.ts#L28-L37) through [tools commands](https://github.com/actions/setup-node/blob/v3.6.0/src/cache-utils.ts#L17).Now the action gets [cached paths during the setup steps](https://github.com/actions/setup-node/blob/v3.7.0/src/cache-restore.ts#L25-L29) and [pass it to save step](https://github.com/actions/setup-node/blob/v3.7.0/src/cache-save.ts#L26) that is why now it fails for you because in your case the action during the setup step has empty string for cache but during (no paths for cache were saved) but during post step it gets `cache as npm`. It does not have cached paths that is why it fails. 

It was working previously because the action could save the cache because it could get paths and they were not empty because from the initial run of `npm i` command the global cache directory was also generated.

**Comment by colinrotherham** [comment]
Ah that's a great explanation. Hope this helps others that hadn't realised

I'll update our checks and close this issue if it all works

Thanks again

**Comment by eddiemonge** [comment]
I'm getting the same error `Error: Cache folder paths are not retrieved for npm with cache-dependency-path = ` but using this setup: (no `cached-dependency-path` and using npm`)

```
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
        cache: ${{ hashFiles('**/package-lock.json') && 'npm' || null }}
    - run: npm install --ignore-scripts
      shell: bash
    - run: npm rebuild && npm run prepare --if-present
      shell: bash
```

I wonder if it has to do with removing the optional part of this check https://github.com/actions/setup-node/commit/8170e22e8fa925daa88fcd5d20e66bbc3a163acb#diff-55f15e2366942ad15f71a41ac983f8ce9a9882b28b7fd9082f3a26c799783064L16

_Originally posted by @eddiemonge in https://github.com/actions/setup-node/issues/801#issuecomment-1639013411_
            

@colinrotherham how did you actually fix it?

**Comment by colinrotherham** [comment]
For the cache option you have to default to `''` now not `null`

**Comment by eddiemonge** [comment]
That should really have been a breaking change requiring a bump to version 4 then.

**Comment by eddiemonge** [comment]
That did not fix it for me.

I'm using a custom reusable action:
```
name: Setup NodeJS
description: Setups NodeJS and install dependencies

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: ${{ hashFiles('**/package-lock.json') && 'npm' || '' }}
    - run: npm install --ignore-scripts
      shell: bash
    - run: npm rebuild && npm run prepare --if-present
      shell: bash
```

The consuming action is:
```
name: Build Node App

runs:
  using: 'composite'
  steps:
    - uses: custom/setup-node
    - run: npm run build
```

Output is
```
Post job cleanup.
Error: Cache folder paths are not retrieved for npm with cache-dependency-path = 
```
