### ISSUE TITLE
Install nightly builds

### ISSUE THREAD

**Issue by arcanis** [actions/setup-node#80]
It would be nice if we could install the nightly builds instead of the stable ones. In our case we'd use it to ensure that we always are compatible with the latest Node master.

The nightly are available here: https://nodejs.org/download/nightly/index.json

**Comment by bryanmacfarlane** [comment]
Thanks.  I'll look into this along with the other version work like "LTS", "latest".  I suppose "nightly" would be a version option?

**Comment by cspotcode** [comment]
Is there any way for me to use nightlies today, perhaps by specifying a URL to the tar.gz or something?

**Comment by dmitry-shibanov** [comment]
Hello everyone. We released and updated the major [tag](https://github.com/actions/setup-node/releases/tag/v3.6.0) with changes to install nightly builds. Could you please confirm that everything works as expected. 
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16-nightly'
      - run: npm ci
      - run: npm test
```
