### ISSUE TITLE
setup-node can't use zstd compression in Ubuntu 22.04 runners

### ISSUE THREAD

**Issue by bateleurX** [actions/setup-node#800]
**Description:**
setup-node can't manipulate zstd cache archives in Ubuntu 22.04 runners.
actions/cache ver 3.0.4 that is used by setup-node has a bug(https://github.com/actions/toolkit/pull/1353) that blocks zstd usage on Ubuntu 22.04 runners.

Update dependent npm package actions/cache to versions >=3.1.4 to use zstd archive in Ubuntu 22.04 runners.

**Action version:**
v3.7.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
pnpm 8.6.0

**Repro steps:**  
Create pnpm cache with following workflow
```
runs:
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
```

**Expected behavior:**
Cache archive should be compressed in zstd.

**Actual behavior:**
Cache archive is compressed in gzip.

```
Post job cleanup.
Post job cleanup.
/usr/bin/tar --posix -z -cf cache.tgz --exclude cache.tgz -P -C /home/runner/work/abcde/abcde --files-from manifest.txt
Cache Size: ~208 MB (217621075 B)
Cache saved successfully
Cache saved with the key: node-cache-Linux-pnpm-1234567890abcdef
Post job cleanup.
Pruning is unnecessary.
```
