### ISSUE TITLE
No token found and can't prompt for login when running with --non-interactive.

### ISSUE THREAD

**Issue by leadream** [actions/setup-node#81]
In my repo I have the workflow like this:
```yml
- run: yarn publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```

I've added `NPM_AUTH_TOKEN` to secrets, but got this error:

![image](https://user-images.githubusercontent.com/12868055/68112019-63875180-ff2b-11e9-8747-c996676940a8.png)

```sh
Run yarn publish
  yarn publish
  shell: /bin/bash -e {0}
  env:
    NODE_AUTH_TOKEN: ***
yarn publish v1.19.1
[1/4] Bumping version...
info Current version: 0.1.22
[2/4] Logging in...
error No token found and can't prompt for login when running with --non-interactive.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
##[error]Process completed with exit code 1.
```

I have tried many times and can't figure it out. My repo is https://github.com/leadream/juuust-icon.
Can anyone help me? Thanks!

**Comment by clarkbw** [comment]
Yarn requires `always-auth` to authorize, NPM tends to ignore this.  Add it like this:

```yml
      - uses: actions/setup-node@v1
        with:
          always-auth: true
```

**Comment by leadream** [comment]
@clarkbw thanks, I'll try it.

**Comment by leadream** [comment]
> Yarn requires `always-auth` to authorize, NPM tends to ignore this. Add it like this:
> 
> ```yaml
>       - uses: actions/setup-node@v1
>         with:
>           always-auth: true
> ```

Still don't work for me, but adding this line in below works.
```yml
- run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
```

**Comment by D4nte** [comment]
Hi,

I have the same issue. One repo it works: https://github.com/comit-network/comit-js-sdk/ but then the same config does not work on a different repo: https://github.com/comit-network/create-comit-app/pull/243/checks?check_run_id=330403347

Is the solution above the official one or should we follow up with yarn to fix it?

**Comment by ammmze** [comment]
> ```yaml
> echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
> ```

You may wanna check your the log in the actions to ensure the token isn't getting logged in there. I'm not sure if github scrubs secrets from the log output or not. If they are scrubbing the output, then it should be all good. I didn't feel like testing it out.

I brought it in as an environment variable so it is evaluated in the shell rather than before sending to the shell.

```yaml
- name: Publish
  run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc && yarn publish
  env:
    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
```

And the result is the logged output just shows the name of the environment variable.
![sync-pom-version-to-package@859fa53 2020-03-28 10-40-31](https://user-images.githubusercontent.com/203336/77829654-9e5b7300-70e0-11ea-9f54-5918b348c10d.png)

**Comment by jorenbroekema** [comment]
For me I just need to supply the following:

```yaml
steps:
    - uses: actions/checkout@v2
    - name: Publish new version to NPM
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
        registry-url: 'https://registry.npmjs.org'
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

https://help.github.com/en/actions/language-and-framework-guides/publishing-nodejs-packages

This sets the always-auth automatically, as well as the registry and scope etc.

**Comment by chrvadala** [comment]
@jorenbroekema suggestion worked for me

**Comment by bryanmacfarlane** [comment]
Anything to doc or improve here?  I see the link to help above and it sounds like it was enough.

**Comment by CSFlorin** [comment]
I've tried all the solutions above and none seems to work for me. [Here are the various runs](https://github.com/CSFlorin/react-onboard/actions). And I have my npm token: 
![image](https://user-images.githubusercontent.com/9855031/86522229-94e45400-be0f-11ea-82ea-1eec45d116be.png)

[And here is the action file](https://github.com/CSFlorin/react-onboard/blob/master/.github/workflows/npm-publish.yml#L21). Anyone have an idea?

**Comment by jorenbroekema** [comment]
@CSFlorin  few things you can try:
On line 28: change it to `node-version: 12.x`     _(adding the x)_
On line 31: remove this entirely, setup-node action does it for you
On line 34: change it to NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}    _(so with spaces)_

I suspect either the 2nd or the 1st suggestion will fix things for you. Don't think the third one matters but you could always try.

**Comment by CSFlorin** [comment]
@jorenbroekema Thanks for the suggestions but I had already tried all these. See [the workflow file for this run](https://github.com/CSFlorin/react-onboard/actions/runs/157364393/workflow).

**Comment by jorenbroekema** [comment]
@CSFlorin You didn't try the third suggestion in that run. I doubt it matters, but it potentially could, if they use use a replacer / template parser where the spaces are relevant. I'm not sure what else it could be :\

**Comment by ndthanhdev** [comment]
I use below steps for workspace

```yarml
      # ...
      - run: yarn config set npmPublishRegistry 'https://npm.pkg.github.com/'
      - shell: pwsh
        env:
          GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
        run: yarn config set npmAuthToken "$env:GH_REGISTRY_TOKEN"
      - run: yarn workspaces foreach npm publish
```

**Comment by kumavis** [comment]
for `yarn publish`, adding `always-auth: true` to `actions/setup-node@v1` solved it for me :+1: 
```yml
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ matrix.node-version }}
        always-auth: true
```
