### ISSUE TITLE
node_version: lts/* resolving to different node versions within the same job

### ISSUE THREAD

**Issue by stephenhmarsh** [actions/setup-node#833]
**Description:**

 I have downstream workflows that rely on a cache key derived from the present Node version.  Currently, different jobs in the same workflow will sometimes run with different patch Node versions for the same specified value (`node-version: lts/*`)
 
 Example:
 ```Cache restored from key: Linux-v18-17-0-46f072a0cf8ec1430f2845c35deb5cf8f53452a2734e7af984bad2664da01429```
 ```Cache not found for input keys: Linux-v18-17-1-46f072a0cf8ec1430f2845c35deb5cf8f53452a2734e7af984bad2664da01429```
 

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

pnpm

**Repro steps:**  

Given a step like this used across different workflows in the same job:

```yaml
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'
```

**Expected behavior:**
Expect it doesn't run with different Node versions. `18.17.1` vs `18.17.0`

**Actual behavior:**
Currently some are `18.17.1` and some are `18.17.0`, so I can't reliably use my cache

<img width="1920" alt="Screenshot 2023-08-18 at 11 54 43 AM" src="https://github.com/actions/setup-node/assets/6576730/588509e4-0eda-40fc-83d2-a85e795ec189">
<img width="1920" alt="Screenshot 2023-08-18 at 11 55 07 AM" src="https://github.com/actions/setup-node/assets/6576730/3013500b-f11c-4c97-b2f9-2d5ebd4feab4">

**Comment by stephenhmarsh** [comment]
Sorry, it seems to be the same behavior described here: https://github.com/actions/setup-node/issues/562#issuecomment-1224924444

For now I have added `check-latest: true` and it seems to be resolved.

```
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
```
