### ISSUE TITLE
Heavy cache miss count

### ISSUE THREAD

**Issue by iBotPeaches** [actions/setup-node#835]
**Description:**
A large collection of "cache miss" and only a handful of "cache hit".

**Action version:**
`actions/setup-node@v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
```

**Repro steps:**  
```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - run: npm ci --verbose
      shell: bash
```      

**Expected behavior:**
A restore of previously downloaded artifacts

**Actual behavior:**
```
npm http fetch GET 200 https://registry.npmjs.org/locate-path 2237ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/json-stable-stringify-without-jsonify 2232ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz 777ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/update-browserslist-db 2424ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/mime-types 2300ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/lodash.merge 2297ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/json-schema-traverse 2291ms (cache miss)
npm http fetch GET 200 https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/6.4.0/fortawesome-fontawesome-common-types-6.4.0.tgz?created=xxx&expires=xxx&source=xxx&signature=xxx 6157ms (cache miss)
```

* tons and tons of cache miss.

Like why was yocto-queue a hit but not fontawesome?

---

So this is being reported because you get charged for using bandwidth when using Font Awesome. Sadly in our case - the basic example used here does not properly cache all items and I'm not following why. We get a hit restoring the cache blob, but it appears its quite small to what I expect.

```
/home/runner/.npm
Received 24691139 of 24691139 (100.0%), 30.4 MBs/sec
Cache Size: ~24 MB (24691139 B)
Cache restored successfully
Cache restored from key: node-cache-Linux-npm-912ac010d33c9c8d3694535a04cbea9be930f020a6b09d60b707ae2ce2d4db8b
```

I know this action does NOT cache node_modules, but then I struggle to understand the benefit I'm gaining here. Its clearly caching and restoring something, but since it doesn't cache the thing that costs us money then :(

We then get billed for overages and Font Awesome support just tells us to follow [this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) which we clearly do.

<img width="733" alt="Screenshot 2023-08-22 at 10 14 02 AM" src="https://github.com/actions/setup-node/assets/611784/3ba181a8-8b11-4171-a8a2-42c0676fe884">

**Comment by iBotPeaches** [comment]
So the large collection of misses was resolved by manually deleting/purging all the caches from that repository. The default cache key I assume is the lockfile hash, so why this happened - I'm not sure. Now the only thing not caching is the links from a private registry.

This private registry (Font Awesome) does not appear to ever successfully cache itself. I assume since the non node_modules cache is HTTP responses and these expire after 20 minutes. So the cache is respecting the TTL and thus becoming misses on builds.

I don't know if this means we should go back to rolling our own cache - (caching node_modules, skipping install if cache hit, etc) or just missing something here.

**Comment by dusan-trickovic** [comment]
Hello, @iBotPeaches ! Thanks for reporting this issue, we will take a closer look and see what can be done :)

**Comment by codepuncher** [comment]
I too am experiencing this same issue with FontAwesome. It is having a large impact on us and our budgets with overage charges.
We have many repositories that are facing this issue.

The only difference that I can see is that we are using `yarn` rather than `npm`.

**Comment by iBotPeaches** [comment]
@codepuncher - I dug into this a lot with FA, who honestly just kept redirecting me back to official GitHub docs on caching. You can't really use setup-node, etc with FA Pro and expect to keep your bandwidth.

We mixed two forms of cache now.

```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: node_modules
        key: ${{ inputs.node-version }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ inputs.node-version }}-node-${{ hashFiles('**/package-lock.json') }}

    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.directory }}
      shell: bash
```
(this is in a composite action)

We restore cache using regular setup-node, but then we attempt to restore a 1-1 cache based on the exact hash of the lock file. If we find a match for that, we skip `npm ci` - which is what would eventually hit FA Pro servers again and bleed bandwidth due to what I described above.

If that cache is a miss, we already restored the npm global cache (the 1st cache) so our cold/miss timing is still pretty fast as we are just installing the FA Pro, the private packages and whatever caused the miss (new version, etc)

This has kept us under the 2gb bandwidth limit for Sept.
