### ISSUE TITLE
with:-parameters not taken in account?

### ISSUE THREAD

**Issue by tobsch** [actions/setup-node#86]
Excuse me, I am pretty much of a newbie but do not understand why my job does not use the parameters I supply.

I want to publish to gpr, but it does not use the supplied registry url:
```
name: npm Package
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        scope: '@ramp106'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Error:
```
...
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/vue-components - You must be logged in to publish packages.
```

I literally used the example action and it does not run?
