### ISSUE TITLE
node-version: 'latest' taking 20+ minuites 

### ISSUE THREAD

**Issue by andyslack** [actions/setup-node#873]
**Description:**

Node setup taking forever (20m+) when using `latest`

Exmaple:

<img width="1073" alt="screenshot" src="https://github.com/actions/setup-node/assets/3747768/5c512552-b599-47d4-af8c-e2b359085d51">

Code:

```
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 'latest'
```

Is the latest version not caches somewhere?

**Action version:**
actions/setup-node@v3

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Comment by andyslack** [comment]
Example of this failing.

<img width="1082" alt="Screenshot 2023-10-18 at 11 03 09" src="https://github.com/actions/setup-node/assets/3747768/0ace418a-cf7e-465a-ac48-9e9be78f8249">

**Comment by daonb** [comment]
I'm getting it too. I'm use `latest` as the node version and the Log is:
```
❯ gh run view 6558471842 --log-failed
test    Node setup      2023-10-18T08:48:29.8829257Z ##[group]Run actions/setup-node@v3
test    Node setup      2023-10-18T08:48:29.8829747Z with:
test    Node setup      2023-10-18T08:48:29.8830054Z   node-version: latest
test    Node setup      2023-10-18T08:48:29.8830412Z   always-auth: false
test    Node setup      2023-10-18T08:48:29.8830776Z   check-latest: false
test    Node setup      2023-10-18T08:48:29.8831318Z   token: ***
test    Node setup      2023-10-18T08:48:29.8831613Z ##[endgroup]
test    Node setup      2023-10-18T08:48:30.3387908Z getting latest node version...
test    Node setup      2023-10-18T08:48:30.3411536Z getting latest node version...
test    Node setup      2023-10-18T08:48:30.3413660Z Attempting to download v21.0.0...
test    Node setup      2023-10-18T08:48:30.6240758Z Not found in manifest. Falling back to download directly from Node
test    Node setup      2023-10-18T08:48:30.6557915Z Acquiring 21.0.0 - x64 from https://nodejs.org/dist/v21.0.0/node-v21.0.0-linux-x64.tar.gz
test    Node setup      2023-10-18T08:53:10.8209480Z aborted
test    Node setup      2023-10-18T08:53:10.8209977Z Waiting 14 seconds before trying again
test    Node setup      2023-10-18T09:02:35.6053574Z aborted
test    Node setup      2023-10-18T09:02:35.6054014Z Waiting 16 seconds before trying again
test    Node setup      2023-10-18T09:05:51.9376210Z ##[error]aborted
```

**Comment by tksx1227** [comment]
The same problem occurs when version `19.8.1` is specified.
At least as of two days ago I had the same problem.

```yaml
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
```

![スクリーンショット 2023-10-18 午後6 12 48](https://github.com/actions/setup-node/assets/59915788/7b9a7e7a-95eb-4157-8e24-f844af2cad1d)

I can get the tar.gz file correctly with curl, so I wonder if there is a problem with the cache handling in the @actions/tool-cache library?

![スクリーンショット 2023-10-18 午後7 33 51](https://github.com/actions/setup-node/assets/59915788/e588b08f-7756-4e02-9135-540c0fa0f18f)

**Comment by jordanerf** [comment]
Same issue here using
```
- name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.6.0'
```

Is there a chance this is related to last week's temp download dir change by any chance? https://github.com/actions/setup-node/commit/2a017f350dbf6c4b6bb4508cc83809719115162e

**Comment by andyslack** [comment]
Same with `node-version: '19'`

![Screenshot 2023-10-18 at 15 32 30](https://github.com/actions/setup-node/assets/3747768/c1ed500d-c7ef-4b06-8700-725a7ec1ba25)

**Comment by mrollinsiv** [comment]
We are also seeing this issue. Anytime we try and install node v18, if Node's downloads are slow that day it always fails. We didn't have this issue on earlier node versions.

**Comment by marko-zivic-93** [comment]
Hello @andyslack 
Thank you for submitting this issue. We will investigate and come back to you as soon as possible 🚀

**Comment by andyslack** [comment]
@marko-zivic-93 let me know if there is anything I can do to help!

**Comment by githubjonas** [comment]
Same problem here too.
```
jobs:
  test_frontend:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.x

    - name: Build
      run: |
        yarn install

    - name: Test
      run: |
        npm test
```

**Comment by juanmanjarres** [comment]
I'm getting the same issue with 19.1 since yesterday
<img width="1106" alt="Screenshot 2023-10-19 at 9 53 42 AM" src="https://github.com/actions/setup-node/assets/11811569/d867482d-ae32-4cb4-9f04-02f8945e32d5">

**Comment by ert78gb** [comment]
Same with node `21`. The install or post-install steps fail almost every run

**Comment by ivan-barragan** [comment]
Builds are failing for us as well. Downloads taking upwards of 7 hours.

**Comment by crespire** [comment]
This is happening for us as well, using `latest`.

**Comment by aaronklinker-st** [comment]
Had the same problem with v3, but it only happens intermittently. Tried v4 out, same problem.

**Comment by bonniegrubbs** [comment]
I found some information that might help others. If you can upgrade your version of node to an LTS version found in the [manifest ](https://github.com/actions/node-versions/blob/main/versions-manifest.json), I believe the builds will use the cached version from `actions/node-versions` and skip the download step. This [link](https://github.com/actions/setup-node#supported-version-syntax) has more information, specifically this part:
"current/latest/node always resolve to the latest [dist version](https://nodejs.org/dist/index.json). That version is then downloaded from actions/node-versions if possible, or directly from Node.js if not. Since it will not be cached always, there is possibility of hitting rate limit when downloading from dist"

**Comment by andyslack** [comment]
@bonniegrubbs I think you are correct here.

Might be a good idea to add options to the manifest for `latest-cached` and also root versions e.g. `18` `19` rather than having to specify `18.18.2`

Just an idea to make it more user friendly.

**Comment by mbrevda** [comment]
Seeing this, too, with pinned versions of node. Sometimes the download fails and the ci failed. Is there some way to add more verbosity to try and see whats breaking down? Also, would it make sense to add a retry mechanism? Things generally work after re-running the workflow, so if we can just automate that it would allow ci to pass.

**Comment by stefcameron** [comment]
What I'm seeing with `setup-node@v4` is whether I use `'latest'` or '>=21.2', for example, the "best" I get is `v18.19.1` while the _actual_ latest is `v21.7.0` right now.

```yml
    strategy:
      matrix:
        node-version: ['>=21.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm
```
