### ISSUE TITLE
Slow post-action after v4

### ISSUE THREAD

**Issue by TrygveUrdahl** [actions/setup-node#878]
**Description:**
The post-action step for this action seems to have become much slower after version 4.0.0 was released.
In the two included images, the only major difference should be the version of `actions/setup-node`.

Before:
![image](https://github.com/actions/setup-node/assets/38653456/bafe9670-a139-4c2d-aa66-d9344fcdfc84)

After:
![image](https://github.com/actions/setup-node/assets/38653456/525afa09-fcd5-47ac-b131-ff6cf1f556bd)

**Action version:**
Using `actions/setup-node@v4` 15 hours after 4.0.0 was released.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Node 18.18.2, and `Yarn@4.0.0`.

**Comment by TrygveUrdahl** [comment]
I noticed that my workflow files didn't specify what node version to use for this workflow through any `node-version` or `node-version-file`. By adding that, and upgrading my project to use node 20, this issue seems to go away.

**Comment by nikolai-laevskii** [comment]
Thank you for detailed description of the issue! We'll investigate it and come back with details.

**Comment by panva** [comment]
> I noticed that my workflow files didn't specify what node version to use for this workflow through any `node-version` or `node-version-file`. By adding that, and upgrading my project to use node 20, this issue seems to go away.

My workflows do always specify `node-version` but the post-action is slow as well.

I also have a flow log [here](https://github.com/panva/jose/actions/runs/6643396154/job/18050359751#step:3:10) which despite requesting lts/iron resolved `20.8.1` which isn't lts/iron. This particular setup-node use is from a reused worflow, when setup-node is used outside of a reused workflow the correct `20.9.0` is resolved.

**Comment by bodinsamuel** [comment]
Just want to report the same thing, from 5s -> 2m15s (Node 18)
Previous: https://github.com/specfy/stack-analyser/actions/runs/6664890448/job/18113374316
With the upgrade: https://github.com/specfy/stack-analyser/actions/runs/6664871105/job/18113316689?pr=84

**Comment by ledermann** [comment]
Same here in multiple projects using JS with Yarn. The `Post Setup Node.js` job slows down from a few seconds to about 2:20 minutes after upgrading to v4. 

It seems to me that this only happens when JS dependencies have been updated. Re-running the job (which causes a cache hit) is fast again - perhaps because the cache doesn't need to be saved.

My conclusion: **Saving the cache** is significantly slower with v4 than with v3.

**Comment by ari-becker** [comment]
Noticing this as well because I have an aggressive `timeout-minutes: 1` on my `actions/setup-node` step, which is now causing many of my builds to fail.

I concur with @ledermann that the issue is somewhere in cache-saving.

With a cache hit, the post-action takes `0s` as expected:

![image](https://github.com/actions/setup-node/assets/1388505/e418cb1e-b4d7-4a42-a065-8ef0b8f04016)

Without a cache hit, when trying to save the cache, the post-action times out:

![image](https://github.com/actions/setup-node/assets/1388505/c41c2c8c-3aad-4424-bc34-90e28a5eda50)

**Comment by eregon** [comment]
See https://github.com/ruby/setup-ruby/issues/543 which explains a possible cause and fix.

**Comment by jraoult** [comment]
And here's the fix: https://github.com/ruby/setup-ruby/commit/036ef458ddccddb148a2b9fb67e95a22fdbf728b that should probably be ported to setup-node

**Comment by xiniria** [comment]
@nikolai-laevskii I opened a PR in #907 that applies the same fix as https://github.com/ruby/setup-ruby (issue https://github.com/ruby/setup-ruby/issues/543, PR https://github.com/ruby/setup-ruby/pull/546), could you take a look at it?

**Comment by nrutman** [comment]
I'm also experiencing this on Node 18.

**Comment by dmitry-shibanov** [comment]
Hello everyone. We've merged the fix for the issue. Could you please try to use `actions/setup-node@main` to confirm that it works as expected?

**Comment by uncenter** [comment]
Made a typo in that commit 😅 . I'll let you know if it appears to be working or not. It doesn't always have the issue but I'll try to run the action a few times to make sure.
![Screenshot 2023-12-13 at 06 48 17 (Arc)](https://github.com/actions/setup-node/assets/47499684/41baeeac-cb61-4580-a358-652045fbc4c0)

**Comment by TrygveUrdahl** [comment]
> Hello everyone. We've merged the fix for the issue. Could you please try to use `actions/setup-node@main` to confirm that it works as expected?

Hi! Yeah, from some quick tests it seems to work better now.

**Comment by colinrotherham** [comment]
@dmitry-shibanov Just confirming that [the fix has worked for us too](https://github.com/alphagov/govuk-frontend/actions/runs/7212675178)

We only really noticed it on Windows where all those tiny `node_modules` really affect performance:

## Before

<img width="310" alt="Windows cache restore time before (5m 38s)" src="https://github.com/actions/setup-node/assets/415517/1c6910c8-c60e-4f9a-8ed7-462581a89d5e">

## After

<img width="316" alt="Windows cache restore time after (1m 46s)" src="https://github.com/actions/setup-node/assets/415517/415c5198-ed6b-402a-9a69-a6f75beab4bf">

**Comment by kireerik** [comment]
@dmitry-shibanov Can you release the changes?

**Comment by aparnajyothi-y** [comment]
Hello everyone. We released the changes yesterday.

For now I am going to close the issue. If you have any concerns feel free to ping us.

**Comment by r-dev-limited** [comment]
I am using v4 with node 20. And it basically hangs forever, any idea how to fix it ?

**Comment by compojoom** [comment]
Hey guys! I wanted to share my experience here. Maybe it could help someone.
I was pulling my hair today and wondered why actions/cache is sooooo slow! Then I found this doc:
https://github.com/actions/cache/blob/main/caching-strategies.md
Which made me think that it could be the calculation of my cache key that is so slow.
You see nextjs is suggesting you do the following:
https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching

```
uses: actions/cache@v4
with:
  # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
  path: |
    ~/.npm
    ${{ github.workspace }}/.next/cache
  # Generate a new cache whenever packages or source files change.
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```

As you can notice the hashFiles function is looking for js, jsx, ts and tsx files. In my project we are talking about 1000s of files. So I split the job in restore and save parts and when saving I reuse the key from the restore job. 

This actually seems to have fixed the post action for me.

**Comment by simon-abbott** [comment]
@compojoom Good thought, but unfortunately that's not the case here. The cache key is [calculated during the cache restore step](https://github.com/actions/setup-node/blob/39370e3970a6d050c480ffad4ff0ed4d3fdee5af/src/cache-restore.ts#L20-L47) (using only the lockfile) and is [re-used without recalculation](https://github.com/actions/setup-node/blob/39370e3970a6d050c480ffad4ff0ed4d3fdee5af/src/cache-save.ts#L36) during the post-job action.

I think this step really is just slow because the cache directory is huge, and thus takes a while to sync across to the cache.

**Comment by compojoom** [comment]
@simon-abbott oh sorry. I posted in the wrong repo. setup-node is fast in my jobs. I was having issues with the "actions/cache" job

**Comment by domhhv** [comment]
@aparnajyothi-y Hello, and thank you for getting back to me! Everything you described makes perfect sense to me.

I can see that I'm only caching `yarn.lock` in my workflow at this moment, so I'll definitely give it a try to also cache `package.json` and Yarn cache directory.

Thanks!

**Comment by reedws** [comment]
Is there a reason this fix has not been tagged and released yet?

**Comment by oerp-odoo** [comment]
I also get very slow post actions. It might be related with caching.

![Image](https://github.com/user-attachments/assets/78efef39-a9e9-4da8-a2bf-982919d4a1ad)

My workflow:

```yaml
---
name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # requites to grab the history of the PR
          fetch-depth: 0
      - uses: actions/setup-python@v4.4.0
        with:
          python-version: "3.10"
          cache: "pip"
      - run: python -m pip install pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key:
            pre-commit-4|${{ env.pythonLocation }}|${{
            hashFiles('.pre-commit-config.yaml') }}
      - run:
          pre-commit run --show-diff-on-failure --color=always --from-ref ${{
          github.event.pull_request.base.sha }} --to-ref ${{ github.sha }}
```
