### ISSUE TITLE
Log Node.js version using

### ISSUE THREAD

**Issue by fishcharlie** [actions/setup-node#90]
Couple of things.

First if you specify `node-version` of `10`, does that use the absoute latest version of Node.js v10 (both minor and patch versions)?

Second, does `node-version` of `10.x` use the latest version when taking account patch versions? Or does `.x` just mean the minor version?

Finally, it'd be great if this action printed the Node.js version it decided to use in the logs of GitHub Actions so developers can determine which Node.js version it decided to use, which would make debugging SO much easier.

<img width="1055" alt="Screen Shot 2019-11-22 at 3 49 46 PM" src="https://user-images.githubusercontent.com/860375/69465889-bb052a00-0d3f-11ea-8f40-41f5e163aecf.png">

**Comment by joshmgross** [comment]
👋 Hey @fishcharlie. Specifying a `node-version` of `10` and `10.x` will have the same result. This follows [semver](https://semver.org/), where `10 == 10.x == 10.x.x`, which is effectively "the latest version of Node.js v10 taking into account both minor and patch versions. 

>Finally, it'd be great if this action printed the Node.js version it decided to use in the logs of GitHub Actions

Great idea! That should be a quick fix.

**Comment by bryanmacfarlane** [comment]
Yes, it should work with any semver version spec.  As part of this issue, I'll make sure it's logged as well.  I'll also update the readme / docs

**Comment by fishcharlie** [comment]
Any updates on this? cc/ @bryanmacfarlane @joshmgross

**Comment by joshmgross** [comment]
@bryanmacfarlane are you still planning on doing this? If not,  I can pick this up.

**Comment by bryanmacfarlane** [comment]
@joshmgross - I'm fine with you picking this up.  If you do, look at recent commits in setup-go where I did it.  I think it should also output npm version.

**Comment by fishcharlie** [comment]
Outputting the npm version too would be amazing!!!

**Comment by demian85** [comment]
Can someone please explain why my node version is not 12 as specified?

Part of my config file is
```
jobs:
  primary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing dependencies
        run: npm install
``` 

And logging the node version to the console results in `node version: 10.20.1` 

I do not quite understand where is the problem.
