### ISSUE TITLE
Registry-url doesn't work

### ISSUE THREAD

**Issue by what1s1ove** [actions/setup-node#911]
**Description:**
When setting `registry-url` the result of running `npm publish --dry-run` remains the default instead of the configured value.

**Action version:**
4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node: v18.19.0, npm: 10.2.3

**Repro steps:**  
```yml
name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  gpr-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'

      - run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior:**
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm

**Actual behavior:**
There must be https://registry.npmjs.org/ instead https://registry.npmjs.org/
