### ISSUE TITLE
Support volta.extends in node-version-file

### ISSUE THREAD

**Issue by ThisIsManta** [actions/setup-node#920]
**Description:**

Given the repository containing the below files
```json
// package.json
{ "volta": { "node": "20.0.0" } }
```
and
```json
// e2e/package.json
{ "volta": { "extends": "../package.json" } }
```

When the action is called with...
```yml
      - uses: actions/setup-node@v4
        with:
          node-version-file: e2e/package.json
```
Then it should result in Node.js v20.0.0 because this is how Volta works: https://docs.volta.sh/advanced/workspaces

But instead, I got the below error:
![image](https://github.com/actions/setup-node/assets/5592654/038b5fc9-c801-4ceb-9d75-95c941ab7278)

**Justification:**
If `setup-node` action claim to support **Volta**, then this `extends` field should be read and resolve into a concrete value of Node.js version as well.

**Are you willing to submit a PR?**
Yes, here you are: https://github.com/actions/setup-node/pull/921
