### ISSUE TITLE
node-version as fallback of node-version-file

### ISSUE THREAD

**Issue by y-nk** [actions/setup-node#939]
**Description:**
Currently the behavior is that `node-version` is preferred rather than `node-version-file` if both are provided.

https://github.com/actions/setup-node/blob/d86ebcd40b3cb50b156bfa44dd277faf38282d12/src/main.ts#L85-L95

I would like to propose the opposite since `node-version` is actually hardcoded in the action parameters, but the file is not guaranteed to be there.

https://github.com/actions/setup-node/blob/d86ebcd40b3cb50b156bfa44dd277faf38282d12/src/util.ts#L8-L12

**Currently**, scenarios resolved as following:

```yaml
with:
  node-version: 8 # nothing to see here
```

```yaml
with:
  node-version-file: fileExists.json # all good
```

```yaml
with:
  node-version-file: fileDoesNotExists.json # throws error and crashes the pipeline
```

```yaml
with:
  node-version: 8
  node-version-file: fileExists.json # ignored, picked version is 8
```

```yaml
with:
  node-version: 8
  node-version-file: fileDoesNotExists.json # ignored, picked version is 8
```

What I'm requesting for is a change in the 2 lasts scenarios:

```yaml
with:
  node-version: 8
  node-version-file: fileExists.json # picked
```

```yaml
with:
  node-version: 8
  node-version-file: fileDoesNotExists.json # does not throw and picks version 8 instead
```

**Justification:**
This is just a nicer API, i think. it does not remove the case of conscious crash of the pipeline if no `node-version` is given, but it does nicely propose a fail-safe for people interested.

**Are you willing to submit a PR?**
Yes, i'm ok.

**Comment by aparnajyothi-y** [comment]
Hello @y-nk
Thank you for creating this issue, we will investigate it and come back to you as soon as we have some feedback.

**Comment by fregante** [comment]
To me this feels backwards; generally, config files are the default and "inline settings/flags" override the defaults. If you're specifying a `node-version`, then you most likely prefer that one over the "project-level" version defined in the package.json

**Comment by y-nk** [comment]
@fregante that is untrue, especially in monorepos where the node-version file can be there (or not) depending on the package/service running the job, but you could always use a hardcoded base version as a fallback.

**Comment by y-nk** [comment]
@fregante i understand your standpoint. as a mean not to remain unblocked, would you have any recommendation for something less verbose/more elegant than this:

```yml

    - if: ${{ !inputs.workspaceRelativePath }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        registry-url: https://npm.pkg.github.com/
        scope: '@company'

    - if: ${{ inputs.workspaceRelativePath }}
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ format('{0}/.node-version', inputs.workspaceRelativePath) }}
        cache: 'pnpm'
        registry-url: https://npm.pkg.github.com/
        scope: '@company'
```

?

**Comment by mk-pmb** [comment]
I agree with @fregante in that I expect my explicitly given parameter in the CI workflow file to have more weight than the files in the repo. My CI workflow is there to keep repo file changes in check. Maybe we can have a weak option `fallback-node-version`; albeit I'd prefer combining all of the possibilities into just `node-version` as a priority list. You could then specify something like `>=16; file:package.json; file:.nvmrc; ; 18; 20` that works like this:

* `>=16` sets a mandatory requirement. If our decision would conflict with that, it's a fatal error.
* `file:package.json` if possible, decide by this file and ignore further entries.
* `file:.nvmrc` if possible, decide by this file and ignore further entries.
* (empty) ignore. The calling workflow probably had a variable insertion here that happened to not be used in this case.
* `18` a literal version. Since this decision mechanism will always succeed, the list will always end here.
* `20` probably an accident since this can never be reached. We could consider warning users about this, or silently ignore it because the previous `18` may have been from an optional parameter like the empty slot was.

**Comment by ssbarnea** [comment]
I have an issue closely related to this that is related to use of multiple node version 

```shell
$ cat .tool-versions 
nodejs 20.18.0 18.20.4
``` 

Basically the `.tool-versions` file defines two different node versions that are supported by the project, with 20 being the implicit one.

Currently it seems impossible to use `actions/setup-node` to create a test matrix that uses these two versions as there is no argument that I pass to tell it to use one or another.

This means that if I want to test both, I have to copy the exact version from the `.tool-versions` into all the GHA workflows that are running with both versions and also to find a magic way to keep this in sync, so they will not diverge.

Does anyone have a workaround for this issue?

**Comment by y-nk** [comment]
@ssbarnea you need to create a first job which will read the .tool-versions and build a json out of it (using job outputs), then pass that json to a 2nd job into your matrix.

```yaml
job1:
  runs-on: ubuntu-latest
  outputs:
    versions: ${{ toJSON(steps.tool-versions.outputs.result) }}

  steps:
    - id: tool-versions
      run: echo "result=[\"20.18.0\", \"18.20.4\"]" >> $GITHUB_OUTPUT
      # add your logic above. probably use jq or something else

job2:
  needs: job1
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: ${{ fromJSON(needs.job1.outputs.versions) }}
  steps:
    - uses: actions/setup-node@v5
      node-version: ${{ matrix.node-version }}
```

drafted hastily so some typos may occur ; general idea is there.
