### ISSUE TITLE
Publish to github repository fails....

### ISSUE THREAD

**Issue by ildella** [actions/setup-node#942]
**Description:**

This workflow fails for authentication issues:

```yaml
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        registry-url: https://npm.pkg.github.com/
    - run: yarn workspaces focus --all --production
    - run: yarn npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Action version:**

v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ x] Hosted
- [ ] Self-hosted

**Tools version:**

yarn v4

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.

**Expected behavior:**

It should work out of the box. 

**Actual behavior:**

It fails with this error: 

```
➤ YN0033: No authentication configured for request
➤ YN0000: Failed with errors in 0s 162ms
Error: Process completed with exit code 1.
```

**Comment by aparnajyothi-y** [comment]
Hello @ildella , Thank you for creating this issue and we will look into it :)

**Comment by johnseekins-pathccm** [comment]
Running into this issue using `@v4` as well. Doing a bit of digging, it _seems_ that `.npmrc` isn't getting created within the action context.

**Comment by davepar** [comment]
Running into a similar issue trying to access a private registry.

**Comment by priya-kinthali** [comment]
Hello @ildella ,
The error you're encountering appears to be due to the authentication not being correctly configured for publishing to your GitHub repository. In order to resolve this issue please update your workflow as below: 
```
- name: Authentication
  run: |
    echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
  env:
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- run: yarn workspaces focus --all --production
- run: |
    yarn npm publish
```
In addition to this, ensure that a `publishConfig` field is included in your `package.json file`. This field specifies the registry that your package will be published to.
 ```
"publishConfig": {
    "registry": "https://npm.pkg.github.com/username”
  },
```
I hope this helps! If you have any further questions or issues, please reach out to us.

**Comment by priya-kinthali** [comment]
Hello @johnseekins-pathccm 👋 , 
Thank you for your response! We are able to publish successfully with `v4 `using below setup:
```
steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: '20'
      cache: 'npm'
      registry-url: 'https://npm.pkg.github.com'
  - run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
  The `.npmrc` file is being created in a temporary directory under the runner's working directory. This is current expected behaviour.
  If you are still facing error, please consider opening an issue in the `actions/setup-node` repository, by providing further details that includes - the specific error, your current workflow, or any relevant links that could help us in reproducing the problem. We appreciate your understanding and cooperation!
  
  Hello @ildella 👋, Hope the provided solution related to authentication worked for you!
  For now i am closing this issue. If you have any issues please feel free to ping us. Thank you!
