### ISSUE TITLE
Npm public login require but new bug

### ISSUE THREAD

**Issue by plsgivemeachane** [actions/setup-node#974]
npm notice === Tarball Details === 
npm notice name:          @quanvndev/waterx                       
npm notice version:       1.0.5                                   
npm notice filename:      @quanvndev/waterx-1.0.5.tgz             
npm notice package size:  129.4 kB                                
npm notice unpacked size: 525.8 kB                                
npm notice shasum:        8edca9b935[51](https://github.com/plsgivemeachane/WaterX/actions/runs/8058032465/job/22010421318#step:5:52)a8d8806cace4fdeea3734f9683a5
npm notice integrity:     sha[51](https://github.com/plsgivemeachane/WaterX/actions/runs/8058032465/job/22010421318#step:5:52)2-8a4WKePggCg3l[...]zvROWUZgv8gpg==
npm notice total files:   32                                      
npm notice 
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2024-02-27T01_20_[58](https://github.com/plsgivemeachane/WaterX/actions/runs/8058032465/job/22010421318#step:5:59)_187Z-debug-0.log
Error: Process completed with exit code 1.
**Description:**
Github actions bug need login when already pass through the GITHUB_ACTION token
already read other duppilcate closed issue

```yml
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
