### ISSUE TITLE
Unable to connect npm with Nexus repo with correct credentials provided by a Github repository secret

### ISSUE THREAD

**Issue by AlexandreSimon44** [actions/setup-node#977]
**Description:**
Usage of self hosted Nexus as Npm repository leads to Error 401 with correct credentials encoded in Base64, provided by a Github repository secret

**Action version:**
Use the @v4

**Platform:**
- Ubuntu

**Runner type:**
- Hosted

**Tools version:**
Use node 14.15.4

**Repro steps:**  
With a private Nexus try to npm ping in a workflow

```
name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.15.4
      uses: actions/setup-node@v4
      with:
        always-auth: true
        node-version: 14.15.4
        registry-url: https://your-nexus.example.fr/repository/npm-public/
        token: ${{ secrets.NPM_TOKEN }}
    - name: Npm ping
      run: npm ping
```

**Expected behavior:**
In Npm ping step
```
Run npm ping
npm notice PING https://your-nexus.example.fr/
npm notice PONG 0.201ms
```

**Actual behavior:**
In Npm ping step
```
Run npm ping
npm notice PING https://your-nexus.example.fr/repository/npm-public/
npm ERR! code E401
npm ERR! Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"

npm ERR! A complete log of this run can be found in:
npm ERR!     ***.log
Error: Process completed with exit code 1.
```

**Comment by HarithaVattikuti** [comment]
Hello @AlexandreSimon44 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by AlexandreSimon44** [comment]
# Update

I am now able to connect to Nexus after adding a .npmrc file to the sources of my project.

## .npmrc file
```
registry=https://your-nexus.example.fr/repository/npm-public/
_auth=${NPM_TOKEN}
```

## The new workflow file
```
name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.15.4
      uses: actions/setup-node@v4
      with:
        always-auth: true
        node-version: 14.15.4
    - name: Npm install
      if: success()
      run: npm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
