### ISSUE TITLE
Add lts alias for lts/*

### ISSUE THREAD

**Issue by zdm** [actions/setup-node#996]
**Description:**
Could you please add simple `lts` alias for the latest lts version in addition to the `lts/*`?
`lts/*` is not obvious, ugly and confusing.

If ypu don't want to do this - please, close this issue immediately,

**Comment by HarithaVattikuti** [comment]
Hello @zdm 
Thank you for creating this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by ThePlenkov** [comment]
oh wow! That's exactly how I reached here. So following the official [doc ](https://github.com/actions/setup-node)page:
```
- uses: actions/setup-node@v4
  with:
    # Version Spec of the version to use in SemVer notation.
    # It also admits such aliases as lts, latest, nightly and canary builds
    # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
    node-version: ''
```

we can see ` It also admits such aliases as lts`

but this is what we get in real:
```
Run actions/setup-node@v4
  with:
    node-version: lts
    registry-url: https://registry.npmjs.org/
    always-auth: false
    check-latest: false
    token: ***
Attempting to download lts...
Not found in manifest. Falling back to download directly from Node
```
